### ISSUE TITLE
--docker option in docker build 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#1015]
### Describe your problem(s)

--docker command should not be the mandatory option for the docker build. Providing --docker-image and --docker-base-image should be enough. 

### Describe your solution

if --docker-image or --docker-base-image is provided then, consider it as a docker build. If only --docker option is given prompt for docker image and the base image.

### How will you implement it

---

**Comment by praminda** [comment]
Fix merged
