### ISSUE TITLE
500 with Null pointer Exception, if no certificate exists under the given alias in jwt config

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1020]
### Description:
When the certificate alias given in the micro-gw.conf does not exist in the microgateway runtime truststore, a null pointer exception is thrown (in jwt scenario). 

### Steps to reproduce:
Provide non existing certificate alias name for JWT config in micro-gw.conf. 

### Affected Product Version:
3.1.0-alpha

### Environment details (with versions):
- OS: MacOS Mojave
- Client:
- Env (Docker/K8s): 

---

**Comment by AmaliMatharaarachchi** [comment]
related to https://github.com/ballerina-platform/ballerina-lang/issues/20896

**Comment by VirajSalaka** [comment]
Closing the issue as it is fixed in the 3.2.0-alpha.
