### ISSUE TITLE
Default version APIs imported from the API Manager are not identified.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1021]
### Description:
In wso2 API Manager, a user can set a certain API version to act as the default version. When we import such a default API, the microgateway does not identify default version property. 
The reason: When we call the publisher REST API, we set the "expand" parameter to false. Hence we do not get the default version property in the response.  If we set this to true, then JSON mapping will be failed and needs to be fixed at the code level.

### Steps to reproduce:
Create a default API in the API Manager and import that API.

### Affected Product Version:
3.1.0-alpha

### Environment details (with versions):
- OS: MacOS Mojave
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
@VirajSalaka Is this something we supported earlier and suddenly dropped during the 3.1.0 development?

**Comment by VirajSalaka** [comment]
Yes. At the moment this could not be supported. The reason is that when we import the API from publisher, what we do is simply save the openAPI definition in our project structure. And this property is not included in the openAPI definition. Therefore we have decided to drop this.

**Comment by praminda** [comment]
Does that mean we no longer support importing default version APIs from WSO2 APIM to MGW as default version APIs? This happens only if we use APIM 3.x right? For 2.6.0 it should work I believe/

**Comment by VirajSalaka** [comment]
Nope we are not AFAIR. In 2.6.0 case, we can identify whether the default version is set. But still, we cannot either save two openAPIs with the different basePaths or add to another extension.
