### ISSUE TITLE
If Authentication Failure happens for a inbound request with analytics enabled, an error log is printed. 

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1039]
### Description:
The following error log is printed if there is an authentication failure.
```
ERROR [wso2/gateway/src/gateway/utils] - [AnalyticsFilter] [37dd6e0a-f934-4352-9949-6148a6df5fa5] Error while publishing analytics data : error {ballerina}TypeCastError message=incompatible types: '()' cannot be cast to 'string'
```

### Steps to reproduce:
Enable analytics and invoke API with an invalid token.

### Affected Product Version:
3.1.0-alpha

### Environment details (with versions):
- OS: MacOS Mojave
- Client:
- Env (Docker/K8s):
- Analytics - 3.1.0-beta

---
#### Suggested Labels:
Priority/Low

**Comment by Rajith90** [comment]
This can not be reproduced in the current master branch

**Comment by VirajSalaka** [comment]
There is some missing information in the error description.
This specifically happens if the authentication failure happens due to JWT signature failure.
