### ISSUE TITLE
Authorization header does not work for basic authentication

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#1043]
### Steps to reproduce:
use x-wso2-auth-header extension to define an authorization header
x-wso2-auth-header : "x-authorization"

use this auth header to send the request. it gets the below error without processing from any auth filter.
`"fault": {
        "code": 900901,
        "message": "Invalid Credentials",
        "description": "Invalid Credentials. Make sure you have given the correct access token"
    }`

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by VirajSalaka** [comment]
Will be looking into this.
