### ISSUE TITLE
Failed to build with OAPI v3 swagger JSON

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/product-microgateway#1044]
### Description:
`micro-gw build <project_name>` fails when trying to build a project which is initiated by the default [petstore OAPI v3](http://petstore.swagger.io:8080/api/v3/openapi.json) swagger JSON with the error `Malformed URL is provided: '/api/v3'`

### Steps to reproduce:
1. `micro-gw init petstore -a http://petstore.swagger.io:8080/api/v3/openapi.json`
2. `micro-gw build petstore`

### Affected Product Version:
3.1.0-beta

**Comment by VirajSalaka** [comment]
We have to provide a proper error message saying that either the user should use x-wso2-production-endpoints / x-wso2-sandbox-endpoints or the user needs to provide the complete url (rather than the relative path in the servers object)
