### ISSUE TITLE
Update toolkit rest API versions by default to 3.1.0

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#1046]
### Description:
Toolkit config.toml uses the rest api versions v1.0 and dcr version v0.15. We need to update these to work with APIM 3.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by AmaliMatharaarachchi** [comment]
Duplicate https://github.com/wso2/product-microgateway/issues/995
