### ISSUE TITLE
Mutual SSL authentication is not working

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#1054]
### Steps to reproduce:
add following to the swagger api
x-wso2-transports:
 mutualssl: "mandatory"

Try it with postman after configuring certs.
give authentication failure.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
#### Suggested Labels:

3.1.0 beta

**Comment by AmaliMatharaarachchi** [comment]
Mutual SSL is not working with HTTP 2. By default, micrgateway is HTTP 2. For mutual SSL authentication to be supported, HTTP version should be configured to 1

**Comment by Rajith90** [comment]
This is fixed with the ballerina version upgrade to 1.1.5 with the PR : https://github.com/wso2/product-microgateway/pull/1208
