### ISSUE TITLE
Analytics : API creator field is not set in the event if it is fault event or throttle event.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1055]
### Description:
When the request is successful, the microgateway sends the API creator field in the event. But when it is a fault scenario or throttled out scenario, the API creator field is set to "_unknown_".

### Steps to reproduce:
Check the event created for fault scenario and success scenario.

### Affected Product Version:
Affected/3.1.0-alpha

### Environment details (with versions):
- OS: MacOS Mojave
- Client:
- Env (Docker/K8s):
- Analytics: 3.1.0-beta

---

**Comment by VirajSalaka** [comment]
Will work on this

**Comment by Rajith90** [comment]
This only set in the throttle event , not in the fault event, Hence reopening the issue
