### ISSUE TITLE
Toolkit fails when folder path has directory names with spaces

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#1056]
### Steps to reproduce:
toolkit path similar to:
/Users/amali/workspace/**beta testing**/wso2am-micro-gw-toolkit-macos-3.1.0-beta-SNAPSHOT
cd into toolkit and run init project command.
`./micro-gw init pet`
`JAVA_HOME is externally set: /Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home
Error: Could not find or load main class testing.wso2am-micro-gw-toolkit-macos-3.1.0-beta-SNAPSHOT.lib`

### Affected Product Version:

3.1.0 beta

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Rajith90** [comment]
@chashikajw will work on this
