### ISSUE TITLE
Method of setting environment variable when a project starts running is not correct

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/product-microgateway#1064]
### Description:
When trying to define a basic security scheme for back-end, an error generates when trying to build the project with environment variables with the steps provided in the docs. It should be updated to use `--` instead of `-e` in the command to the end as below.
`bash gateway <path_to_the_excutable_file> --myEndpoint3_prod_basic_password=123456 `

### Steps to reproduce:
`bash gateway -e myEndpoint3_prod_basic_password=123456 <path_to_the_excutable_file>` for a initiated project.

### Content Positioning in Documentation:

- Link: [https://docs.wso2.com/display/MG310/Defining+a+Backend+Security+Scheme](https://docs.wso2.com/display/MG310/Defining+a+Backend+Security+Scheme)

**Comment by Rajith90** [comment]
This is fixed in documentation
