### ISSUE TITLE
API Key authentication

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#1093]
### Describe your problem(s)

Provide API Key authentication support for microgateway. 

### How will you implement it

---
#### Related Issues:

https://github.com/wso2/product-microgateway/issues/897

#### Suggested Labels:

3.1.0

**Comment by AmaliMatharaarachchi** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/932

**Comment by praminda** [comment]
Duplicates #897
