### ISSUE TITLE
Auth related issues

### ISSUE THREAD

**Issue by praminda** [wso2/product-microgateway#1103]
### Description:

1. If resource has combination of openapi security requirements including OAuth requirement with scopes, Trying to invoke that resource with non oauth method also requires correct scopes.
1. AFAIK MGW auth doesn't claim the support for basicauth at the moment, However if above case if we try to invoke the resource with a user who has the required scope it successfully authenticates the request. Which means scope validation has happened. But defining scopes in solely basic auth protected resource allows users without scope to authenticate for the resource.

### Steps to reproduce:
1. Create an API using yaml file in [sample.zip](https://github.com/wso2/product-microgateway/files/4286920/sample.yaml.zip).
2. Invoke `/pet/{petId}` resource with basic auth or api_key auth and observe the output.

### Affected Product Version:

3.1.0-beta
### Environment details (with versions):
- OS: MacOs
- Client: curl
- Env (Docker/K8s):

**Comment by VirajSalaka** [comment]
In the generated ballerina code, this is how the resourceconfig  looks like,

```
@http:ResourceConfig {
        methods:["GET"],
        path:"/pet/{petId}",
        auth:{
        
            
                scopes: ["read"], 
        
            authHandlers: gateway:getAuthHandlers(["basic","oauth2","jwt","apikey"], false, false)
        }
    }
```
By looking at this, it feels like the scopes are applied for all the auth handlers. But if we consider basicAuth, AFAIK there is no concept called scopes. @ldclakmal can you please comment on this?

**Comment by ldclakmal** [comment]
In Ballerina, scope concept applied for all the inbound authentication providers including basic auth, oauth2 and jwt. Here, the "read" scope applied for all the `authHandlers` configured. There is no way to bind "handler" and "scope" as couples as of now.

**Comment by praminda** [comment]
Looks like there is no simple solution for this. 
Considering the usage of `scopes` concept we may not need to fix this urgently but just to know the options we have, lets say we move away from this annotation and try enable/disable scope validation programmatically on each auth provider? Is that something we can do

**Comment by Rajith90** [comment]
Currently basic auth and API key does not, check the scope validation. We need to support the validation

**Comment by VirajSalaka** [comment]
To handle this issue, it is required to provide the scopes with the basicAuth configurations in the micro-gw.conf. 
Here is a sample.
```
[b7a.users]
  [b7a.users.generalUser1]
    password="5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8"
    scopes="write:pets,read:pets"
```

**Comment by Rajith90** [comment]
If basic auth is used with oauth2 security schema that have scopes then the scope validation will happen as mentioned in the previous comment.

When API key is used with oauth2 security schema that have scopes we need to skip the scope validation for the api key since scopes are not applicable to api key security schema. This validation is skipped using https://github.com/wso2/product-microgateway/pull/1134
