### ISSUE TITLE
FileNotFoundException occurs when running on Windows

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/product-microgateway#1107]
### Description:
FileNotFoundException run-time exception occurs when running a project on Windows. But the servers are started regardless.

![image](https://user-images.githubusercontent.com/25485783/75952566-f2699380-5e63-11ea-9b0a-312f09970e40.png)

### Steps to reproduce:
1. Build a project in Windows
2. Run the project using `gateway <path-to-MGW-executable-file>`

### Affected Product Version:
3.1.0-beta

### Environment details (with versions):
- OS: Windows 10

**Comment by praminda** [comment]
Happens due to wrong arguments provided to `tools` jar in `gateway.bat` file. I will send a PR with the fix.
