### ISSUE TITLE
In Java Interceptors, if the payload is a JSON Array, getJsonPayload does not work.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1150]
### Description:
If the response.getJsonPayload method is called from the java interceptor and the received payload is JSON Array, it throws an error.

```
error: {ballerina}TypeCastError message=incompatible types: 'error' cannot be cast to 'lang.array:$anonType$0|()'
	at wso2.pizza__service_0:get08637edc9c284a5e87db4c467885ced6(PizzaShackAPI__1_0_0.bal:315)
```
This happens due to creating a JSONObject with a json array string. It should be a JSONArray object instead of that.
https://github.com/wso2/product-microgateway/blob/d7dcfbc7e04ca5e006a8d68e172c7064472732dd/components/micro-gateway-interceptor/src/main/java/org/wso2/micro/gateway/interceptor/Entity.java#L169

### Steps to reproduce:
Build a microgateway project with a java interceptor which includes response.getJsonPayload method. The backend should send a JSON Array. 

### Affected Product Version:
3.1.0-beta

### Environment details (with versions):
- OS: MacOS Mojave
- Client:
- Env (Docker/K8s):

---
#### Suggested Labels:
Affected/3.1.0-beta

**Comment by Rajith90** [comment]
getJsonArrayPayload and setJsonPayload(JSONArray jsonArrayPayload) will be introduced the the Request and Response Objects.
So the java array objects can be retrieved and set.
