### ISSUE TITLE
Error when defining only resource level endpoints

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-microgateway#1176]
### Description:
I am getting the following error when defined only the resource level endpoints using the extension x-wso2-production-endpoints. 

**Error:**
micro-gw: Error while parsing the openAPI defintion for the API "Online-Store-Api : v1.0.0".
	-The provided endpoint using the "servers" object is invalid.
	-Malformed Url is provided :/

**Swagger Def:**

```
openapi: 3.0.0
info:
  title: Online-Store-Api
  version: v1.0.0
  description: This API contains operations related to online shopping store.
x-wso2-basePath: /storemep/{version}
paths:
  /products:
    get:
      x-wso2-production-endpoints:
        urls:
          - http://products.micro
      responses:
        "200":
          description: ""

  /products/{productId}:
    get:
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      x-wso2-production-endpoints:
        urls:
          - http://products.micro
      responses:
        "200":
          description: ""
```

### Affected Product Version:
3.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
@VirajSalaka is this something related to fix done for #1044?

**Comment by VirajSalaka** [comment]
https://github.com/wso2/product-microgateway/issues/963 This is the reason I think.

**Comment by VirajSalaka** [comment]
The issue is not completely solved. I will send the PR with the fix.
