### ISSUE TITLE
Configuration for WSO2 API Manager 3.0.0 not matching up with tool kit dir structure

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/product-microgateway#1177]
I downloaded the latest MGW ToolKit (3.0.4) and trying out to Configuration for WSO2 API Manager 3.0.0 description given in [1]. Given instruction is not matching up with the tool kit dir structure [2].
<img width="658" alt="Screen Shot 2020-03-28 at 12 06 14 AM" src="https://user-images.githubusercontent.com/3397321/77817770-e485e780-708a-11ea-9c0b-91d8cf73d6cb.png">
<img width="1635" alt="Screen Shot 2020-03-28 at 12 10 24 AM" src="https://user-images.githubusercontent.com/3397321/77817776-e780d800-708a-11ea-92ea-5c9d816c6762.png">

**Comment by praminda** [comment]
@vanjikumaran Please stick to the issue template provided in each issue type when creating issues. This helps us properly track and keep issue list organized for later reference.

**Comment by praminda** [comment]
Doc [Configuration for WSO2 API Manager 3.0.0](https://docs.wso2.com/display/MG300/Configuration+for+WSO2+API+Manager+3.0.0#ConfigurationforWSO2APIManager3.0.0-ConfiguringtheMicrogateway3.0.xToolkit) is updated with a note explaining the behavior.
