### ISSUE TITLE
CORs example is outdated

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#1178]
### Description:

https://github.com/wso2/product-microgateway/blob/master/samples/cors_sample.yaml
The above example is given in https://docs.wso2.com/display/MG310/Enabling+CORS document
but it is outdated.

1. "access-control-allow-origins:" this needs to be changed to "accessControlAllowOrigins:"
2. Add accessControlAllowCredentials

### Affected Product Version:

3.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
This is a doc issue. Not a product bug. 😉 You should have used the doc template.

**Comment by AmaliMatharaarachchi** [comment]
Docs updated. the extension is supported for both formats.
