### ISSUE TITLE
Improvement to support multiple token issuers with Claim Mappings

### ISSUE THREAD

**Issue by tharmini** [wso2/product-microgateway#1179]
### Describe your problem(s)
When JWT retrieved from Multiple Identity providers Gateway should able to validate the JWT and map the Relevant Claims

### Describe your solution
1. Retrieve the Issuer from Given JWT.
2. Retrieve the issuer details from the config file
3. Validate the JWT signature against that.
4. Transform the JWT from Map Claims.

### How will you implement it

---

**Comment by Rajith90** [comment]
Fixed with : https://github.com/wso2/product-microgateway/pull/1180
