### ISSUE TITLE
Update samples in passing environment variables

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-microgateway#1188]
### Description:
Outdated samples in providing the password as an environment variable.

> bash gateway -e <Endpoint Name>_<Endpoint Type>_basic_password=<passowrd> <path_to_the_excutable_file>

should be corrected as 
(otherwise getting an error saying 
**ballerina: too many arguments to call the 'main' function**)

```
bash gateway --<Endpoint Name>_<Endpoint Type>_basic_password=<passowrd> <path_to_the_excutable_file>
```

### Content Positioning in Documentation:

-  https://docs.wso2.com/display/MG300/Defining+a+Backend+Security+Scheme
-  https://github.com/wso2/product-microgateway/blob/master/README.md#5-define-backend-security-parameters

**Comment by praminda** [comment]
> https://docs.wso2.com/display/MG300/Defining+a+Backend+Security+Scheme

This example should work for MG 30x versions. [310 document](https://docs.wso2.com/display/MG310/Defining+a+Backend+Security+Scheme) is already updated with the required changes.

However the read me is outdated. We'll update it. 
Thanks for reporting the issue
