### ISSUE TITLE
Basic auth header is removed when x-wso2-disable-security: true

### ISSUE THREAD

**Issue by umerasir** [wso2/product-microgateway#1189]
### Description:
Basic authentication header is removed when x-wso2-disable-security: true and is no longer present when request is received by user defined  interceptor. 
we are trying to validate basic auth hearder as part of interceptor. this was working in version 3.0.1 but there were other issue so moved to 3.1.0. but in latest version header is altogether removed.

### Steps to reproduce:
```yaml
/public/rt/PING:
    get:
      description: ""
      operationId: PING
      x-wso2-disable-security: true
      x-wso2-request-interceptor: java:org.mgw.interceptor.IDSAuthInterceptor
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PING"
            application/xml:
              schema:
                $ref: "#/components/schemas/PING"
      security:
        - basicAuthentication: []
```

### Affected Product Version:
3.1.0

**Comment by Rajith90** [comment]
Could you please add the following config to micro-gw.conf and check

```toml
[authConfig]
  # Remove authorization header from the backend request
  removeAuthHeaderFromOutMessage = false
```

**Comment by umerasir** [comment]
thanks. it did work.
