### ISSUE TITLE
Not able to get remote address from caller in request interceptor 

### ISSUE THREAD

**Issue by umerasir** [wso2/product-microgateway#1192]
### Description:
I am using java interceptor for a request in WSO2 microgateway 3.1.0.
 I wanted to determine client ip address who made the request. its always empty when trying to fetch from _Caller_. Also "X-FORWARDED-FOR" header is not available as part of Request

### JAVA Interceptor

```
public class MyInterceptor implements Interceptor {

   ...
   ...
    public boolean interceptRequest(Caller caller, Request request) {
          ...
          // Supposed to print remote address as a string in the format host:port
          System.out.println("remote address " + caller.getRemoteAddress());
         ...
    }
  ...
```

### Output

remote address  :57669

Only port is populated no host info available

**Comment by praminda** [comment]
@umerasir This is a known issue in ballerina `http:Caller`. You can find the original issue in ballerina-platform/ballerina-lang#22283
Anyway we expect ballerina team will do patch release very soon with a set of bug fixes. Once that is available we'll also do a MGW patch release with the fixes

**Comment by umerasir** [comment]
@praminda i manged  to fetch it from Request. Is it okay if i use this?
        ```
ObjectValue nativeRequestObject = request.getNativeRequestObject();

        HashMap<String, Object> nativeData = nativeRequestObject.getNativeData();
        HttpCarbonRequest transportMessage = (HttpCarbonRequest) nativeData.get("transport_message");

        Map<String, Object> transportMessageProperties = transportMessage.getProperties();
        InetSocketAddress remoteAddress = (InetSocketAddress) transportMessageProperties.get("REMOTE_ADDRESS");
        InetAddress inetAddress = remoteAddress.getAddress();
```

**Comment by praminda** [comment]
@chamil321 Any feedback on the above workaround?

**Comment by chamil321** [comment]
> HttpCarbonRequest transportMessage = (HttpCarbonRequest)nativeData.get("transport_message");

Shall we cast it to the `HttpCarbonMessage` and use 
```
transportMessage..getProperty("REMOTE_ADDRESS");
```
to get the address?

How ever we have fixed the original issue and will be providing the [fix this week](https://github.com/ballerina-platform/ballerina-lang/pull/22569)

**Comment by Rajith90** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/1320
