### ISSUE TITLE
Grafana Dashboard link is leading to a 404 page

### ISSUE THREAD

**Issue by fjunior87** [wso2/product-microgateway#1193]
### Description:
In the Microgateway Observability page () the link for the Microgateway Grafana Dashboard is leading to a 404 Page.

![image](https://user-images.githubusercontent.com/302112/78828372-fd5f9880-79ba-11ea-9790-c6cb09aa618a.png)

### Content Positioning in Documentation:

- Link: https://docs.wso2.com/display/MG310/Observability

---

**Comment by praminda** [comment]
@fjunior87 This is updated now. Thanks for reporting the issue. We are in the process of doing the final reviews of 310 documentation. Do let us know if you find any limitations or mistakes like this.
