### ISSUE TITLE
Wrong Instruction in the Message Transformation with Java for the jar location

### ISSUE THREAD

**Issue by fjunior87** [wso2/product-microgateway#1195]
### Description:
In the Message Transformation page[1] when instructing where to place the generated jar file for the Interceptors it mentions:

> Once java interceptors are written, then the interceptor project should be built and the output jar should be placed in the <MGW-project>/libs directory.

But the correct location should be MGW-project/lib directory.

[1]https://docs.wso2.com/display/MG310/Message+Transformation

### Content Positioning in Documentation:

- Link: https://docs.wso2.com/display/MG310/Message+Transformation

- Heading (& Step):

- Any other reference:

---

**Comment by praminda** [comment]
@fjunior87 This is updated now. Thanks for reporting the issue. We are in the process of doing the final reviews of 310 documentation. Do let us know if you find any limitations or mistakes like this.

**Comment by praminda** [comment]
Fixed it. Thanks for reporting the issue.
