### ISSUE TITLE
jmx_port property not being read from environment variable

### ISSUE THREAD

**Issue by fjunior87** [wso2/product-microgateway#1201]
### Describe your problem(s)
The jmx_port for the prometheus metrics is not getting retrieved when being set via environment variables like below:

`export b7a_observability_metrics_prometheus_jmx_port="8080"`

If I set it in the micro-gw.conf it works fine. The same behavior does not happen for the metrics _port_ and the _secure_port_ properties which I can change via env variables.

I tried this with Micro-gateway 3.1.0.

### How will you implement it

---

**Comment by praminda** [comment]
Hi @fjunior87 
Sorry for the delay in providing an update to this issue. Issue is fixed with PR 1361 and will be available with MGW 3.2.0.
