### ISSUE TITLE
Can we unify path for product performance result

### ISSUE THREAD

**Issue by lpastor74** [wso2/product-microgateway#1202]
**Description:**
Problem: Path for product performance report is not unified across every product. It is hard to find and the path is not descriptive at all.
Some product has performance result in branch root and it just has a number that increases. 

**Suggested Labels:**
The suggestion is to have a unique path (
example: 
**xxxxx/perfomace_results/latest**
while every previous result will have the version in the path like 
**xxxxx/perfomace_results/v2.6**

This way we can reference it in documentation without any issue.

**Comment by praminda** [comment]
@lpastor74 This is the unified url for mgw product perf summary.
https://github.com/wso2/product-microgateway/blob/performance/300-general/performance/benchmarks/summary.md

In this url if you change the version number like 260, 300, 310 you can get the general perf numbers for that version

**Comment by lpastor74** [comment]
I'm ok with nomenclatures but keeping is it in root he best solution?
