### ISSUE TITLE
Subscription Validation is not documented.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1204]
### Description:
Subscription Validation is not provided in the documentation. We should include details about the following aspects.

- the relation with API name and API version properties between the microgateway's openAPI and the publisher's API name.
- how to enable/disable
- How default-policy works

### Steps to reproduce:
N/A

### Content Positioning in Documentation:

N/A

- Heading (& Step):

- Any other reference:

---
#### Suggested Labels:
Severity Major

**Comment by AmaliMatharaarachchi** [comment]
Added to the documentation https://docs.wso2.com/display/MG310/Subscription+Validation
