### ISSUE TITLE
Error undefined symbol when API level interceptors

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#1212]
### Description:

Error while building a project with API level interceptors

### Steps to reproduce:
Create a project and copy an API definition.
Define a request interceptor in the API level of API definition. (reproducible for Ballerina interceptor)
Build the project.

You will observe error similar to below:
`test.bal:176:16: undefined symbol 'getc3fc8d0ee82342c3a2e490e9678ac7a7_api_response_interceptor_index'`

### Affected Product Version:

3.1.0 macos toolkit

### Environment details (with versions):
- OS: macos
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
Steps to reproduce should be updated as ,
Define a **~~request~~ response** interceptor in the API level of API definition. (reproducible for Ballerina interceptor)
