### ISSUE TITLE
Missing MessageContext Properties

### ISSUE THREAD

**Issue by amalkasubasinghe** [wso2/product-microgateway#1221]
### Describe your problem(s)
**Request a way to extract these information**

REST_API_CONTEXT (eg: /context/1.0.0) 
API_ELECTED_RESOURCE (eg: /resource/{playerId}) 
REST_FULL_REQUEST_PATH (eg: /context/1.0.0/resource/pathparam) - can get from REQUEST_RAWPATH
REST_SUB_REQUEST_PATH (eg: /resource/pathparam) 

**Is this information available when the analytics enabled?**

request.execution.start.time
api.ut.backendRequestEndTime
api.ut.backendRequestTime (Must need)
backend_latency

### How will you implement it

---

**Comment by Rajith90** [comment]
Request informations are available as in explained by comment[1].

Analytics related data:
Can be found from the following properties in invocation context.
request.execution.start.time : requestTimestamp
api.ut.backendRequestEndTime : timeStampResponseIn
api.ut.backendRequestTime (Must need) : timeStampRequestOut
backend_latency : the diff of above two

[1] - https://github.com/wso2/product-microgateway/issues/1210#issuecomment-618425433

**Comment by Rajith90** [comment]
The requested data can be retrieved. Hence closing the issue. Please reopen If further properties are required.
