### ISSUE TITLE
base64EncodedCert cannot be used in the interceptor.

### ISSUE THREAD

**Issue by Senthuran100** [wso2/product-microgateway#1237]
### Description:
When base64EncodedCert method is used in the interceptor of the Microgateway and when we build the microgateway project an error is thrown as an invalid operation: type 'ballerina/http:MutualSslHandshake'

### Steps to reproduce:
Use the interceptor which contains the base64EncodedCert as below.
`        string? base64EncodedCert = mtls?.base64EncodedCert;    
`
Then build the Microgateway project. 
We can notice the below error

> invalid operation: type 'ballerina/http:MutualSslHandshake' does not support optional field access for field 'base64EncodedCert'

base64EncodedCert is used in ballerina 1.2.x but APIM 3.1.0 uses ballerina 1.1.4.
### Affected Product Version:
API Microgateway Toolkit Mac-3.1.0, API Microgateway Toolkit Linux- 3.1.0, API Microgateway Toolkit  Windows 3.1.0
#### Suggested Labels:
MG 3.1.0

**Comment by Rajith90** [comment]
This was fixed with ballerina 1.1.5 version and fix will be available with microgateway 3.1.1 version
