### ISSUE TITLE
X-wso2-basepath support for Envoy gateway

### ISSUE THREAD

**Issue by chashikajw** [wso2/product-microgateway#1241]
### Describe your problem(s)

Need to implement the x-wso2-basepath extension support for envoy gateway.
### Describe your solution

Currently we  expose the api with default basepath.
default basepath: /api/v3/
curl  **http://localhost:10000/api/v3/pet/5** -v

Need to support a x-wso2 basepath and after that user can expose the Api like below
x-wso2-basepath: /petstore/v2
curl **http://localhost:10000/petstore/v2/pet/5** -v

### How will you implement it

---

**Comment by menakaj** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/1240
