### ISSUE TITLE
Gateway runtime does not recognize etcd arguments 

### ISSUE THREAD

**Issue by JamieMac96** [wso2/product-microgateway#1243]
### Steps to reproduce:

1. Download and install the latest version as per the guide
2. setup local etcd server
3. build and run the gateway as specified in the documentation: https://docs.wso2.com/display/MG300/Service+Discovery#example-store-key-value
4. Output: 
`Path to executable jar file is invalid`

I then changed the order of the arguments and placed the etcd arguments after the executable and got the following message: 
`ballerina: too many arguments to call the 'main' function`

 
### Environment details (with versions):
- OS: ubuntu 18.04
- Client:
- Env (Docker/K8s): VM

---

**Comment by Rajith90** [comment]
If you are using the micro gateway 3.1.0 version could you please follow the doc [1], in which the command is [2]

[1] - https://docs.wso2.com/display/MG310/Service+Discovery#example-store-key-value
[2] - 
```
gateway /Users/kim/Downloads/TestProj/petstore-project/target/petstore-project.jar --etcdurl=http://127.0.0.1:2379 --etcdusername=root --etcdpassword=pass --etcdtimer=10000
```

**Comment by JamieMac96** [comment]
@Rajith90 Thanks for this, my mistake. Is there any scope for adding a -help option for the gateway command? Think it would clear up a lot of this type of confusion.
