### ISSUE TITLE
Using Self-Signed Certificates for JWT Validation Results in NullPointerException

### ISSUE THREAD

**Issue by molinab297-unisys** [wso2/product-microgateway#1265]
### Description:

Using a self-signed certificate for JWT validation results in a null pointer exception being thrown, with no logging in the microgw.log file (even with trace logging enabled).

### Steps to reproduce:

1). Generate a self-signed certificate (in my case, I'm using a self-signed certificate from my own private [KeyCloak](https://www.keycloak.org/) server).

2). Run the following commands to import the SSL cert into the ballerina stores (following instructions [here](https://docs.wso2.com/display/MG310/Importing+Certificates+to+the+API+Microgateway+Truststore)):

```
[root]# openssl x509 -inform der -in keycloak.cert -out keycloak.pem
[root]# keytool -import -keystore $MGW_TOOLKIT_HOME/lib/platform/bre/security/ballerinaTruststore.p12 -alias wso2carbonjwt -file keycloak.pem
[root]# keytool -import -keystore $MGW_RUNTIME_HOME/runtime/bre/security/ballerinaTruststore.p12 -alias wso2carbonjwt -file keycloak.pem
``` 

and here's the certificate in the trust stores (using keytool):

```
Alias name: wso2carbonjwt
Creation date: Jun 5, 2020
Entry type: trustedCertEntry

Owner: CN=localhost
Issuer: CN=localhost
Serial number: b1ef7fe9ac5a19d3
Valid from: Fri Jun 05 14:14:40 EDT 2020 until: Mon Jun 03 14:14:40 EDT 2030
Certificate fingerprints:
         MD5:  C8:DC:E3:44:3C:08:3A:D7:F9:AE:0B:AA:96:AA:BC:8A
         SHA1: B1:97:4C:F7:C9:D7:07:BE:6C:53:38:4C:ED:DC:CE:F9:A3:69:44:0D
         SHA256: 3A:7A:4D:AF:DC:92:D8:2D:06:28:5D:90:CA:63:F1:EF:A8:33:46:CE:43:37:81:99:B2:0D:BF:D6:03:21:0E:CF
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

```

3). Update the micro-gw.conf file to use the wso2carbonjwt certificate (following instructions [here](https://docs.wso2.com/pages/viewpage.action?pageId=141255241)):

```
[[jwtTokenConfig]]
  issuer = "https://<keycloak server IP>/auth/realms/master"
  audience = "account"
  certificateAlias = "wso2carbonjwt"
  validateSubscription = false
```

4). Run the normal commands to build the docker image and run the microgateway (following instructions [here](https://docs.wso2.com/display/MG310/Install+on+Docker)):
```
[root]# micro-gw init petstore
[root]# micro-gw build petstore --deployment-config deployment.toml
[root]# docker run -d -p 9090:9090 -p 9095:9095 petstore:v1
[root]# TOKEN=eyJhbGciOi..
[root]# curl -X GET "https://localhost:9095/petstore/v1/pet/1" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
```

After doing all of this, I get this back: ```java.lang.NullPointerException```

### Affected Product Version:
3.1.0

### Environment details (with versions):
- OS: CentOS 7
- Client:
- Env (Docker/K8s): Docker 1.13.1

---
#### Related Issues:

This sounds like it's related to #1020 , however that problem description states that this NPE occurs with invalid certificate aliases. In my case I believe I am using a valid certificate alias, is it maybe that the format of my self-signed certificate is invalid? Is there something else I need to do in order to setup JWT validation?

**Comment by praminda** [comment]
Hi @molinab297-unisys,

Seems like the sample provided in [documentation](https://docs.wso2.com/display/MG310/Install+on+Docker) doesn't include instructions to copy the truststore to mgw docker image. So if you haven't manually added instructions to copy the new truststore to built mgw docker image, it will use the default truststore inside the mgw base image. 

To get a working config, you can update your `deployment.toml` with matching docker `copyFiles` instructions for k8s sample in [this doc](https://docs.wso2.com/display/AM260/Deploying+the+API+Microgateway+in+Kubernetes)
Ex:
```toml
[docker.dockerCopyFiles]
  enable = true
  [[docker.dockerCopyFiles.files]]
    source = '/home/user/custom_truststore.p12'
    target = '/home/ballerina/runtime/bre/security/ballerinaTruststore.p12'
    isBallerinaConf = false
```

Thanks,
Praminda

**Comment by praminda** [comment]
I update the documentation [here](https://docs.wso2.com/display/MG310/Install+on+Docker)

**Comment by molinab297-unisys** [comment]
@praminda Thanks for the reply. I modified my deployment.toml to look like this:
```
[docker]
  [docker.dockerConfig]
    enable = true
    name = "petstore"
    registry = ''
    tag = 'v1'
    #buildImage = ''
    #dockerHost = ''
    #dockerCertPath = ''
    baseImage = 'wso2/wso2micro-gw:latest'
    #enableDebug = ''
    #debugPort = ''
    #push = ''
  [docker.dockerCopyFiles]
    enable = true
    [[docker.dockerCopyFiles.files]]
        source = '/usr/lib64/wso2/wso2am-micro-gw-toolkit/3.1.0/resources/conf/micro-gw.conf'
        target = '/home/ballerina/conf/micro-gw.conf'
        isBallerinaConf = true
    [[docker.dockerCopyFiles.files]]
        source = '/usr/lib64/wso2/wso2am-micro-gw-toolkit/3.1.0/lib/platform/bre/security/ballerinaTruststore.p12'
        target = '/home/ballerina/runtime/bre/security/ballerinaTruststore.p12'
        isBallerinaConf = false
```

Then rebuilt the docker image. However when invoking the API with a bearer token I still get a ```java.lang.NullPointerException```.

**Comment by praminda** [comment]
Hi @molinab297-unisys,
I've made a mistake in the target path for docker image's truststore file, correct path should be,
`/home/ballerina/wso2/runtime/bre/security/ballerinaTruststore.p12`

Sample: 
```toml
[[docker.dockerCopyFiles.files]]
    source = '/usr/lib64/wso2/wso2am-micro-gw-toolkit/3.1.0/lib/platform/bre/security/ballerinaTruststore.p12'
    target = '/home/ballerina/wso2/runtime/bre/security/ballerinaTruststore.p12'
    isBallerinaConf = false
```

**Comment by molinab297-unisys** [comment]
@praminda That appears to have fixed it! I'm now getting a response from the API and no more NPEs. Thank you.

**Comment by praminda** [comment]
@molinab297-unisys,

Great. 

Small note on the error logs,
When I tried to reproduce this scenario I saw there are some logs related to ballerina jwt validation in the microgw log. However the exact java certificate level exception trace is missing in the log. That happens due to ballerina limitation in printing java layer exception traces.

**Comment by molinab297-unisys** [comment]
@praminda I forgot to mention that in your last sample, the 'source' should actually point to the runtime's ballerina trust store, i.e.: 
```
[[docker.dockerCopyFiles.files]]
    source = '/usr/lib64/wso2/wso2am-micro-gw/3.1.0/runtime/bre/security/ballerinaTruststore.p12'
    target = '/home/ballerina/wso2/runtime/bre/security/ballerinaTruststore.p12'
    isBallerinaConf = false
```
Either that, or you actually have to import your self signed certificate into the wso2 toolkit's ballerina trust store (however, the docs [here](https://docs.wso2.com/display/AM250/Importing+Certificates+to+the+API+Microgateway+Truststore) indicate that you need to import the self signed cert into the runtime's store).
