### ISSUE TITLE
After configuring the global throttling in the micro gateway, error pops up once the server starts.

### ISSUE THREAD

**Issue by tharmini** [wso2/product-microgateway#1273]
### Description:
After configuring the global throttling in the micro gateway, an error pops up when starting the Microgateway.
### Steps to reproduce:
1. configure global throttling in MGW 
2. Start the APIM server
3. Start the MGW and now the error popups like below
<img width="1680" alt="Screen Shot 2020-06-11 at 2 46 51 PM" src="https://user-images.githubusercontent.com/29250881/84367843-68fbf700-abf2-11ea-8961-8da9c6b9e2e1.png">

### Affected Product Version:
MGW 3.2.0 

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Rajith90** [comment]
fixed with : https://github.com/wso2/product-microgateway/pull/1283
