### ISSUE TITLE
error: wso2/petstore:3.1.0::Swagger_Petstore_New__1_0_0.bal:109:1: error resolving value: DOCKER_USERNAME is not set in the environment

### ISSUE THREAD

**Issue by starsmall-xiaoqq** [wso2/product-microgateway#1275]
### Description:

  I setup username and password of docker registry in [kubernetes.kubernetesDeployment] like:

[kubernetes]
  [kubernetes.kubernetesDeployment]
    enable = true
    name = 'petstore'
    labels = '{"app": "petstore"}'
    replicas = '3'
    dockerHost = 'tcp://localhost:2375'
    push = true
    registry = 'index.docker.io/myname'
    username="myname"
    password='mypassword'
    baseImage = 'wso2/wso2micro-gw:3.1.0'

After run "micro-gw build perstore", the error as title is shown. 
I check the generated *.bal file, it does not use the specified "username" and "password".
 
    name:"petstore",
    labels:{"app": "petstore"},
    replicas:3,
    dockerHost:"tcp://localhost:2375",
    push:true,
    registry:"index.docker.io/myname",
    username:"$env{DOCKER_USERNAME}",
    password:"$env{DOCKER_PASSWORD}",
    baseImage:"wso2/wso2micro-gw:3.1.0" 

### Environment details (with versions):
- OS: windows10

- Client:
- Env (Docker/K8s):
docker for windows
---

**Comment by VirajSalaka** [comment]
It is required to provide the docker username and password as environmental variables. They are not picked from the script as it seems. Since you are using windows, please execute the following commands in the command prompt and try again.
```
SET DOCKER_USERNAME=<USER>
SET DOCKER_PASSWORD=<PASSWORD>
```
[1] https://docs.wso2.com/display/MG310/Install+on+Docker

**Comment by Rajith90** [comment]
@VirajSalaka
