### ISSUE TITLE
Global throttling is not working at Resource Level

### ISSUE THREAD

**Issue by tharmini** [wso2/product-microgateway#1276]
### Description:
1. Global throttling is not working at Resource Level. 
2. when enabling  [throttlingConfig.binary] to false and send a request in MGW then it popups error in the APIM server like below.
<img width="1306" alt="Screen Shot 2020-06-11 at 9 43 23 PM" src="https://user-images.githubusercontent.com/29250881/84412258-99f91d80-ac2c-11ea-820e-bfdffc96bfbd.png">

    

### Steps to reproduce:
1. Configure MGW for global throttling.
2. In advance policy of admin portal change the number of quota for a policy.
3. In MGW test the  resource Level global throttling for the particular policy at resouce level.

### Affected Product Version:
MGW 3.2.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by VirajSalaka** [comment]
Managed to reproduce the issue. Will look into this.

**Comment by VirajSalaka** [comment]
Related to https://github.com/wso2/product-apim/issues/7972

**Comment by Rajith90** [comment]
@tharmini could you please check this with 3.2.0 bet of APIM

**Comment by tharmini** [comment]
This issue still exists in 3.2.0 bet of APIM and global throttling is not working at Resource Level.

**Comment by menakaj** [comment]
Fixed in API Manager. https://github.com/wso2/carbon-analytics-common/commit/d05a92ae2b97003008b5208bd9b27662b004fd1c
