### ISSUE TITLE
Inconsistent error messages from API GW and API MGW

### ISSUE THREAD

**Issue by nadeesha5814** [wso2/product-microgateway#1291]
### Description:
In consistent error messages are provided as the response from API GW and API MGW. Messaging format  can be different (XML or JSON) but the error message should be consistent across the two products.

### Steps to reproduce:

Example - Error for invalid token
API Gateway
<ams:fault xmlns:ams="http://wso2.org/apimanager/security">
    <ams:code>900901</ams:code>
    <ams:message>Invalid Credentials</ams:message>
    <ams:description>Invalid JWT token. Failed to decode the token.. Make sure you have provided the correct security credentials</ams:description>
</ams:fault>

API Micro Gateway
{
    "fault": {
        "code": 900901,
        "message": "Invalid Credentials",
        "description": "Invalid Credentials. Make sure you have given the correct access token"
    }
}

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Rajith90** [comment]
I don't think we can make the error messages one to one same in both gateways. Since they are different technologies. The generic messages like auth failure, throttle failure and etc set we have made them similar as much as possible

**Comment by Rajith90** [comment]
Please re open if there are further concerns
