### ISSUE TITLE
Steps missing in the below documentation

### ISSUE THREAD

**Issue by nadeesha5814** [wso2/product-microgateway#1300]
### Description:
Steps to copy the conf file from Microgateway to the docker container missing in the below documentation.
https://docs.wso2.com/display/MG310/Observability#e19ed54e9a224173865e4a10a7cc45cc

Steps needed to be added
* Modifying deployment-config.toml file to include the below
[docker.dockerCopyFiles]
    enable = true
    [[docker.dockerCopyFiles.files]]
        source = '<Microgateway location>/conf/micro-gw.conf'
        target = '/home/ballerina/conf/micro-gw.conf'

### Content Positioning in Documentation:
https://docs.wso2.com/display/MG310/Observability#e19ed54e9a224173865e4a10a7cc45cc
- Link:

- Heading (& Step):

- Any other reference:

---

**Comment by nadeesha5814** [comment]
Further more it would be useful to include the below information as well
1.  Default IP of the container and how to find it. Docker container IP can be found using the following command.
docker inspect <container id> | grep '"IPAddress"' | head -n 1

2. How to check if Prometheus has connected successfully to the MGW. This can be done by navigating to targets pages in Prometheus. 

Without the above instructions it would be hard for someone who is new to docker and Prometheus to set this up.

**Comment by praminda** [comment]
@nadeesha5814 Thanks for trying out and suggesting the changes. We'll work on these.

**Comment by AmaliMatharaarachchi** [comment]
You can follow the document on docker specific guide in (https://docs.wso2.com/display/MG310/Install+on+Docker). As that doc mentions, you can refer the deployment-config.toml configuration guide in https://docs.wso2.com/display/MG310/deployment.toml+for+Docker.
