### ISSUE TITLE
Original request from the client disregarded when sending a validation request

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-microgateway#1313]
The current behavior of the HTTP caching implementation is to send a new HTTP request when the response needs to be validated. Instead of doing this, need to add the relevant precondition header(s) to the original request itself and forward it to the origin server.

See the following:
https://tools.ietf.org/html/rfc7234#section-4.3 
https://tools.ietf.org/html/rfc7232#section-3.2
https://tools.ietf.org/html/rfc7232#section-4.1

#### Related Issues:
Ballerina issue: https://github.com/ballerina-platform/ballerina-lang/issues/24534

### Steps to reproduce:
1.Enable response caching for the Microgateway as well as the backend.
2. If the backend responds with an ```Etag``` and ```cache-control``` header, the response will be cached and next requests will be served on the cached response. After some time a validation request will be sent with ```if-none-match``` header without original request headers.

### Affected Product Version:
MGW-3.1.0

**Comment by Rajith90** [comment]
@VirajSalaka

**Comment by VirajSalaka** [comment]
https://github.com/ballerina-platform/ballerina-lang/issues/24534 
Fixed in 3.2.0-beta. Hence the issue can be closed.
