### ISSUE TITLE
JWT custom Claim mapping is not working

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#1342]
### Description:

Mapping remote claims in jwt is not working.

### Steps to reproduce:
create project with https://petstore.swagger.io/v2/swagger.json
get a self jwt token with scope: "read:pets" 
Add similar to the following to micro-gw.conf
[[jwtTokenConfig]]
  issuer = "https://localhost:9443/oauth2/token"
  certificateAlias = "wso2apim310"
  validateSubscription = false
  consumerKeyClaim = "aud"
  [[jwtTokenConfig.claims]]
    remoteClaim = "scope"
    localClaim = "scp"
# enable backendjwt generator
[jwtGeneratorConfig]
  # Enable jwt generator
  jwtGeneratorEnabled=true
Invoke /pet/findByStatus which is scope protected resource.

Expected:
backendjwt has scp claim instead of the "scope".

### Affected Product Version:

3.2.0 beta

### Environment details (with versions):
- OS: catalina
- Client:
- Env (Docker/K8s):

---

**Comment by AmaliMatharaarachchi** [comment]
@tharmini Please take a look

**Comment by AmaliMatharaarachchi** [comment]
Two causes found:
1. This issue is reproducible when "audience" is not given for jwtTokenConfig. 
2. backendjwt generator is not using modified payload

**Comment by menakaj** [comment]
Fixed with #1345
