### ISSUE TITLE
Unable to create a user for etcd server

### ISSUE THREAD

**Issue by ShalkiWenushika** [wso2/product-microgateway#1355]
### Description
When creating user for etcs server following error occurs.
![Screenshot (190)](https://user-images.githubusercontent.com/35829027/88368191-26aa0600-cdab-11ea-946e-d04d188ef5b9.png)

### Steps to reproduce:
Download [etcd v3.4.5](https://github.com/etcd-io/etcd/releases/tag/v3.4.5) for windows.
Navigate to the unzipped etcd distribution and start the etcd server.
```
cd <etcd_HOME>
./etcd
```
Setup the required authentication with the service as follows:
`curl -L http://localhost:2379/v3/auth/user/add -X POST -d '{"name": "root", "password": "pass"}'`
### Affected Product Version:
3.2.0 beta

### Environment details (with versions):
- OS: Windows 10 Pro
- Client:
- Env (Docker/K8s):

---
#### Suggested Labels:
Type/bug

**Comment by praminda** [comment]
@ShalkiWenushika did we updated the docs?

**Comment by ShalkiWenushika** [comment]
> @ShalkiWenushika did we updated the docs?

Yes. 
this is the link to PR: https://github.com/wso2/docs-mg/pull/17
