### ISSUE TITLE
[envoy-gw] Need to implement a gRPC server for the envoy external auth service from java language

### ISSUE THREAD

**Issue by chashikajw** [wso2/product-microgateway#1412]
### Describe your problem(s)

As $subject, we need to implement a gRPC server for the envoy external auth filter from java language to make a connection between the external java filter chain and envoy proxy.

### Describe your solution

Use  [external_auth.proto ](https://github.com/envoyproxy/envoy/blob/master/api/envoy/service/auth/v3/external_auth.proto )  file to implement the gRPC server.

### How will you implement it

You can generate the required java code using [external_auth.proto ](https://github.com/envoyproxy/envoy/blob/master/api/envoy/service/auth/v3/external_auth.proto )  file or you can directly use already compiled stub dependency (https://mvnrepository.com/artifact/io.envoyproxy.controlplane/api).   

---

**Comment by Rajith90** [comment]
Fixed
