### ISSUE TITLE
[envoy-gw] Need to add a gRPC server testing setup for the envoy external auth service from go language

### ISSUE THREAD

**Issue by chashikajw** [wso2/product-microgateway#1422]
### Describe your problem(s)

As $subject, we need to add a gRPC server testing setup for the envoy external auth service from go language with jwt validation

### Describe your solution

- Implement gRPC server to envoy ext auth service

- Implement jwt validation with cache

**Comment by AmaliMatharaarachchi** [comment]
closing as fixed https://github.com/wso2/product-microgateway/pull/1423
