### ISSUE TITLE
[Envoy-MG] Implement envoy C++ filters to extend envoy functionalities

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#1443]
### Describe your problem(s)
Envoy can be extended using filters. Microgateway need request level interceptor to call the external filter chain and also a response filter in order to publish analytics

### Describe your solution
Write C++ filters and custom build the envoy and use that custom built envoy.

### How will you implement it

---

**Comment by AmaliMatharaarachchi** [comment]
Closing with https://github.com/wso2/product-microgateway/pull/1514
