### ISSUE TITLE
[Envoy-MG] New configuration model and pass configurations from control plane to data plane

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#1445]
### Describe your problem(s)
Microgateway data plane has following two components

1. Envoy proxy
2. Filter chain

The control plane should be able to configure the both of the components.

### Describe your solution
Envoy proxy configuration can be done via the xds APIs.
Filter chain side configuration should be done using a similar approach used in envoy proxy.

### Tasks
- [x] Implement the filter chain config model #1452 
- [x] Dynamically update filter chain configs from control plane
---

**Comment by AmaliMatharaarachchi** [comment]
Closing with https://github.com/wso2/product-microgateway/pull/1572
