### ISSUE TITLE
[Envoy-MG] Integration test suite for envoy based microgateway

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#1449]
### Describe your problem(s)
The every feature should be added to the gateway should have integtration tests. There should be proper framework in the gateway in order to write integration tests for thier features.
The framework should be able to start the gateway against the given configs and APIs and execute the tests against it.

### Describe your solution
A framework like testng can be used for this. And docker images should be started by the testing framework in order to run the tests.

---

**Comment by AmaliMatharaarachchi** [comment]
Closing with https://github.com/wso2/product-microgateway/pull/1511
