### ISSUE TITLE
Implement Scope Validation for Envoy-mgw

### ISSUE THREAD

**Issue by menakaj** [wso2/product-microgateway#1463]
### Describe your problem(s)
The api scopes should be validated along with the token validation of the envoy-microgateway.

### Describe your solution
- Append the scopes to the metadata of the ext-authz request from the envoy.
- Retrieve the api-metadata and validate the scopes in filter chain.

### How will you implement it

---

**Comment by Rajith90** [comment]
The scope details come in the open API. The adapter passes the scope details to the enforcer and enforcer validate the scopes attached to the resource against the scopes presents in the jwt
