### ISSUE TITLE
Support Production Endpoints and Sandbox Endpoints

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1495]
### Describe your problem(s)
Needs to provide both Production and Sandbox endpoints for a given API resource. This allows the user to test the API functionality by using a sandbox endpoint.

### Describe your solution

The environment type is picked based on the access token. Depending on that value, the proxy should route the request to the production or sandbox endpoints.

### How will you implement it

The environment type is selected after processing the access token. Hence, it is required to set an additional header to the response received from the enforcer (external authz filter) depending on the environment type. [1]

Then the headers_to_metadata http filter needs to be applied to map these header values to some metadata property. The option to remove the additional headers are provided OOTB within the filter. [2]

Finally, the cluster endpoints should be matched based on these metadata values. [3] and [4]

[1] https://www.envoyproxy.io/docs/envoy/v1.16.0/api-v3/service/auth/v3/external_auth.proto.html?highlight=checkresponse#service-auth-v3-okhttpresponse

[2] https://www.envoyproxy.io/docs/envoy/v1.16.0/api-v3/extensions/filters/http/header_to_metadata/v3/header_to_metadata.proto

[3] https://www.envoyproxy.io/docs/envoy/v1.16.0/api-v3/config/endpoint/v3/endpoint_components.proto#envoy-v3-api-msg-config-endpoint-v3-lbendpoint

[4] https://www.envoyproxy.io/docs/envoy/v1.16.0/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster-lbsubsetconfig

---

**Comment by VirajSalaka** [comment]
As per discussion had with @pubudu538 , it is decided to implement the production and sandbox endpoints as two separate clusters. (previously it was two lb subsets within one cluster) This gives additional advantage of keeping more granular configuration between the two types. (for example, this allows users to have HTTP endpoints for sandbox endpoints but HTTPS for the production. 

The cluster for the routes would be mentioned using a predefined header. And this header would be used to assign the cluster to the route using `cluster-header` parameter. From the enforcer (external authz) the corresponding header would be assigned after processing the access token. (as the environment is dependent on access token). In other words, the router will be performing header-based routing.

Still, there is one limitation as the user cannot have two different basePaths for production and sandbox endpoints. Either user needs to avoid having a basePath or use the same basepath for both occasions.

**Comment by VirajSalaka** [comment]
Due to the architecture of envoy, the headers added from the external authentication filter (enforcer) cannot impact the routing configurations even though the route filter is added in the end of the filter chain. 

Hence, we had to use the `ClearRouteCache:     true` configuration within the external authz filter config to remove the cached configurations. Even though this is enabled, the route cache will only be cleared if there is an addition, removal or change of a certain header happens within the enforcer.

To reduce the performance degradation, the following design decisions are taken.

- The header-based routing will only happen if a certain resource has both types: the production and sandbox endpoints. (`cluster-header` parameter is used) Header should be populated within the enforcer and added to the filter response.
- Otherwise the cluster is assigned via `cluster`. In this case, the developer should add the header from the enforcer.

Performance impact should be tested.

**Comment by AmaliMatharaarachchi** [comment]
Closed with https://github.com/wso2/product-microgateway/pull/1525
