### ISSUE TITLE
Backend TLS Communtication (Upstream connections)

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1496]
### Describe your problem(s)

The upstream connections (backend) could be using TLS to make it secure. And those endpoints could be using self-signed certificates or certificates signed by a private CA. Both of these scenarios need to be supported. (as per current state, only public certificates are supported.)

In addition, the proxy should support Mutual TLS based backends as well. 

### Describe your solution

The trusted CA certs file will be the envoy base image's default file. But the user can change it to his own file. In the configuration file, the file path can be mentioned (considering the image's folder structure). And the corresponding trusted CA file needs to be included within the distribution and mount. (docker-compose file or as a k8s secret.) This is not dynamically configurable.

By design, the apictl project only contains API definition at the moment. Within the apictl project, there would be a directory called `Endpoint-Certificates`. If multiple cert files are included here, all these files' content will be merged into a single crt file and applied to the envoy. 

For mutual TLS case, the proxy should present its own certificate if certificate-request comes. For that, there would be one single private key. And it is applied for all transport sockets (there is no harm via providing to all TLS endpoints).  **It may require to have different private keys based on more granular level like virtual host in future. But at the moment, it is decided have single key** 

Secret Discovery Service should be used to provide the secrets. This will reduce the envoy configuration file length. 

### How will you implement it

Refer to the above segment.

---

**Comment by AmaliMatharaarachchi** [comment]
Closed with https://github.com/wso2/product-microgateway/pull/1525
