### ISSUE TITLE
ballerina.cache.LruEvictionPolicy Concurrency issues

### ISSUE THREAD

**Issue by lkokila** [wso2/product-microgateway#1507]
### Description:
Requesting a fix for https://github.com/ballerina-platform/ballerina-standard-library/issues/630

### Affected Product Version:
MGW Toolkit 3.2.0

**Comment by adrienyhuel** [comment]
Hello,

We're using WSO2 Microgateway 3.2.1 in production, and we're facing this issue.

- Is there a way to mitigiate this issue, waiting for the 3.2.2 release ?
- Could we upgrade ballerina version to 1.2.12 in toolkit 3.2.1 and rebuild our APIs ?

Thanks for your answer.

**Comment by praminda** [comment]
If you have WSO2 subscription you should be able to get the fix from via [wum](https://wso2.com/updates/wum). If not you'll have to wait for the 3.2.2.

> Could we upgrade ballerina version to 1.2.12 in toolkit 3.2.1 and rebuild our APIs ?
Yes as a workaround you should be able to upgrade ballerina to 1.2.12 manually and try. @chashikajw can you confirm if old mustache templates work with ballerina 1.2.12?

**Comment by chashikajw** [comment]
@praminda  If we upgrade to the ballerina version to 1.2.12, we need to change the mustache templates according to the https://github.com/wso2/product-microgateway/pull/1530 fix.  Otherwise, it breaks the existing code since the request header limits applying a different way in 1.2.12.

**Comment by adrienyhuel** [comment]
@praminda @chashikajw 
Thanks for the help.
It just happened one night, and didn't reappear yet after restarting microgateway container.
We'll wait for the 3.2.2 release then. Do you have an idea when it will be available ?

**Comment by praminda** [comment]
@adrienyhuel Right now we don't have a specifically set timeline for the next patch release for 3.2.x.
So if the fix become high priority, as a workaround. you can try to upgrade ballerina manually and make the changes to `.mustache` files done in #1530 for the the toolkit to apply the required changes.
