### ISSUE TITLE
[Envoy-Mgw] Need to add the integration tests for the mgw setup

### ISSUE THREAD

**Issue by chashikajw** [wso2/product-microgateway#1509]
### Describe your problem(s)

As $subject needs to add the integration tests for the project to test the integration between project components and overall use cases.

### Describe your solution

- Create a dockerize environment to test the overall setup

- Write test cases to cover all the user cases

### How will you implement it

Use TestNg for writing tests
Use Testcontainer to setup the dockerize environment

**Comment by AmaliMatharaarachchi** [comment]
Duplicate issue #1449. fixed with https://github.com/wso2/product-microgateway/pull/1511
