### ISSUE TITLE
[Envoy-Mgw]   Connecion between Enforcer and Router can't be initiated in ubuntu environment

### ISSUE THREAD

**Issue by chashikajw** [wso2/product-microgateway#1510]
### Description:

As $subject connection between Enforcer and Router can't be initiated in ubuntu since the host.docker.internal address cant be resolved in the ubuntu environment

### Steps to reproduce:

- Follow the quick start guide and deeply an API to the mgw.
- Then when you try to invoke an API you will get the 403 error code.

### Environment details (with versions):
- OS: Ubuntu
- Client:
- Env (Docker/K8s): Docker

---

**Comment by AmaliMatharaarachchi** [comment]
Closing as it is fixed with https://github.com/wso2/product-microgateway/pull/1511
