### ISSUE TITLE
[Envoy-MGW] Integration test cases running order doesn't depend on the testng.xml

### ISSUE THREAD

**Issue by chashikajw** [wso2/product-microgateway#1522]
### Description:

As $subject integration test cases should run in the order which has defined in testng.xml. But in this setup, those test cases not running according to the tesng.xml file

### Steps to reproduce:

1. Run the test module using maven clean install.
2. Define only a few test classes in the testng.xml file.
3. But you can see all the test cases are running and it's not dependent on testng.xml.

### Affected Product Version:

4.0.0-m2

### Environment details (with versions):
- OS: Ubuntu 20.04
- Client:
- Env (Docker/K8s):

---

**Comment by AmaliMatharaarachchi** [comment]
Closed with https://github.com/wso2/product-microgateway/pull/1523
