### ISSUE TITLE
Cannot import API to MGW 4.0.0-m3

### ISSUE THREAD

**Issue by McMlok** [wso2/product-microgateway#1554]
### Description:
I followed the [quick start guide](https://github.com/wso2/product-microgateway/tree/v4.0.0-m3#microgateway-quick-start) for Microgateway 4.0.0-m3 but I can't import petstore API to Microgateway with error provided bellow.

### Steps to reproduce:
run microgateway on Docker Desktop with docker-compose up
import petshop api  - _apictl init petstore --oas https://petstore.swagger.io/v2/swagger.json_
deploy api to mg - _.\apictl.exe mg deploy --host https://localhost:9843 --file petstore  -u admin -p admin -k --verbose_

Log in PowerShell

> Executed ImportExportCLI (apictl) on Thu, 14 Jan 2021 11:34:34 CET
[INFO]: Insecure: true
[INFO]: Creating the project artifact C:\Users\XXXXXX\AppData\Local\Temp\project-artifact991188643.zip
[INFO]: Creating: petstore/
[INFO]: Creating: petstore/Docs/
[INFO]: Creating: petstore/Docs/FileContents/
[INFO]: Creating: petstore/Image/
[INFO]: Creating: petstore/Interceptors/
[INFO]: Creating: petstore/Meta-information/
[INFO]: Creating: petstore/Meta-information/api.yaml
[INFO]: Creating: petstore/Meta-information/swagger.yaml
[INFO]: Creating: petstore/README.md
[INFO]: Creating: petstore/Sequences/
[INFO]: Creating: petstore/Sequences/fault-sequence/
[INFO]: Creating: petstore/Sequences/in-sequence/
[INFO]: Creating: petstore/Sequences/out-sequence/
[INFO]: Creating: petstore/api_params.yaml
[INFO]: Creating: petstore/libs/
Response : [ERROR]:  Post "https://localhost:9843/api/mgw/adapter/0.1/apis": EOF
[INFO]: Deleting C:\Users\XXXXXX\AppData\Local\Temp\project-artifact991188643.zip
[ERROR]: remove C:\Users\XXXXXX\AppData\Local\Temp\project-artifact991188643.zip: The process cannot access the file because it is being used by another process.
apictl: Error adding swagger to microgateway Reason: Post "https://localhost:9843/api/mgw/adapter/0.1/apis": EOF
Exit status 1

Log from Adapter container 
> 2021-01-14 09:43:04 INFO [logger.go:63] - [loggers.UpdateLoggers] [-] Updated loggers
2021-01-14 09:43:04 INFO [bootsrap.go:36] - [microgateway.StartMicroGateway] [-] Starting Microgateway
2021-01-14 09:43:04 INFO [mgw.go:108] - [mgw.Run] [-] Starting adapter ....
2021-01-14 09:43:04 INFO [mgw.go:81] - [mgw.runManagementServer] [-] port: 18000 management server listening
2021/01/14 09:43:04 Serving restapi at https://[::]:9843
2021/01/14 09:53:55 http: TLS handshake error from 172.18.0.1:45858: remote error: tls: illegal parameter
2021/01/14 09:53:55 http: TLS handshake error from 172.18.0.1:45856: remote error: tls: illegal parameter
2021/01/14 09:53:56 http: TLS handshake error from 172.18.0.1:45876: remote error: tls: illegal parameter
2021/01/14 09:53:56 http: TLS handshake error from 172.18.0.1:45878: remote error: tls: illegal parameter
2021/01/14 09:54:01 http: TLS handshake error from 172.18.0.1:45916: remote error: tls: illegal parameter
2021/01/14 09:54:01 http: TLS handshake error from 172.18.0.1:45922: remote error: tls: illegal parameter
2021/01/14 09:54:01 http: TLS handshake error from 172.18.0.1:45928: remote error: tls: illegal parameter
2021/01/14 10:18:07 http: TLS handshake error from 172.18.0.1:55196: remote error: tls: illegal parameter
2021/01/14 10:18:07 http: TLS handshake error from 172.18.0.1:55202: remote error: tls: illegal parameter
2021/01/14 10:18:08 http: TLS handshake error from 172.18.0.1:55222: remote error: tls: illegal parameter
2021/01/14 10:18:08 http: TLS handshake error from 172.18.0.1:55226: remote error: tls: illegal parameter
2021/01/14 10:18:13 http: TLS handshake error from 172.18.0.1:55266: remote error: tls: illegal parameter
2021/01/14 10:18:13 http: TLS handshake error from 172.18.0.1:55272: remote error: tls: illegal parameter
2021/01/14 10:34:34 http: panic serving 172.18.0.1:33302: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 53 [running]:
net/http.(*conn).serve.func1(0xc0000d6fa0)
/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0xdb37c0, 0xc0004c2300)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/wso2/micro-gw/pkg/api.getAPIType(0xc0004b8580, 0x29b, 0x2c0, 0xc0004b8580, 0x29b, 0x2c0, 0x0)
/Users/amali/workspace/mgw/envoy/temp/product-microgateway/adapter/pkg/api/file_read_utils.go:147 +0x240
github.com/wso2/micro-gw/pkg/api.ApplyAPIProject(0xc0001d6000, 0x178f, 0x1e00, 0xc0001d6000, 0x178f)
/Users/amali/workspace/mgw/envoy/temp/product-microgateway/adapter/pkg/api/file_read_utils.go:107 +0xc36
github.com/wso2/micro-gw/pkg/api/restserver.configureAPI.func2(0xc0000d2a00, 0x1088bc0, 0xc0002f6700, 0x0, 0x0, 0xc0003cb950, 0xee4f01, 0xc0003cb320)
/Users/amali/workspace/mgw/envoy/temp/product-microgateway/adapter/pkg/api/restserver/config_restapi.go:87 +0x88
github.com/wso2/micro-gw/pkg/api/restserver/operations/api_individual.PostApisHandlerFunc.Handle(0xf6dd88, 0xc0000d2a00, 0x1088bc0, 0xc0002f6700, 0x0, 0x0, 0xc0003cb950, 0x0, 0xd40400)
/Users/amali/workspace/mgw/envoy/temp/product-microgateway/adapter/pkg/api/restserver/operations/api_individual/post_apis.go:36 +0x51
github.com/wso2/micro-gw/pkg/api/restserver/operations/api_individual.(*PostApis).ServeHTTP(0xc000505c40, 0x10991c0, 0xc0004ea1c0, 0xc0000d2a00)
/Users/amali/workspace/mgw/envoy/temp/product-microgateway/adapter/pkg/api/restserver/operations/api_individual/post_apis.go:87 +0x342
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x10991c0, 0xc0004ea1c0, 0xc0000d2900)
/Users/amali/go/pkg/mod/github.com/go-openapi/runtime@v0.19.22/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc00050a970, 0x10991c0, 0xc0004ea1c0, 0xc0000d2900)
/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x10991c0, 0xc0004ea1c0, 0xc0000d2400)
/Users/amali/go/pkg/mod/github.com/go-openapi/runtime@v0.19.22/middleware/router.go:77 +0x356
net/http.HandlerFunc.ServeHTTP(0xc0003909e0, 0x10991c0, 0xc0004ea1c0, 0xc0000d2400)
/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x10991c0, 0xc0004ea1c0, 0xc0000d2400)
/Users/amali/go/pkg/mod/github.com/go-openapi/runtime@v0.19.22/middleware/redoc.go:72 +0x286
net/http.HandlerFunc.ServeHTTP(0xc0004ffc80, 0x10991c0, 0xc0004ea1c0, 0xc0000d2400)
/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x10991c0, 0xc0004ea1c0, 0xc0000d2400)
/Users/amali/go/pkg/mod/github.com/go-openapi/runtime@v0.19.22/middleware/spec.go:46 +0x188
net/http.HandlerFunc.ServeHTTP(0xc0004ffcc0, 0x10991c0, 0xc0004ea1c0, 0xc0000d2400)
/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc0004ea2a0, 0x10991c0, 0xc0004ea1c0, 0xc0000d2400)
/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0000d6fa0, 0x109be00, 0xc00036e2c0)
/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
/usr/local/go/src/net/http/server.go:2927 +0x38e

### Affected Product Version:
Microgateway 4.0.0.-m3

### Environment details (with versions):
- OS: Windows 10 1909
- Client: apictl 4.0.0-m3
- Env (Docker/K8s): DockerDesktop 3.0.0

**Comment by AmaliMatharaarachchi** [comment]
Hi @McMlok, This issue might be caused due to the folder structure change introduce in apictl m3 release. Make sure to delete .wso2apictl and .wso2apictl.local in your home directory (for example /Users/username/.wso2apictl) before initiating the project using the apictl.

**Comment by McMlok** [comment]
Thank you, after I removed directories it started working.
