### ISSUE TITLE
Retrieving APIM Events to Control Plane in microgateway

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-microgateway#1562]
### Describe your problem(s)
Control plane in  microgateway needs to be retrieved events(Notification, KeyManager, Token Revocation) coming from APIM

### Describe your solution
Consumers for Notification, KeyManager, Token Revocation topics are needed to be implement at control plane and store the data

### How will you implement it
There is a go library [1] which can be used to implement the logic at control plane

[1] https://github.com/streadway/amqp

---

**Comment by AmaliMatharaarachchi** [comment]
closed with https://github.com/wso2/product-microgateway/pull/1559
