### ISSUE TITLE
Fetch APIs from Control Plane

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-microgateway#1564]
### Describe your problem(s)

During the Adapter start up, connect to the control plane and fetch the APIs.
Then the fetched APIs should be fed into enforcer and router.

Later this can be extended to fetch the updated APIs from the control plane.

A similar flow for this can be seen in the diagram below.

![Untitled Diagram](https://user-images.githubusercontent.com/8377610/105821268-aa55e100-5fe0-11eb-89b9-9a0c85597ccc.png)

### How will you implement it

---

**Comment by AmaliMatharaarachchi** [comment]
Closing with https://github.com/wso2/product-microgateway/pull/1572
