### ISSUE TITLE
Provide CORS Configurations Globally

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1566]
### Describe your problem(s)
The user should have the capability to provide the CORS Configurations globally.

### Describe your solution
The config.toml should have a segment for the CORS configuration.

### How will you implement it

---

**Comment by VirajSalaka** [comment]
Closing the issue as having API level cors Configurations is enough. Global Configuration would not be required.

**Comment by dinusha92** [comment]
Closing the issues since this is fixed with above PRs.
