### ISSUE TITLE
Retrieve API information from adapter to enforcer

### ISSUE THREAD

**Issue by praminda** [wso2/product-microgateway#1568]
### Describe your problem(s)

API details of newly added/updated/deleted APIs are fetch from the control plane to the adapter. These information should be pushed to enforcer inorder to validate requests coming from router.
### Describe your solution

Implement a xDS similar to the configDS
### How will you implement it

---

**Comment by AmaliMatharaarachchi** [comment]
Closing with https://github.com/wso2/product-microgateway/pull/1572
