### ISSUE TITLE
Support Multiple Enforcers Per Single Router

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1624]
### Describe your problem(s)
There could be occasions where a single enforcer cannot handle the load coming from a single router. It would be better if we can load balance the load from router to enforcer by deploying multiple enforcers.

At the moment, the enforcer is assigned within the enforcer dockerfile as a static envoy.yaml. 

### Describe your solution

- Introduce an executable that is capable of generating the envoy.yaml depending on the enforcer endpoints mentioned. 

- Add the enforcer cluster using xds.

### How will you implement it

---

**Comment by pubudu538** [comment]
Current deployment pattern is side car. So this pattern is not required.
