### ISSUE TITLE
Unclassified Authentication Failure for JWT validation failure 

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/product-microgateway#1653]
### Description:
The following response is received when JWT validation fails with a token.

`{"error_message":"Unclassified Authentication Failure","code":"900900","error_description":"Unclassified Authentication Failure"}`

This response should be changed to invalid credentials response.

**Comment by Rajith90** [comment]
This is happening for invalid jwt token, i.e token with invalid signature @HeshanSudarshana

**Comment by Rajith90** [comment]
This seems to be fixed with alpha2. When invoke token with tampered signature it gives the error code 900901, Invalid Credentials message
