### ISSUE TITLE
Support external key manager configuration

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/product-microgateway#1663]
### Describe your problem(s)
Instead of adding all the token issuers from config.toml file, it should be able to extract the key manager configurations of APIM and used for token validation. 

### Describe your solution
Key manager configurations should be extracted from APIM when eventhub is enabled from config.toml. A key manager discovery service should be implemented for communication between adapter and enforcer.

**Comment by dinusha92** [comment]
Closing this since #1666 fixed this.
