### ISSUE TITLE
Generate a test JWT

### ISSUE THREAD

**Issue by npamudika** [wso2/product-microgateway#1671]
### Describe your problem(s)
There should be a way to generate a test JWT for development.

### Describe your solution
Implement JWT generation support in MGW and expose it as a http service.

**Comment by Rajith90** [comment]
Fixed with: https://github.com/wso2/product-microgateway/pull/1675

**Comment by dinusha92** [comment]
Reopenning the issue to fix the encoding issue.

**Comment by dinusha92** [comment]
Ignore the above last comment.
