### ISSUE TITLE
Support Endpoint Prototype APIs 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-microgateway#1681]
### Describe your problem(s)
Current envoy support cannot deploy Endpoint prototype APIs

### Describe your solution
Changes needs to be added prior to lifeCycleStatus=Prototyped

### How will you implement it
Endpoints needs to be extracted from api.json file as it doesn't perform at swagger and add it to existing MGWSwagger model

---

**Comment by dinusha92** [comment]
Closing the issue since PR #1682 has fixed this.
