### ISSUE TITLE
[envoy-gw] A common HTTP Client for adapter to connect with control plane.

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-microgateway#1690]
### Describe your problem(s)

Currently Adapter is connecting with control plane for a lot of tasks. As of now, for each of these invocations we can see redundant code. Hence we need to create a common method to avoid the redundent code and make the code clean.

### How will you implement it

---

**Comment by pubudu538** [comment]
THis refactoring has already happend. Hence closing.
