### ISSUE TITLE
[envoy-gw] Web socket metadata grpc service

### ISSUE THREAD

**Issue by NomadXD** [wso2/product-microgateway#1703]
### Describe your problem(s)
gRPC service for processing web socket frame related metadata for web socket throttling and analytics.  

### Describe your solution
Publish web socket metadata from a custom c++ filter to enforcer gRPC service

### How will you implement it
Implement a custom http filter in envoy, gRPC service in enforcer

---
#### Related Issues:
Sub task of #1540

**Comment by Rajith90** [comment]
Fixed with : https://github.com/wso2/product-microgateway/pull/1943
