### ISSUE TITLE
Subscriptions validation is not working properly

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-microgateway#1706]
### Description:
When validate token, subscription validation is not working as expected.

### Steps to reproduce:
1. Invoke API with subscription

### Affected Product Version:
product-microgateway-4.0.0-M7

### Environment details (with versions):
- OS: Mac
- Client:
- Env (Docker/K8s):

---

**Comment by dinusha92** [comment]
Fixed with the above PR.
