### ISSUE TITLE
Use test tags in testng.xml to create collections of tests that can reuse the same mgw instance

### ISSUE THREAD

**Issue by SuKSW** [wso2/product-microgateway#1709]
### Describe your problem and solution
Although we can extend the existing classes in order to use the same mgw instance, there can be tests that cannot be extended in such a way because the tests are not similar. One example can be tests that will be written with apictl. Although there are mgw instances created that can be reused for these test, since the tests currently using them are different from apictl tests they cannot be extended due to technical and logical reasons. And as more test cases gets added, having common mgw instances that can be reused will be useful.

Even if we have such common mgw instances, only extending them by considering them as 'bestTestCase' would not support our requirement, which is to only start the mgw once to be used by all relevant test cases. This can be solves by using test tags in testng.xml together with the beforeTest annotation.

More importantly if a mgw instance cannot be reused for a test case, it will be quickly visible and therefore we can check whether the behavior is expected.

### How will you implement it

---

**Comment by dinusha92** [comment]
Closing as the above PR fixed this.
