### ISSUE TITLE
APIM docker-compose intermittant issue

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#1714]
### Description:
The following error is occurred when executing the docker-compose.yaml inside the docker-with-apim folder.
This is due to compose file version 3.7 requires the depends on as array. And  condition also not supported under the depends on.
This works in some machines(MAC OS), but fails in some other machines

```
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.adapter.depends_on contains an invalid type, it should be an array
```

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by dinusha92** [comment]
Closing since this is fixed with above PR.
