### ISSUE TITLE
Target Connectivity related errors should follow the APIM error codes.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1717]
### Describe your problem(s)
When an error occurs due to connectivity issue, the microgateway should be able to generate a response with the necessary APIM error codes.

### Describe your solution
Response mapper feature can be used here. Filtering needs to be done using response flags.

### How will you implement it

---

**Comment by Rajith90** [comment]
https://github.com/wso2/product-microgateway/issues/1831 is a subset of this issue

**Comment by Rajith90** [comment]
Fixed with: https://github.com/wso2/product-microgateway/pull/1935
