### ISSUE TITLE
JMS connection parameter url password can not be override using envs

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#1732]
### Description:
The following config section will not replace the password using the configured environment variable

```
controlPlane.eventHub.jmsConnectionParameters]
    eventListeningEndpoints = ["amqp://admin:$env{cp_admin_pwd}@apim:5672?retries='5'&connectdelay='30000'"]
```

### Steps to reproduce:
1. Change the `eventListeningEndpoints` url as above
2. Set the `cp_admin_pwd` environment variable to admin password of API manager
3. Enable event hub
4. There will be errors in connecting to event hub

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by dinusha92** [comment]
Closing since this is fixed with above PR.
