### ISSUE TITLE
Use API Manager as the Control Plane for Integration tests

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/product-microgateway#1755]
### Describe your problem(s)

- Use API Manager as the Control Plane for Integration tests
- Add utility methods for Mgw test cases that use the APIM as the backend server

### How will you implement it

- Use docker with apim docker-compose.yaml file
- Write utility methods to interact with APIM
---

**Comment by dinusha92** [comment]
Closing as the above PR fixed this.
