### ISSUE TITLE
False health status for Adapter when it is unable to connect to control plane

### ISSUE THREAD

**Issue by mpmunasinghe** [wso2/product-microgateway#1762]
### Describe your problem(s)
In case of a failure at the control plane the adapter retries to connect to the control plane. However, once the retry interval expires adapter abandons the retry connection. The adapter still appears healthy despite that it is not connected with the control plane therefore false health status is displayed in the k8s environment. 

When considering the health check improvements for https://github.com/wso2/product-microgateway/issues/1749 we should look at this aspect for adapater health checks. 

### How will you implement it

---
#### Suggested Labels:
Choreo, envoy-gw

**Comment by pubudu538** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/1899
