### ISSUE TITLE
Support Basic Auth Endpoint security

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-microgateway#1779]
### Describe your problem(s)
Currently any of endpoint security mechanism is not supported in mgw. Basic auth support should be included

### Describe your solution
Adding security details to API object and parse to enforcer in order to add basic auth credentials at runtime

### How will you implement it
JWTAuthenticator flow will be added new header appending basic auth credentials checking endpoint keytype

---

**Comment by Rajith90** [comment]
Fixed with : https://github.com/wso2/product-microgateway/pull/1785
