### ISSUE TITLE
Introduce two ports, for http and https communication.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1783]
### Describe your problem(s)
Following the API Manager's approach, and Microgateway 3.2.0; two listeners need to accept the traffic. At the moment it is one port available and enable/disable tls is done based on the configuration value.

### Describe your solution
Two listeners will be created with same rds config name. 

### How will you implement it

---

**Comment by Rajith90** [comment]
Fixed with: https://github.com/wso2/product-microgateway/pull/1753
