### ISSUE TITLE
Kubernetes artifacts for Router and Enforcer in Sidecar mode

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-microgateway#1794]
### Describe your problem(s)

Currently k8s artifacts provide seperate pods for router and enforcer.
To enhance the network latency etc, k8s artifacts should be created to run enforcer and router in the same pod.

### How will you implement it

---

**Comment by Rajith90** [comment]
Fixed with : https://github.com/wso2/product-microgateway/pull/1795
