### ISSUE TITLE
Add capability to envoy-mgw API invocation with Custom Auth Header 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-microgateway#1807]
### Describe your problem(s)
Mgw needs to support api invocation with custom header includes in swagger definition

### Describe your solution
Auth header could be extracted from swagger/api json and pass to enforcer to store api level custom auth header. During api invocation, JWTAuthenticator needs to check whether the custom header presents in the API request.

### How will you implement it

---

**Comment by Rajith90** [comment]
Fixed with: https://github.com/wso2/product-microgateway/pull/1793
