### ISSUE TITLE
If jwt claim based throttling is enabled and a certain resource's auth is disabled, results in NPE

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1839]
### Description:
Null Pointer exception happens if the $subject is met.

### Steps to reproduce:
Jwt Claim Based throttling is applied.
(Then the advanced policy is changed to a generic count-based policy again.)
One resource's authentication is disabled.
Try to invoke the resource.

### Affected Product Version:
m10-SNAPSHOT

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s): Docker with APIM

---

**Comment by praminda** [comment]
@VirajSalaka couldn't reproduce this with the provided steps.
