### ISSUE TITLE
Prototyped APIs cannot be invoked

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#1955]
### Description:

state changes requires redeploying the API(create a new revision). simply only clicking prototype button does not work.

### Steps to reproduce:
(only tried in tenant user.)
create an API with a mocky.io endpoint as prototype backend. and publish as a prototype.
try to invoke the API.
API should be able to invoke w/o a token, but it shows the following error.

```
{"error_message":"Invalid Credentials","code":"900901","error_description":"Make sure you have provided the correct security credentials"}
```

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by HiranyaKavishani** [comment]
Should be issue in the value comes for lifecycle state. We have removed authFilter for prototype APIs [1]

[1] https://github.com/wso2/product-microgateway/blob/main/enforcer/src/main/java/org/wso2/choreo/connect/enforcer/api/RestAPI.java#L174

**Comment by AmaliMatharaarachchi** [comment]
API should be redeployed in order to get the state change to gateway side. then it will work as expected.

**Comment by VirajSalaka** [comment]
following log appears in the adapter logs.
```
adapter_1   | 2021-11-19 03:57:18 INFO [apis_impl.go:240] - [api.ApplyAPIProjectFromAPIM] [-] API myprototypeAPI:v1 with UUID "e5900709-c025-43da-8b66-25a5e2e00031" already deployed to vhost: localhost
adapter_1   | 2021-11-19 03:57:18 ERRO [mgw_swagger.go:440] - [model.(*MgwSwagger).Validate] [-] No Endpoints are provided for the API myprototypeAPI:v1
adapter_1   | 2021-11-19 03:57:18 ERRO [server.go:312] - [xds.UpdateAPI] [-] Validation failed for the API myprototypeAPI:v1 of Organization carbon.super
adapter_1   | 2021-11-19 03:57:18 ERRO [apis_fetcher.go:105] - [synchronizer.PushAPIProjects] [-] Error occurred while applying project myprototypeAPI:v1 with UUID "e5900709-c025-43da-8b66-25a5e2e00031"
```
