### ISSUE TITLE
Analytics resource path details are not visible for error requests

### ISSUE THREAD

**Issue by praminda** [wso2/product-microgateway#1964]
### Description:

When analytics is enabled and API invocations are failed due to upstream connectivity issues, those stats are visible in the analytics dashboard, however the request resource path and method is not populated.
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/2655553/115845642-ad753780-a43e-11eb-9029-a60918560ae6.png">

### Steps to reproduce:
- Enable analytics
- Create an API with invalid upstream endpoint
- Invoke an resource of that API
- Observe the analytics dashboard for `API Resource Usage Summary`
### Affected Product Version:

0.9.0-beta
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

**Comment by praminda** [comment]
Seems data is being published but analytics portal is not showing the stats. This should be moved to analytics issue tracker

**Comment by praminda** [comment]
@ruks @fazlan-nazeem can you move this to the relevant repo?

**Comment by ruks** [comment]
@praminda this is not possible to move. I Will link this issue.

**Comment by praminda** [comment]
Thanks @ruks.
I'll close the issue from mgw.
