### ISSUE TITLE
Issue with certificate api.central.ballerina.io/52.191.85.177:443

### ISSUE THREAD

**Issue by dishelt** [wso2/product-microgateway#1980]
Hey there!. Im having some issues with Microgateway 3.1.0

### Description:

When I am building microgateway, Im getting: connection to the remote repository host failed: SSL connection failed:unable to find valid certification path to requested target api.central.ballerina.io/52.191.85.177:443. Do you known how I can fix it?
### Steps to reproduce:
Build a microgatway
### Environment details (with versions):
- OS: Ubuntu
- Client:
- Env (Docker/K8s):
- Java; OpenJDK 8

---
#### Related Issues:
Complete trace:
Compiling source
	wso2/c3-portal:3.1.0
error: 	connection to the remote repository host failed: SSL connection failed:unable to find valid certification path to requested target api.central.ballerina.io/52.191.85.177:443
error: wso2/gateway:3.1.0::/src/gateway/services/throttle_event_listener.bal:17:1: cannot resolve module 'wso2/jms'
error: 	connection to the remote repository host failed: SSL connection failed:unable to find valid certification path to requested target api.central.ballerina.io/52.191.85.177:443
error: wso2/gateway:3.1.0::/src/gateway/services/token_revocation_event_listener.bal:17:1: cannot resolve module 'wso2/jms'
error: 	connection to the remote repository host failed: SSL connection failed:unable to find valid certification path to requested target api.central.ballerina.io/52.191.85.177:443
error: wso2/gateway:3.1.0::/src/gateway/utils/throttle_util.bal:18:1: cannot resolve module 'wso2/jms'
error: wso2/gateway:3.1.0::/src/gateway/services/throttle_event_listener.bal:27:33: undefined module 'jms'
error: wso2/gateway:3.1.0::/src/gateway/services/throttle_event_listener.bal:27:33: unknown type 'Message'
error: wso2/gateway:3.1.0::/src/gateway/services/token_revocation_event_listener.bal:31:33: undefined module 'jms'
error: wso2/gateway:3.1.0::/src/gateway/services/token_revocation_event_listener.bal:31:33: unknown type 'Message'
error: wso2/gateway:3.1.0::/src/gateway/services/throttle_event_listener.bal:68:59: undefined module 'jms'
error: wso2/gateway:3.1.0::/src/gateway/services/throttle_event_listener.bal:68:59: unknown type 'MessageConsumer'
error: wso2/gateway:3.1.0::/src/gateway/services/token_revocation_event_listener.bal:58:74: undefined module 'jms'
error: wso2/gateway:3.1.0::/src/gateway/services/token_revocation_event_listener.bal:77:13: unknown type 'Destination'
error: wso2/gateway:3.1.0::/src/gateway/services/token_revocation_event_listener.bal:77:42: invalid remote function invocation, expected an client object
error: wso2/gateway:3.1.0::/src/gateway/services/token_revocation_event_listener.bal:78:13: undefined module 'jms'
error: wso2/gateway:3.1.0::/src/gateway/services/token_revocation_event_listener.bal:78:13: unknown type 'MessageConsumer'
error: wso2/gateway:3.1.0::/src/gateway/services/token_revocation_event_listener.bal:78:67: invalid remote function invocation, expected an client object
error: wso2/gateway:3.1.0::/src/gateway/services/token_revocation_event_listener.bal:108:9: undefined module 'jms'
error: wso2/gateway:3.1.0::/src/gateway/services/token_revocation_event_listener.bal:108:9: unknown type 'MessageConsumer'
error: wso2/gateway:3.1.0::/src/gateway/services/token_revocation_event_listener.bal:109:47: undefined module 'jms'
error: wso2/gateway:3.1.0::/src/gateway/services/token_revocation_event_listener.bal:109:47: unknown type 'MessageConsumer'

Creating balos
	target/balo/c3-portal-2019r3-java8-3.1.0.balo
ballerina: Oh no, something really went wrong. Bad. Sad.

ballerina: Oh no, something really went wrong. Bad. Sad.

Hope you can help me. Regards!!!

**Comment by AmaliMatharaarachchi** [comment]
Hi @dishelt, this error happens during the build, toolkit tries to download the balo dependencies from the ballerina central.  
When you build a project for the first time, a directory named .ballerina will be created in the user home directory. The downloading of the JMS module from remote Ballerina central happens for the very first project build. After that this folder will be used without downloading the JMS module again.
So if you do not have an internet connection where you are building the project, you may encounter this error.
Therefore, Replacing the ./ballerina folder with a pre-downloaded JMS module manually will work for this scenario. Replace the <user_home>/.ballerina folder with a pre-downloaded .ballerina folder.

**Comment by dishelt** [comment]
Thank you for your answer @AmaliMatharaarachchi . It worked like a charm. 

However, for this scenario, I have internet connection and I am getting this error. I did not have this problem before. It looks a certificate problem (invalid). Just to tell you.

Again, Thank you. Regards!!

**Comment by AmaliMatharaarachchi** [comment]
That's great. We'll close the issue as per the above comment.
