### ISSUE TITLE
Refactoring adapter packages for common usage.

### ISSUE THREAD

**Issue by ShalkiWenushika** [wso2/product-microgateway#2040]
### Describe your problem(s)
A common package is needed for the global adapter to reuse the adapter components which are already available in the envoy microgateway.

### Describe your solution
Refactor the already available golang implementation for the adapter such that the components could be reused.

### How will you implement it

---

**Comment by renuka-fernando** [comment]
This is fixed with https://github.com/wso2/product-microgateway/pull/2046
