### ISSUE TITLE
Cannot build the project with URI templates including Underscores

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-microgateway#2043]
### Description:
Cannot build the project with URI templates including Underscores in the API definition file.

### Steps to reproduce:

- Create a Microgateway project.
- Add a sample API definition file with a URI template as below.

```
paths:
  /test/{TEST_ID}:
    post:
      parameters:
        - name: TEST_ID
          in: path
          description: Test variable
          required: true
          type: string
      responses:
        "200":
          description: OK
      security:
        - default: []
      x-wso2-application-security:
        security-types:
          - oauth2
```

- Try to build the project. When compiling the generated ballerina source, that will fail with error as below image.

![Screenshot from 2021-05-31 14-42-30](https://user-images.githubusercontent.com/18566908/120170385-87516d00-c21e-11eb-9671-d67bf4275991.png)

### Affected Product Version:
Microgateway Toolkit - 3.2.0 latest Updated Level

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/2075
