### ISSUE TITLE
Support API UUID as the key of the internal maps

### ISSUE THREAD

**Issue by menakaj** [wso2/product-microgateway#2049]
### Describe your problem(s)
Currently in choreo-connect adapter, vhost:apiname:apiversion are used as the map key. But, with the introduction of ability to change the api name in api manager, this key cannot be used in future.

### Describe your solution

Use the api uuid as the map key. The uuid is included in the api manager events. This can be propagated to the relevant methods in `xds/server.go` (update api, delete api) and use as the key.

In api ctl scenario however, we do not have the uuid. Therefore, generate a hash or a uuid from the api name and version when importing/ deleting the api. 

In both these scenarios, the key would be like: `vhost:api-uuid`

A reverse map should also needs to keep the api name and version against the uuid, to use in the api ctl scenario.

### How will you implement it

---

**Comment by renuka-fernando** [comment]
This is fixed
