### ISSUE TITLE
Support organizations and tenants

### ISSUE THREAD

**Issue by menakaj** [wso2/product-microgateway#2050]
### Describe your problem(s)
In API-M, the multi tenancy will be merged with organization concept, where resources (apis/ apps) in a tenant are further isolated in to orgnizations.

In the current implementation of Choreo-Connect, it's only supported to configure a single tenant. This cannot facilitate the above requirement as it is. 
 
### Describe your solution

In APIM, the event will contain a field which tells whether the event is belong to an org or a tenant. Based on this information, in CC adapter, the logic should be improved to check this condition.

### How will you implement it

---

**Comment by renuka-fernando** [comment]
fixed with https://github.com/wso2/product-microgateway/issues/2041
