### ISSUE TITLE
LogConfig and MGW_HOME read operations are repeated.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#2077]
### Describe your problem(s)

As per current implementation, the log_config.toml read operation and GetMGWHome() operation functionality has been repeated twice despite they share the same functionality.

One implementation resides in pkg/config directory while the other implementation can be seen in config directory.

### Describe your solution

Following facts should be taken into account while solving the issue.

- The log_config.toml parsing operation should reside within the pkg directory as the loggers are initialized within both pkg and internal directory. 
- The same implementation should be reused within global adapter to read and parse logs.
The log_config.toml 's file name and directory may change when it is reused within a global adapter (not necessarily located within `conf/log_config.toml` relative path)

Based on these, 

- a new environmental variable is introduced `LOG_CONFIG_PATH`. And this has the top priority for resolving log_config.toml's file path.
- if it is not available, relative path based approach (current implementation) will be used. (Therefore this preserves backward compatibility)

### How will you implement it

---

**Comment by renuka-fernando** [comment]
fixed with https://github.com/wso2/product-microgateway/pull/2100
