### ISSUE TITLE
Internal key caching issue

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#2081]
### Steps to reproduce:
use a valid internal key and invoke a created api
then tamper with the key (delete some characters) and use it to invoke the same api. -> it works (but this should not work)

### Affected Product Version:

beta

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by HiranyaKavishani** [comment]
We might need to add the fix [1] for internal key implementation.

[1] https://github.com/wso2/product-microgateway/pull/1852/files
