### ISSUE TITLE
W10 - APIM 2.5.0 MicroGW OOTB Pizzashack 

### ISSUE THREAD

**Issue by robbla** [wso2/product-microgateway#210]
an OOTB APIM 2.5.0 with a deployed Pizzashack API fails  to migrate to microgw on Windows 10 

PS C:\Users\rob\Desktop\api250GW> micro-gw setup pizzashack-project -a PizzaShackAPI -v 1.0.0 -f
Enter Password for admin:

micro-gw: Internal error occurred while executing command.
PS C:\Users\rob\Desktop\api250GW>
[audit.log](https://github.com/wso2/product-microgateway/files/2249530/audit.log)
[http_access_2018-08-01.log](https://github.com/wso2/product-microgateway/files/2249531/http_access_2018-08-01.log)
[wso2-apigw-errors.log](https://github.com/wso2/product-microgateway/files/2249532/wso2-apigw-errors.log)
[wso2-apigw-service.log](https://github.com/wso2/product-microgateway/files/2249533/wso2-apigw-service.log)
[wso2carbon.log](https://github.com/wso2/product-microgateway/files/2249534/wso2carbon.log)

Included all logs that were  created around that time

**Comment by dunithd** [comment]
Noticed the same error with APIM 2.6.0 on Windows 10 with OOTB Pizzashack sample.

**Comment by praminda** [comment]
@dunithd Did you experience same errors in API Manager log files?

**Comment by praminda** [comment]
@robbla @dunithd 
We tried to reproduce this in the latest packs but couldn't reproduce. With the recent restructuring change other fixes we've done we hope this issue should be resolved now. Please reopen the ticket if you still get the issue in latest builds.

**Comment by krishnilak** [comment]
@praminda I am also getting this error when using pizzaShack example.
I am using macOS high Sierra 10.13.6
APIM 2.6.0
APIM micro gw 2.6.0
[microgw.log](https://github.com/wso2/product-microgateway/files/3180988/microgw.log)

**Comment by praminda** [comment]
@krishnilak It seems you've wso2 subscription for APIM 2.6.0 and has installed updates for it. But you've not updated the micro-gw.
