### ISSUE TITLE
RE2 program size of 106 > max program size of 100 set for the error level threshold

### ISSUE THREAD

**Issue by bmonteiro** [wso2/product-microgateway#2105]
Hello guys, 

It looks like when using more complex regex in the API path the MG is complaining with the below error:
 
![image](https://user-images.githubusercontent.com/908425/123750621-18b40d80-d8b7-11eb-81ba-f8199cd1fa6b.png)

FYI @praminda

**Comment by praminda** [comment]
ref: https://github.com/envoyproxy/envoy/issues/9174

**Comment by Rajith90** [comment]
This is fixed in the main branch. This is the issue: https://github.com/wso2/product-microgateway/issues/2067

**Comment by bmonteiro** [comment]
Thx! @Rajith90, That code was already shipped in a docker image available in docker hub? If yes, what tag please

**Comment by bmonteiro** [comment]
Tested via building main branch and push to my docker hub account:

docker pull bmonteiro/choreo-connect-enforcer:0.9.1-SNAPSHOT
docker pull bmonteiro/choreo-connect-adapter:0.9.1-SNAPSHOT
docker pull bmonteiro/choreo-connect-router:0.9.1-SNAPSHOT

We can close this issue thx!
