### ISSUE TITLE
Connecting to Global Adapter and fetch APIs via XDS

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#2106]
### Describe your problem(s)
For the choreo deployment, the global adapter will be the component that provides information on which APIs to pull. For that it is required to implement XDS client within adapter component.

### How will you implement it

---

**Comment by VirajSalaka** [comment]
Related to https://github.com/wso2-enterprise/choreo/issues/4332

**Comment by renuka-fernando** [comment]
this is fixed
