### ISSUE TITLE
Issue in exporting PizzaShackAPI sample

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/product-microgateway#211]
**Description:**
Refer https://github.com/ballerina-platform/ballerina-lang/issues/9774 for further details.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praminda** [comment]
We've restructured the CLI with #325. This should be fixed now.
