### ISSUE TITLE
Getting OutOfMemoryException after exceeding the token cache + revoked tokens are in the token cache

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-microgateway#2169]
### Description:
**Issue 1**
Getting an OOM when performing a load test to generate access tokens and invoke the API.
**Issue 2**
When receiving the token revocation notification event through the JMS message listener, the revoked token is not removing from the gateway token cache.

### Steps to reproduce:
**Issue 1**
- Create an MGW project and generate a runtime artifact.
- Open the **micro-gw.conf** file inside the <MGW_RUNTIME_HOME>/conf directory and add the below token cache configurations.

```
[caching]
  tokenCacheExpiryTime = 4800
  tokenCacheCapacity = 50
  tokenCacheEvictionFactor = 0.5
```

- Deploy the generated runtime artifact by using the Microgateway Runtime.
- Perform a load test with the below API invocations each time. (200 requests per second)
1. Token API invocation to generate a large JWT access token. (application has 30 API subscriptions to generate a large JWT)
2. API invocation by parsing the generated access token.

**Issue 2**

- According to the code, the token is removing from the gateway token cache if the token is expired.

### Affected Product Version:
3.2.0

**Comment by pubudu538** [comment]
Fixed!
