### ISSUE TITLE
[Apple M1][ARM] Docker image compatibility issues in ARM versions

### ISSUE THREAD

**Issue by vlgunarathne** [wso2/product-microgateway#2170]
### Describe your problem(s)
I recently tried to build this repository in an Apple M1 mac and faced a couple of failures.

1. Enforcer component build fails with the following error
```
[ERROR] DOCKER> Unable to pull 'adoptopenjdk/openjdk11:jre-11.0.11_9-alpine' : no matching manifest for linux/arm64/v8 in the manifest list entries  [no matching manifest for linux/arm64/v8 in the manifest list entries ]
```
The other two components can be built. However,

2. The docker images built on M1 machines are based on `linux/arm64/v8` architecture and hence they fail when we try to run them on the AKS clusters since those nodes are running on a platform with amd64 architecture.

### Describe your solution
Need to add the following platform specification configuration when building the docker images on M1 ARM machines

```
FROM --platform=linux/x86_64 alpine:3.13.5
...
```

This will force to pull the amd64 versions of the base images and these images will work on both the AKS and also will work on M1 machines via Rosetta2 emulation.

### How will you implement it

---

**Comment by pubudu538** [comment]
Duplicate - https://github.com/wso2/product-microgateway/issues/2412
