### ISSUE TITLE
Unwanted error logs when configuring multiple JWT configs

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-microgateway#2191]
### Description:
When configuring multiple JWT configurations in the micro-gw.conf file and invoking the API, the token will validate sequentially and printing error logs. However, the request getting successful.

### Steps to reproduce:

- Add multiple JWT configurations to the **micro-gw.conf** file as below.

```
[[jwtTokenConfig]]
  issuer = "https://localhost:9443/oauth2/token"
  certificateAlias = "wso2carbonjwt1"
  validateSubscription = false
  consumerKeyClaim = "aud"
[[jwtTokenConfig]]
  issuer = "https://localhost:9444/oauth2/token"
  certificateAlias = "wso2carbonjwt2"
  validateSubscription = false
  consumerKeyClaim = "aud"
```

- Generate an access token which includes the issuer https://localhost:9444/oauth2/token
- Invoke the API and the request getting successful.
- However, in the **microgateway.log** file, able to see error logs related to JWT validation by using the 1st JWT configs.

### Affected Product Version:
3.2.0

**Comment by pubudu538** [comment]
Fixed
