### ISSUE TITLE
Microgateway Runtime goes Out of Memory after enabling observability

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-microgateway#2193]
### Description:
Microgateway Runtime goes Out of Memory after enabling Prometheus observability

### Steps to reproduce:

- Create an MGW project with a path parameterized API resource.
- Open the **micro-gw.conf** file inside the <MGW_RUNTIME_HOME>/conf directory and enable Prometheus observability.

```
[b7a.observability.metrics]
# Flag to enable Metrics
  enabled = true
  reporter = "prometheus"
[b7a.observability.metrics.prometheus]
  port=9797
  hostname= "prometheus.platform-system"
  jmx_port = 8080
  secure_port = 9000 
```

- Deploy the MGW runtime artifact and perform a load test (300TPS)

### Affected Product Version:
3.2.0

**Comment by pubudu538** [comment]
Where is the public branch fix for this issue?

**Comment by chashikajw** [comment]
> Where is the public branch fix for this issue?

Fixed in here https://github.com/wso2/product-microgateway/pull/2207
