### ISSUE TITLE
Cannot deploy API's from Swagger definitions which has malformed URL under server objects

### ISSUE THREAD

**Issue by JanakaSandaruwan** [wso2/product-microgateway#2226]
### Description:

Cannot deploy API's from swagger definitions when malformed URL is found under server object and correct ` x-wso2-production-endpoint`.
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by renuka-fernando** [comment]
fixed with https://github.com/wso2/product-microgateway/pull/2225
