### ISSUE TITLE
MGW analytics Label field is hardcoded

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/product-microgateway#223]
**Description:**

Currently, we publish a field called "label" to the analytics server which is hardcoded to "micro". We need a way to retrieve the label from the micorgateway instance.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Rajith90** [comment]
Since label is not always associated with API, and in the future with the developer first approach (swagger), we want be having APIM connection at all to the micro gw
