### ISSUE TITLE
Add Open Tracing Support

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-microgateway#2234]
### Describe your problem(s)
In case of an hight latency reported in gateway we should have some mechanism to narrow down which part is causing that delay, for ex: jwt verification, scope validation , subscription validation and etc.

This can be achieved to some extend by bringing the open tracing support.

### How will you implement it

Implement distributed tracing support for,
- jaeger
- zipkin
- app insights

**Comment by pubudu538** [comment]
Fixes https://github.com/wso2/product-microgateway/pull/2212

**Comment by praminda** [comment]
Tracing is still not complete. Need to add jaeger and zipkin support
