### ISSUE TITLE
Unexpected responses via apictl when both rest api and control plane are enabled

### ISSUE THREAD

**Issue by suksw** [wso2/product-microgateway#2244]
### Description:
When both rest api and control plane are enabled in the config.toml, 
1. Deploy API produces `Successfully deployed API to microgateway.` while not being deployed. The `get` command lists all other APIs that were deployed correctly.
2. Undeploy API produces `apictl: Error undeploying API Reason: the API does not exist` for existing APIs and this error is printed in the adapter as well.

### Steps to reproduce:
1. Set the following in the config.toml
    ```
   [adapter.server]
        enabled = true
      [controlPlane]
        enabled = true
    ```

2. Try to deploy an API that would not get deployed (with existing context and version)
3. Try to undeploy an existing API

### Affected Product Version:
Choreo Connect 0.9.0.3
apictl v4.0.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by pubudu538** [comment]
This is not a recommended pattern. Either you work with apictl --> mgw or apictl --> APIM--> mgw.
