### ISSUE TITLE
Upgade netty once azure monitor beta 5 is released

### ISSUE THREAD

**Issue by praminda** [wso2/product-microgateway#2262]
### Describe your problem(s)

$subject.
Netty upgrade is dependent on `com.azure:azure-monitor-opentelemetry-exporter-beta5`.
### How will you implement it

Upgrade netty to > 4.1.68.Final version after azure monitor beta 5 is done

**Comment by Rajith90** [comment]
In order to use the beta 5 of exporter do we need to upgrade the netty version in the enforcer?

**Comment by praminda** [comment]
related to #2259

**Comment by pubudu538** [comment]
Requested to release with the issue: Azure/azure-sdk-for-java#25295
