### ISSUE TITLE
Production Guide for CC

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-microgateway#2270]
### Content Positioning in Documentation:

- Link:

- Heading (& Step):

- Any other reference:

---

**Comment by renuka-fernando** [comment]
Docs:
- 4.0.0: https://github.com/wso2/docs-apim/pull/5214
- latest: https://github.com/wso2/docs-apim/pull/5243

**Comment by renuka-fernando** [comment]
https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline/
