### ISSUE TITLE
Rollback to the original Envoy trust file when upgraded to latest Envoy

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#2290]
### Description:
Its probably good idea to have a seperate issue to rollback to the original envoy trust file when we upgrade to the latest envoy version which has the fix

_Originally posted by @Rajith90 in https://github.com/wso2/product-microgateway/pull/2289#issuecomment-941111700_

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
#### Related Issues:
https://github.com/wso2/product-microgateway/issues/2255

**Comment by pubudu538** [comment]
The same issue is still there in Envoy 1.20 image as well.
