### ISSUE TITLE
A resource that starts with the same word as the basepath returns 404

### ISSUE THREAD

**Issue by suksw** [wso2/product-microgateway#2308]
### Description:

- When the basepath is `/foo` and the resource is `/foo-bar` choreo-connect returns a 404 for `https://localhost:9095/foo/foo-bar`.
- This does not occur when basebath is `/foo1` and the resource is `/foo-bar`. Then it returns the correct response for `https://localhost:9095/foo1/foo-bar`
- Works correctly for basepath `/v2/foo` and resource `/foo-bar` as well

### Steps to reproduce:
1. Create a swagger 2 definition
2. Add `x-wso2-basePath: /foo`
3. Add a resource `/foo-bar`
4. Deploy the API via apictl
5. Invoke `<host-url>/foo/foo-bar`

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by SuKSW** [comment]
Yes, this is in the standalone mode. In the APIM mode, APIM sets the basepath as `/foo/1.0.5` where 1.0.5 is the version. Therefore, I think we are safe in the APIM mode.

**Comment by AmaliMatharaarachchi** [comment]
This is not reproducing now. Hence closing the issue
