### ISSUE TITLE
Wire logs with request/response body

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#2360]
### Describe your problem(s)
logs with request/response body when it is enabled.

### Describe your solution

Add descriptive debug and trace logs.
https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-component-log-level

### How will you implement it

---

**Comment by pubudu538** [comment]
This is implemented with the PR - https://github.com/wso2/product-microgateway/pull/2936
