### ISSUE TITLE
[IMPROVEMENT] [MGW-TOOLKIT] [3.2.0] - Configure per API timeout in gRPC service definition

### ISSUE THREAD

**Issue by dev-skd** [wso2/product-microgateway#2373]
### Describe your problem(s)
As per the current implementation of the microgateway, we can not define the endpoint timeout in the gRPC service definition. It should improve the microgateway toolkit to generate endpoint configuration that defines in the gRPC  service definition in open API definition as below,
```
x-wso2-production-endpoints:
    urls:
      - https://localhost:2380/v3
    advanceEndpointConfig:
      timeoutInMillis: 7000
```

### Describe your solution
It requires modifying the <toolkit-home>/resources/grpc/wso2_options.proto file to define the endpoint configuration in the gRPC definition. Please refer to the following sample advance endpoint definition that defines in the wso2_options.proto file.

```
message Endpoints {
repeated string url = 1;
EndpointType type = 2;
message AdvanceEndpointConfig {
int32 timeoutInMillis = 1;
}
AdvanceEndpointConfig advanceEndpointConfig = 3;
}
```
In order to reflect the above changes, it requires changing source code [1] and generating an identical open API model in [2] as well.
[1]: https://github.com/wso2/product-microgateway/blob/3.2.x/components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/protobuf/ExtensionHolder.java
[2]: https://github.com/wso2/product-microgateway/blob/ba4ff8850656be54848c6d99a0a96a701d3fb552/components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/protobuf/ProtoOpenAPI.java#L127

**Comment by pubudu538** [comment]
Where is the 3.2.x fix for this?

**Comment by chashikajw** [comment]
> Where is the 3.2.x fix for this?

Added the fix
