### ISSUE TITLE
All Endpoints belongs to an API requiring same basepath

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#2383]
### Description:

Choreo connect has a limitation on endpoints where every endpoint defined for an API should have a common base path.
this limitation is affected for x-wso2-production-endpoints, x-wso2-sandbox-endpoints, x-wso2-endpoints extensions.
Since APIM allows following scenarios this needs to be addressed/validated properly in apim and choreo-connect.

for an examples check below scenarios
scenario 1:
```
prod endpoint: https://prod:8080/v2
sand endpoint:https://sand:8081/v3
```
not allowed- different base paths in prod and sand endpoints /v2 /v3

scenario 2:
```
prod lb endpoints: 
https://prod/v2, 
https://lb/v3
```
 not allowed - different base paths on prod lb endpoints /v2 and /v3

scenario 3:
```
prod lb endpoints: 
https://run.mocky.io/v3/8bd89417-22af-426e-9739-51770afcf312, 
https://run.mocky.io/v3/9bd89417-22af-426e-9739-51770afcf789
```
 not allowed - different base paths endpoints /v3/8bd89417-22af-426e-9739-51770afcf312 and /v3/9bd89417-22af-426e-9739-51770afcf789

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by renuka-fernando** [comment]
Related Issue:
https://github.com/wso2/product-microgateway/issues/2327

**Comment by AmaliMatharaarachchi** [comment]
As per an offline discussion, it's concluded that to go ahead with restricting the basepath to be same for all endpoints given for an API. Basepath validation has improved with this PR https://github.com/wso2/product-microgateway/pull/2395. Hence, closing this issue.

**Comment by pubudu538** [comment]
With headers support, we can support different base paths. @NomadXD's PR is for that change. Still we need to use same base paths for dynamic routing.
