### ISSUE TITLE
Adapter readiness probe fails as connection with Global Adapter fails.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#2414]
### Description:
$subject. This was due to the configuration refactor implementation [1] . The Overwritehostname is not replaced with OverrideHostName property in the implementation.

[1] https://github.com/wso2/product-microgateway/issues/2300

### Steps to reproduce:
Run the adapter with global-adapter with no OverwriteHostName property. 

### Affected Product Version:
Choreo-Connect-1.0.0-alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by renuka-fernando** [comment]
This should be merged to the main branch https://github.com/wso2/product-microgateway/pull/2413
