### ISSUE TITLE
Formalising Error Logs in Choreo Connect Components

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-microgateway#2422]
## Describe your problem(s)
Need to implement a standard way to monitor the Error Logs

## Describe your solution(s)
Structured Logging - To extract Error logs more efficiently (JSON Format)

Correlation Id - An id to track a specific set of logs together with request vise. It should be unique per request. 

**Note:- Below fields are only applicable for Log level - Error**

Severity level - Defined based on the criticality of the error. 
> Blocker
> Critical
> Major
> Minor
> Trivial

Error code - To narrow down the details of errors. With this error code, anyone should be able to 
> Narrow down the error
> Cause of the error
> How to correct it.

**Comment by shananjana** [comment]
Subtask of https://github.com/wso2-enterprise/choreo/issues/9250
