### ISSUE TITLE
Provide advanced configurations for the router

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#2424]
### Describe your problem(s)

When it comes to improve performance, it is better if users could change the values mentioned in [1].

https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge#best-practices-edge

### How will you implement it

---

**Comment by pubudu538** [comment]
Duplicate issue - https://github.com/wso2/product-microgateway/issues/2813
