### ISSUE TITLE
Automate getting the product name and version for the product.txt file

### ISSUE THREAD

**Issue by nihlaakram** [wso2/product-microgateway#243]
**Description:**
The filter.properties file that can be utilized to get the product name and version is redundant. Instead need an automated solution to do this for each release iteration.

**Suggested Labels:**
Improvement

**Suggested Assignees:**
N/A

**Affected Product Version:**
N/A

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by praminda** [comment]
Fixed with #364 
With this fix, product.version property in filter.properties file should be updated for each release.
