### ISSUE TITLE
Upgrade the dependency azure-monitor-opentelemetry-exporter

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#2430]
### Describe your problem(s)
Current dependency is azure-monitor-opentelemetry-exporter:1.0.0-beta.4

### Describe your solution
Upgrade the dependency azure-monitor-opentelemetry-exporter:1.0.0-beta.5 when it is released.
Requested to release with the issue: https://github.com/Azure/azure-sdk-for-java/issues/25295

### How will you implement it

---

**Comment by pubudu538** [comment]
Duplicate issue - https://github.com/wso2/product-microgateway/issues/2262
