### ISSUE TITLE
API key fails when enforcer debug enabled

### ISSUE THREAD

**Issue by suksw** [wso2/product-microgateway#2437]
### Description:
API-Key returns 401 when enforcer debug enabled via log4j2.properties

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
Whats in the log when this happens?

**Comment by suksw** [comment]
> Whats in the log when this happens?
It doesn't give a specific log. The apikey just fails with a 401 and the log says none of the authenticators were able to validate the request.
