### ISSUE TITLE
Can't handle request with header Expect:100 continue

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#244]
**Description:**
Send a request to the micro gw containing header Expect:100 continue. The request will fail.

Use the following curl request to re create  the issue. This request invoke /token endpoint of gateway with jwt grant

`curl -k -X POST -u Tui7GdCBi2aUjdzFoUNwBxMA4n8a:QtoTyQHp8gQpln2C2QGQ35U3PdUa -k -d 'grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=eyJ4NXQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJraWQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiaWdoMm1hc3YtYWNTUnpxTmJyM3UzdyIsImF1ZCI6WyJWRDdqZzFTd1V5N2o4U0hDVmtuZkc2UnE5R29hIiwiaHR0cHM6XC9cLzE3Mi4xNy4wLjE6OTQ0M1wvb2F1dGgyXC90b2tlbiJdLCJjX2hhc2giOiJadFdpWU1RbGhaNU56aXFpYjRYWm9nIiwic3ViIjoiZmFyYXphdGgiLCJuYmYiOjE1MzY4MzkyODUsImF6cCI6IlZEN2pnMVN3VXk3ajhTSENWa25mRzZScTlHb2EiLCJhbXIiOlsidG90cCIsIkJhc2ljQXV0aGVudGljYXRvciJdLCJpc3MiOiJodHRwczpcL1wvaWRwLndzbzIuY29tIiwiZXhwIjoxNTM2ODQyODg1LCJpYXQiOjE1MzY4MzkyODV9.Xo5Jok8Pd2WnMvE-pNjjMFWrCuw4jhRebQpVIqmkkPu2UOlPtkVUbj3YyLjaaiv2UcpxyjS83rBr2D1tKVn3oQMw0aTuM730PTw46Z2dLy6YZ0GyIGKUAgTgroXBIRRMKxBUg2ar5WZsdaLijRueRHqKx6Bjh5wYx1nCNPx34T574F_8HDz1TScQk5nXtGb5ItNmO4LoTS-e-5y5uwIhcdjCUPVijIKei7aVgi_tj81uShuz6veXWEFUp4MiBiQ7R9CZPVGFJs698zIpnsurPZk6CvVOW8pKBQT7klewQWomkbkessOva3Ts5MSCfimrUDZ0tq4fUmihUg6CstuTkQ' -H 'Content-Type: application/x-www-form-urlencoded' https://localhost:9096/token`
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praminda** [comment]
@kavishkafernando @Rajith90 
Do we have any updates for this after the new fixes we did for supporting **Expect: 100**?
[1]: https://github.com/wso2/product-microgateway/issues/231

**Comment by Rajith90** [comment]
@praminda , yes #339 Fixes the issue
