### ISSUE TITLE
Microgateway 3.2.0 return 408 request timeout

### ISSUE THREAD

**Issue by riyazathali** [wso2/product-microgateway#2456]
### Description:
The 408 Request Timeout error is observed for a few requests intermittently in the API micro gateway. According to the observations, the Microgateway had not initiated the OutBoundRequest to send the client request to the backend. After 2 minutes, we can see the 408 Request Timeout error. (Idle timeout triggered before initiating outbound response).

### Steps to reproduce:

1. Get the APIM 3.2.0
2. Create a mock backend to send JSON payload.
3. Create and publish an API with the endpoint and subscribe to it.
4. Get the WUM updated wso2am-micro-gw-toolkit-macos-3.2.0 pack and import the above API to the toolkit.
5. Apply the interceptor.bal as below to the wso2am-micro-gw-toolkit-macos-3.2.0/bin/sample/interceptors/ location and mention it in the API definition file as x-wso2-request-interceptor: validateRequest.
```
public function validateRequest (http:Caller outboundEp, http:Request req) {
 
}
```
6. Build the project
7. Add the following configurations in the wso2am-micro-gw-macos-3.2.3/conf/micro-gw.conf file.
# API Authorization security for the gateway and the backend
```
[authConfig]
 # Authorization header expected by the Microgateway. Can be overridden at API level using the extension
 authorizationHeader = "Authorization"
 # Remove authorization header from the backend request
 removeAuthHeaderFromOutMessage = false
# Throttling configurations
[throttlingConfig]
  enabledGlobalTMEventPublishing = true
  jmsConnectionProviderUrl = "amqp://admin:admin@carbon/carbon?brokerlist='tcp://localhost:5672'"
  # Throttling configurations related to event publishing using a binary connection
  [throttlingConfig.binary]
    enabled = true
    [[throttlingConfig.binary.URLGroup]]
      receiverURL = "tcp://localhost:9611"
      authURL = "ssl://localhost:9711"
[apim.eventHub]
  enable = true
  serviceUrl = "https://localhost:9443"
  internalDataContext="/internal/data/v1/"
  username="admin"
  password="admin"
  eventListeningEndpoints = "amqp://admin:admin@carbon/carbon?brokerlist='tcp://localhost:5672'"
[b7a.http]
[b7a.http.tracelog]
console = true
```
8. Run the project with the wso2am-micro-gw-macos-3.2.3 runtime
9. Invoke the API with 10 concurrent users, Ramp-up period 1s via JMeter script with an infinite loop.
10. There will be the following in the microgateway.log file
`Idle timeout triggered before initiating outbound response`
11. On the client-side, we can see the following in the Jmeter jti file.
`<httpSample t="121429" lt="121429" ts="1633343667484" s="false" lb="HTTP Request" rc="408" rm="Request Timeout" tn="Thread Group 1-6" dt="text" by="174" ng="10" na="10"/>`

### Affected Product Version:
API micro gateway 3.2.0

**Comment by elevencityhost** [comment]
Hi WSO2 Experts,
Great news that you've resolved this issue.
But I didn't see release update on link: https://github.com/wso2/product-microgateway/tags, v3.2.3 still released on on 15 Jul 2021. I made a test on this version, the 408 request timeout still exists. 
When will you update the new release about v3.2.3 ?
