### ISSUE TITLE
Issue in "created" life cycle state

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#2459]
### Steps to reproduce:
1. create and publish an api using the apim.
2. generate a production jwt using the devportal.  
3. demote the api to created state in publisher.
4. should not be able to invoke the API using production jwt (only internal keys should be allowed.) 

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by pubudu538** [comment]
Check the synpase gateway.

**Comment by suksw** [comment]
Tested the scenario in a U2 updated API-M 4.0.0 pack. I was able to invoke an API with a token generated from the devportal while the API was in the created state. Assigning the issue back to @AmaliMatharaarachchi

**Comment by AmaliMatharaarachchi** [comment]
closing as per above comment.
