### ISSUE TITLE
Support API blocking and subcription throttling for API key

### ISSUE THREAD

**Issue by suksw** [wso2/product-microgateway#2483]
### Description:
$subject

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by pubudu538** [comment]
API key contains the subscription values and we should use that to validate the subscription. In case a user wants to delete the subscription for an API key, then he needs to revoke the API key. We should be able to improve APIM side where subscription deletion revokes the API keys. At the moment we don't store any API keys. First, we need to persist the API keys in APIM.

**Comment by suksw** [comment]
Closing to open a new issue "Validate subscriptions for API key when enabled"
