### ISSUE TITLE
Error While bulding an API with a SOAP Endpoint

### ISSUE THREAD

**Issue by fjunior87** [wso2/product-microgateway#249]
**Description:**
I am getting the error below when trying to build an API which the endpoint is HTTP/SOAP Endpoint.

Below you can see the output when trying to build it:
```
micro-gw build correios
could not find package wso2/gateway:*
error: src:0.0.0\TestCorreios_1_0_0.bal:87:34: undefined symbol 'TestCorreios_1_0_0_sand'
error: src:0.0.0\TestCorreios_1_0_0.bal:87:34: invalid action invocation, expected an endpoint
micro-gw: Internal error occurred while executing command.
```

**Suggested Labels:**

**Affected Product Version:**
WSO2 API Manager 2.5
wso2am-micro-gw-toolkit-2.5.0
**OS, DB, other environment details and versions:**    
Windows 10
**Steps to reproduce:**
Create an API with a HTTP/SOAP Endpoint
Execute the micro-gw setup for the created API
Then try to build it

**Comment by praminda** [comment]
@fjunior87 Thanks for reporting the issue and Sorry for the late response.
I was able to reproduce the issue in 2.7.0-m1. We'll check on this.

**Reproduced OS:** Ubuntu

**Comment by praminda** [comment]
@fjunior87 
Fix is merged into ballerina-update branch. It'll be available in the next release.
