### ISSUE TITLE
Invoke a APIM REST endpoint when an API removed from the gateway 

### ISSUE THREAD

**Issue by shanakama** [wso2/product-microgateway#2528]
### Describe your problem(s)
Currently there is no way to notify APIM when removing an API from the gateway.

### Describe your solution
There is a specific REST endpoint at the APIM to remove the un-deployed API revision deployment information entry from the database .Once an API removed from the gateway, adapter should invoke the APIM REST endpoint with relevant payload.

### How will you implement it
Invoking the APIM REST endpoint if  the API revision successfully un-deployed from the gateway.

---
#### Related Issues:
https://github.com/wso2-enterprise/choreo/issues/9175

**Comment by renuka-fernando** [comment]
@shanakama could you please do the changes in https://github.com/wso2/product-microgateway/pull/2503 to the main branch as well?

**Comment by shanakama** [comment]
> @shanakama could you please do the changes in #2503 to the main branch as well?

Sure, will do.
