### ISSUE TITLE
Document throttling in HA deployment

### ISSUE THREAD

**Issue by yhilem** [wso2/product-microgateway#253]
**Description:**
Microgateway offers a proxy that is capable of performing security validations (OAuth, Signed JWT), in-memory (local) rate limiting and operational analytics (https://docs.wso2.com/display/AM260/Working+with+the+API+Microgateway).

There is no documentation that describes how throtling is done in a HA Deployment (for example a replication factor 3 in kubernetes environment).

Thanks
Youcef HILEM

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by yhilem** [comment]
Yes, that I know it.
But what should we do to deploy in HA with consistent throttling policies tied to that cluster?
When we apply a throttling policy to an API saying x calls per second, a user will be able to get 2x with a a 2-node cluster.

Thanks

**Comment by uvindra** [comment]
Yes @yhilem thats correct, the Microgateway does not replicate its throttle counters among other nodes in the cluster. It is not designed to function in this way. Each Microgateway instance maintains its own independent private throttle counter. If you need to sync throttle counters across multiple gateway nodes you need to use the traditional Centralized synapse gateway as mentioned here[1]

[1]https://docs.wso2.com/display/AM250/Overview+of+the+Microgateway#OverviewoftheMicrogateway-WhentousetheCentralizedAPIGateway

**Comment by uvindra** [comment]
FYI @yhilem API Manager team is already working on addressing this short coming regarding throttling in the Microgateway in the upcoming release for Q3 2018. So this limitation should be addressed soon
