### ISSUE TITLE
[3.2.0] The microgateway server does not immediately terminate the client-side connection when an Inbound RST_STREAM is received from the backend service.

### ISSUE THREAD

**Issue by dev-skd** [wso2/product-microgateway#2540]
### Description:
The microgateway server does not immediately terminate the connection between the client and the gateway (downstream) when an Inbound RST_STREAM is received from the backend service (upstream). It waits till the stream idle timeout happens. 

### Steps to reproduce:

Download the RST_STREAM_ISSUE_ARTIFACTS.zip file from the drive location [1] and extract it.

Deploy the microgateway 1

- Place the extracted MG1/advanceEndpoint.mustache and MG1/listeners.mustache files inside the <MGW-TOOLKIT-HOME>/resources/templates directory. To set the advance endpoint timeout (600000ms) and listener timeout(660000ms).
- Execute the following command inside the <MGW-TOOLKIT-HOME>/bin directory to initiate the microgateway project.
`./micro-gw init micro_gateway1`
- Create a subdirectory called OrderService under <MGW-TOOLKIT-HOME>/bin/micro_gateway1/grpc_definitions.
- Place the extracted MG1/extenda_refdata_new.proto file inside the OrderService directory.
- Then Execute the following command inside the <MGW-TOOLKIT-HOME>/bin directory to build the microgateway project.
`./micro-gw build micro_gateway1`
- Open the <MGW-HOME1>/conf/micro-gw.conf file and replace the existing listenerConfig configuration with the following configuration.
```
[listenerConfig]
host = "0.0.0.0"
httpPort = 9092
httpsPort = 9097
keyStorePath = "${mgw-runtime.home}/runtime/bre/security/ballerinaKeystore.p12"
keyStorePassword = "ballerina"
trustStorePath = "${mgw-runtime.home}/runtime/bre/security/ballerinaTruststore.p12"
trustStorePassword = "ballerina"
tokenListenerPort = 9098
```
- Execute the following command inside the <MGW-HOME1>/bin to start the generated microgateway project.
`./gateway <path to generated microgateway artifact> --b7a.http.tracelog.console=true`

 Deploy the microgateway 2
 
- Place the extracted MG2/advanceEndpoint.mustache and MG2/listeners.mustache files inside the <MGW-TOOLKIT-HOME>/resources/templates directory. To set the advance endpoint timeout (360000ms) and listener timeout (330000ms). 
- Execute the following command inside the <MGW-TOOLKIT-HOME>/bin directory to initiate the microgateway project.
` ./micro-gw init micro_gateway2`
- Create a subdirectory called OrderService under <MGW-TOOLKIT-HOME>/bin/micro_gateway2/grpc_definitions.
- Place the extracted MG2/extenda_refdata_new.proto file inside the OrderService directory.
- Then Execute the following command inside the <MGW-TOOLKIT-HOME>/bin directory to build the microgateway project.
` ./micro-gw build micro_gateway2`
- Execute the following command inside the <MGW-HOME2>/bin to start the generated microgateway project.
`./gateway <path to generated microgateway artifact> --b7a.http.tracelog.console=true`
- Then execute the following command to start the backend service (you can find the serverImpl-1.0-SNAPSHOT.jar file from the extracted Backend folder ).
` java -jar serverImpl-1.0-SNAPSHOT.jar 9091`
- Place the order_service.proto file inside the grpcurl_1.8.1_linux_x86_64 directory.
- Then execute the following grpcurl command in the grpcurl_1.8.1_linux_x86_64 directory to invoke the gRPC API.
` ./grpcurl  -v -insecure -H "grpc-accept-encoding: gzip"  -H "accept: application/grpc" -format-error  -d '{"location":0}' -proto order_service.proto 127.0.0.1:9097 org.mgw_demo.order_service_lib.OrderService/subscribeItemDetails`
- Then wait for 11 minutes and then you will be able to see log lines as below in the MG1 server logs,
```
[2021-11-30 17:18:47,547] TRACE {http.tracelog.upstream} - [id: 0xe0e4937d, L:/127.0.0.1:37108 - R:localhost/127.0.0.1:9090] INBOUND RST_STREAM: streamId=3 errorCode=2  
[2021-11-30 17:24:17,543] TRACE {http.tracelog.downstream} - [id: 0x596e79b7, L:/127.0.0.1:9097 - R:/127.0.0.1:58938] OUTBOUND RST_STREAM: streamId=1 errorCode=2  
```

### Affected Product Version:
3.2.0

[1]: https://drive.google.com/file/d/1PmZy3ma7VP0FORQrC6LRx-PKVwmeP5o7/view?usp=sharing

**Comment by msm1992** [comment]
With https://github.com/wso2/product-microgateway/commit/19707192dc7c9460555d4903b043db76bd1718a1 3.2.x ballerina version is upgraded to 1.2.25 which contains this fix too. Hence resolving the issue.
