### ISSUE TITLE
Backend JWT is not generated for unsecured resources

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#2569]
### Steps to reproduce:
enable backend jwt generation
turn of security of an api resource.
invoke the resource and check outbound headers

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by renuka-fernando** [comment]
It seems in ballerina mgw, we do not generate JWT token unless it is JWT or opaque token

https://github.com/wso2/product-microgateway/tree/59bc37d348ccf9acbce709f6fee5bfcc89f5ac3a/components/micro-gateway-core/src/main/ballerina/src/gateway/handlers

unless secured auth handlers don't get applied and there will not be any backend jwt if handelrs are not applied
