### ISSUE TITLE
Setup and build command output stream issue.

### ISSUE THREAD

**Issue by NipunaPrashan** [wso2/product-microgateway#260]
**Description:**
microgateway build command output and setup command output successful messages are getting as error output streams. 

![image](https://user-images.githubusercontent.com/8381009/46655124-4ec17880-cbc8-11e8-90fc-8537b9ff3dd7.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/259
