### ISSUE TITLE
API/Subscription Rate Limiting does not work for websocket APIs

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#2673]
### Description:
API Level throttling and subscription level throttling does not work for websocket APIs. 

### Steps to reproduce:
Create a websocket API. 
Assign a rate limiting policy and invoke.

### Affected Product Version:
Choreo-Connect 1.0.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by suksw** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/2667
