### ISSUE TITLE
Git Integration for Choreo Connect

### ISSUE THREAD

**Issue by nandulaperera** [wso2/product-microgateway#2676]
### Describe your problem(s)
When Choreo Connect is used as a [standalone gateway](https://apim.docs.wso2.com/en/4.1.0/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/as-a-standalone-gateway), APIs can be deployed through the APICTL command-line tool. Once an API project is added/updated, it must be deployed/redeployed using APICTL. If the Adapter container restarts for any reason, the APIs deployed with APICTL will be lost.

### Describe your solution
A source watcher, in the Adapter, is responsible for deploying the API artifacts, with the help of Git. Initially, it is required to have a repository with the API projects, hosted on a source control system (E.g. GitHub, Bitbucket). When the Adapter starts, the source watcher will clone the API project(s) from the given repository and will deploy the API artifacts. The source watcher will then start polling the repository for changes. If there are any updates in the repository, the source watcher will fetch the changes and will deploy the updated API artifacts.

### How will you implement it

---

**Comment by Rajith90** [comment]
It would be great if we can improve the feature to get updates from a webhook as well, apart from polling. Gitbub, bit bucket etc provide webhook notifications on a commit or a pull request is merged

**Comment by pubudu538** [comment]
We can consider this requirement in the future.
