### ISSUE TITLE
[Websocket] [Analytics] Analytics Events publishing for Websocket

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#2705]
### Describe your problem(s)

Analytics Events should be published for all the handshake requests, publishing frames and subscribed frames. Throttle failures, Auth Failures and Target connectivity issues also needs to be shown in the choreo analytics portal.

### How will you implement it

---

**Comment by suksw** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/2696
