### ISSUE TITLE
Trim spaces in backend endpoints

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#2707]
### Description:
In APIM publisher we can set endpoints with trailing spaces, which better to trim from the CC side.
for eg:
```
http://run.mocky.io/v2/5185415ba171ea3a00704eed<SPACE_HERE> 
```

When invoking the API getting 400, may confuse the user.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by pubudu538** [comment]
@Amila-Rukshan is working on this.
