### ISSUE TITLE
Improve logs with timestamps

### ISSUE THREAD

**Issue by AyeshW** [wso2/product-microgateway#2709]
### Describe your problem(s)

While investigating on choreo incidents, we found that some component logs missing timestamps.
```
ballerina: initializing connection with observability backend periscope.choreo.dev:443
ballerina: visit http://console.choreo.dev/observe/app/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY to access observability data
ballerina: started publishing metrics to Choreo
```
Therefore, having timestamps in standard out logs makes debugging easier.

### Describe your solution

Improve logs with timestamps

### How will you implement it

---

**Comment by pubudu538** [comment]
This is not related to the Choreo Connect gateway. @AyeshW Please create a separate issue in the Ballerina side.
