### ISSUE TITLE
Improve Websocket implementation

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#2719]
### Describe your problem(s)

It is required to do following improvements to the websocket implementation compared choreo-connect-1.0

- Supporting async APIs
- Supporting scope based protection
- Topic level support
- Fix rate-limiting related issues
- Analytics for websocket APIs

### How will you implement it

---

**Comment by suksw** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/2718
