### ISSUE TITLE
Add Executable Permission for Generated gateway Script

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-microgateway#273]
**Description:**
The gateway start script is not executable by default. This prevents dot slash executions of the script, giving a "permission denied" error if a user does ./gateway. 

Executable permissions needs to provide for the scripts in https://github.com/wso2/product-microgateway/tree/master/distribution/resources/bin
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praminda** [comment]
AFAIK not all zip utils can preserve unix file permissions while creating the .zip archives. Let us do some research and find a solution for this.

**Comment by Rajith90** [comment]
One workaround is to set the permission using chmod command. Hence this is not a blocker, reducing the severity

**Comment by Rajith90** [comment]
This is fixed after the toolkit and run time separation was done in 3.0.0 beta 2
