### ISSUE TITLE
Improve the error logs in the micro gw cli

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-microgateway#274]
**Description:**

Upon any runtime error, the cli provides the following error message which is not sufficient to identify the root cause of the issue.

micro-gw: Internal error occurred while executing command.

We need to check and improve the error responses.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Rajith90** [comment]
By default we only logs the complete error message to the log file. But by changing the logging.properties file [1] we can output the error message to console and log file both. 
In PR [2] we have added only the error message to console output.

[1] - https://github.com/wso2/product-microgateway/blob/master/distribution/resources/cli-conf/logging.properties#L33
[2] - https://github.com/wso2/product-microgateway/pull/395

**Comment by Rajith90** [comment]
#395 Merged to master
