### ISSUE TITLE
Event Health check for GA

### ISSUE THREAD

**Issue by shanakama** [wso2/product-microgateway#2747]
### Describe your problem(s)

At times, Global Adaptor is unable to receive events from the ASB, and the only solution we've found come across is re-starting GA pods. In order to detect GA is frozen we need to check whether events are getting received by the GA regularly. 

### Describe your solution

Send a special event (health check) periodically and check whether the event is received properly by matching the sent and received event count. If there any mismatch between the count , then triggering an alert.

### How will you implement it

There will be an external application that sending health check events periodically and printing logs for each event. Then calculating the log count per relevant time period.

---

**Comment by pubudu538** [comment]
Fix is already available. Hence closing the issue.
