### ISSUE TITLE
Endpoint security credentials does not work with apim

### ISSUE THREAD

**Issue by Amila-Rukshan** [wso2/product-microgateway#2770]
### Description:

After settings Endpoint security values for a API and deploying does not show the corresponding auth header in the backend request.
 

### Affected Product Version:

1. Run mgw with apim. 
2. Create an API in apim with endpoint credentials in endpoints tab. 
ex: Basic Auth
3. Send a request to the endpoint and note that the authorisation header with basic auth header is retrieved at back-end.

### Environment details (with versions):
- OS: Unix
- Client: 
- Env (Docker/K8s): Docker

---

**Comment by AmaliMatharaarachchi** [comment]
@Amila-Rukshan I tested the above scenario with the apim RC1 and cc latest image. but could not reproduce. Can you verify this?

Also seems like there's an integration test covering it as well.

**Comment by Amila-Rukshan** [comment]
It worked in my local env as well

**Comment by pubudu538** [comment]
Hence closing this issue.
