### ISSUE TITLE
Mock Impl fails for super tenant and tenant

### ISSUE THREAD

**Issue by suksw** [wso2/product-microgateway#2772]
### Description:
Mock impl returns the following instead of the configured response for both super tenant and tenant

```
{
  "error_message": "Not Implemented",
  "code": "900871",
  "error_description": ""
}
```

### Steps to reproduce:
1. Create and publish an API
2. Change the endpoint type to Mock Implementation from the endpoints tab
3. Update the GET resource to the following from the definitions tab
```
paths:
  /*:
    get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: I am a get
```
5. Save the changes
6. Create new revision and deploy
7. Go to Dev portal and check if the configured response appears under the resource method
8. Invoke the resource method

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by AmaliMatharaarachchi** [comment]
You have to provide examples under the content in order to enable mock responses. the above behaviour is expected as we have not added any examples under content

**Comment by suksw** [comment]
What would be the correct way of adding an example?

**Comment by AmaliMatharaarachchi** [comment]
for oas3, refer https://swagger.io/docs/specification/adding-examples/#:~:text=description%3A%20OK-,Here%20is%20an%20example,-of%20the%20example

**Comment by suksw** [comment]
My bad, got confused because the dev portal displayed the response I configured under the correct resource method. So as per [this](https://github.com/wso2/docs-apim/pull/5486/files) following is the format,
```
get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              example: I am a get
```

And once the correct format is added, both the API definition editing tab and the endpoint tab in publisher must show the configured examples as given below right?
![image](https://user-images.githubusercontent.com/17605554/159695823-e77982d9-eb68-475d-818e-69c10b47fe57.png)
![image](https://user-images.githubusercontent.com/17605554/159696017-e18e7915-103b-42b2-9ef4-11aac6705614.png)

**Comment by AmaliMatharaarachchi** [comment]
yes, you can confirm that it has been added correctly by going to the publisher portal's endpoint > mock implementation > choreo connect. You should see the examples there if you have added examples correctly in the API specification. Make sure to save and deploy as well.
