### ISSUE TITLE
Increased memory consumption and OOM Issue when analytics connection is broken

### ISSUE THREAD

**Issue by nuwankng** [wso2/product-microgateway#2822]
### Description:
When analytics connection is broken with the microgateway it tries to reconnect continuously resulting an Out of Memory error after increasing the heap usage.

![memory consumption (1)](https://user-images.githubusercontent.com/16064951/160753890-2a1befb8-1f32-4f3a-a4f1-7b199e1f0876.png)

### Steps to reproduce:

1. Create an MGW project following the documentation [1]
2. Stop the analytics node while bursting the MGW with requests.
3. Observe the heap usage against time

### Affected Product Version:
MGW-3.2.0/Analytics-3.2.0

[1]. https://mg.docs.wso2.com/en/latest/getting-started/quick-start-guide/quick-start-guide-binary/#quick-start-guide-binary

**Comment by pubudu538** [comment]
@rashm1n Where is the fix for the public branch? Can you send the fix to 3.2.x branch?

**Comment by chashikajw** [comment]
Closed with the above comment
