### ISSUE TITLE
Add gRPC support for Micro-gateway 

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-microgateway#283]
**Description:**
gRPC is a high-performance, lightweight communication framework designed for making traditional RPC calls, and developed by Google. The framework uses HTTP/2, the latest network transport protocol, primarily designed for low latency and multiplexing requests over a single TCP connection using streams. This makes gRPC amazingly fast and flexible compared to REST over HTTP/1.1.
   Existing micro-gateway does not provide support for gRPC protocol. To include above mentioned benefits to micro-gateway it is required to implement this support into micro-gateway.

**Suggested Labels:**
Enhancement
type/feature

**Affected Product Version:**
2.6.0
3.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Suggested Approach:**
Implement gRPC support for product micro-gateway as a service which supports HTTP requests into gRPC supported ones. In this scenario we have to implement a ballerina service which receives REST requests and convert them to requests that can be identified in endpoint which is a gRPC service. But in this case we don't need to implement new gRPC filers to process request since receiving requests will be treated as REST/HTTP requests. After the filter processing these requests will be converted into gRPC supported ones. Then that converted ones will be sent to endpoint. When user provides the .proto API definition at Setup command level it reads the proto file and creates the ballerina file which act as service which do the REST to gRPC conversion. For that we have to implement logic to read .proto file from the scratch and implement the business logic of conversion according to the .proto file.

![qp2](https://user-images.githubusercontent.com/42435576/51366751-232a2480-1b0d-11e9-9786-726ef4f1cd47.png)

Figure 1

According to above approach this grpc feature is to be enabled at micro-gateway set up. At microgateway setup user required to provide .proto definition and the grpc endpoint. We will introduce a new setup command flag as “-oa” and “--openApi” which can be configured at setup command as “-oa=”PATH_TO_”.proto”_API_DEFINITION_FILE” to provide path of the “.proto” API definition file which required to setup micro-gateway with gRPC support. Then it requires to enter gRPC endpoint at the setup with “-e” flag. In this scenario user can only enter gRPC endpoint as the production endpoint. When this command is provided, the ballerina source will be generated in a way it can support above figure 1 diagram flaw.

Then from the given path, cmd side of product micro-gateway which written in Java will extract methods, models and configurations from the file and generate the java objects related to that definition given in the .proto file. Ballerina grpc support has a skeleton which used to generate ballerina source that support gRPC protocol. Then java objects will be mapped into that skelton and generate “Client_stub.bal” file and generate “Client.bal” file which includes logic of converting HTTP request payloads into gRPC supported objects. And this Client.bal file has the ability to convert gRPC responses into HTTP/REST responses also. This ballerina source files has to be generated using mustache templates. 
In the mapping of HTTP/ REST to gRPC there is a optional field as HTTP Rule in the proto files which uses to convert Resource methods and it’s paths into their respective gRPC supported functions. The bold highlighted field of following .proto code segment is an example for that.  
```
syntax = "proto3";

package greeter;

import "google/api/annotations.proto";

service Say {
    rpc Hello(Request) returns (Response) {
       **option (google.api.http) = {
            post: "/greeter/hello"
            body: "*"
        };**
    }
}

message Request {
    string name = 1;
}

message Response {
    string msg = 1;
}
```

After the resources are generated then using build command user can get an executable and start the server.

**Steps to be done for providing this Feature.**
Current ballerina does not have the support of creating service.bal file which expose service as HTTP service with REST to gRPC conversion.

- Ballerina has to provide support to read the HTTP Rule option in ".proto" definition, which is mentioned earlier to support REST to gRPC mapping. This mapping will be done from the API .proto definition when the "--mode" flag is set to "Gateway" in ballerina command tool and this Gateway option is not yet provided by the ballerina. Therefore, as the first step micro gateway has to upgrade it's ballerina version to a version that support this feature.

- Then micro gateway should provide endpoint of the gRPC service which is provided by user at the Setup command level to the ballerina file builder using "GRPCUtils.java" file.

- Then the mode also have to set "Gateway" and provide it to BallerinaFileBuilder at "GRPCUtils.java" file.

- Then ballerina will generate the "Client_stub.bal" file and "Service.bal" file. This "Service. bal" file will contains the REST to gRPC mapping and logic and functions for communication with gRPC back endpoint.

After these steps are completed, micro-gateway will be provide full gRPC support for users.

**Comment by praminda** [comment]
We are hoping to update this feature with a new design. @VirajSalaka Can you provide an update?

**Comment by VirajSalaka** [comment]
Initially, the plan is to provide the grpc support where both backend server and client endpoint are grpc. The microgateway will act as a proxy and will handle the gateway functionalities like authentication, authorization and rate-limiting. After that, we will be considering the variation mentioned above, where the client is REST and the server is grpc. 

We can serve the grpc traffic as HTTP/2 traffic since grpc is built on top of HTTP/2 protocol. By using "Content-Type" header we can figure out whether the coming request is grpc or not. Depending on that we can decide the response the gateway should send to the client in case of the occurance of error from filters. The applying filters would be authentication, authorization and rate-limiting. Load balancing and Failover endpoints can also be supported.

![grpcProxy](https://user-images.githubusercontent.com/17596317/63223000-ab1ffc00-c1cc-11e9-8a63-5d6cc9061375.png)

Rate limiting can be provided based on "Requests per second/minute/hour" as it is already provided for REST calls. Throttling for streams (bytes per some time unit etc) will not be provided at the moment as there is no support for any sort of bandwidth control in ballerina.

**Comment by VirajSalaka** [comment]
Now we need to decide the way the user can provide the inputs like grpc server endpoints, security type, scopes and rate-limiting policies. To follow the developer first approach, the user should be able to provide the microgateway configurations declaratively. To facilitate that, we are planning to introduce some service and method extensions to the protobuf file in which the service is defined.

This is the file where wso2 specific extensions are defined. 

>syntax = "proto3";
>package service;
>import "google/protobuf/descriptor.proto";
>
>//service level extensions
extend google.protobuf.ServiceOptions {
  string x_wso2_basePath = 50001;
  Endpoint x_wso2_production_endpoints = 50002;
  Endpoint x_wso2_sandbox_endpoints = 50003;
  Security x_wso2_security = 50004;
  string x_wso2_rate_limit = 5005;
}
>
>//method level extensions
extend google.protobuf.MethodOptions {
	Endpoint x_wso2_method_production_endpoints = 50006;
  	Endpoint x_wso2_method_sandbox_endpoints_m = 50007;
  	Security x_wso2_method_security = 50008;
  	string x_wso2_method_rate_limit = 50009;
}
>
>
>//to define endpoints
>message Endpoint {
	repeated Url urls = 1;
	EndpointType type = 2;
}
>
>message Url {
	string url = 1;
}
>
>enum EndpointType {
	HTTP = 0;
	LOADBALANCE = 1;
	FAILOVER = 2;
}
>
>
>//to define security schema
>message Security {
	SecurityType type = 1;
	repeated Scope scopes = 2;
}
>
>message Scope {
	string scope = 1;
}
>
>enum SecurityType {
	NONE = 0;
	BASIC = 1;
	OAUTH2 = 2;
	JWT = 3;
}

This will be added as a protobuf file named "wso2_lib.proto" to the project directory during `micro-gw init <project>`.  

Then the user has to modify the proto file ( which includes the service definition ). This is a sample user-modified file. 

	syntax = "proto3";
	package service;
	import "google/protobuf/wrappers.proto";
	import "lib/lib.proto";

	//service
	service HelloWorld {

	  //method
	  rpc hello (google.protobuf.StringValue) returns (google.protobuf.StringValue) {
    
		//method level security 
		option (x_wso2_method_security) = {
			type : OAUTH2
			scopes {
				scope: "scope_1"
			}
			scopes {
				scope: "scope_2"
			}
			x_wso2_method_rate_limit = "10kPerMin"
		};
	  }

	  //basepath
	  option (x_wso2_basePath) = "/pizzashack";

	  //production endpoints
	  option (x_wso2_production_endpoints) = {
		type: FAILOVER
		urls {
			url : "http://localhost:9091"
		}
		urls {
			url : "http://localhost:9092"
		}
	  };    

	  //service level security
	  option (x_wso2_security) = {
		type : OAUTH2
		scopes {
			scope: "scope_1"
		}   
	  };    
	}

**Comment by VirajSalaka** [comment]
As we discussed offline, these are the finalized design decisions.

1. For the moment, we will be considering rate limiting based on "requests per second". No control over bandwidth will be provided in the streaming case.
2. Basepath concept is not required as it is less practical in grpc case. 
3. Method level production/sandbox endpoints, security also needs to be removed as it less practical in grpc scenario, but the developer should have the capability to provide method-level scopes.
4. Under the Endpoints object, term "Urls" should be changed to "endpoint".

**Comment by VirajSalaka** [comment]
This is the revised protobuf file which includes the microgateway specific extensions.

	syntax = "proto3";
	package service;

	import "google/protobuf/descriptor.proto";

	//service level extensions
	extend google.protobuf.ServiceOptions {
	  Endpoints x_wso2_production_endpoints = 50001;
	  Endpoints x_wso2_sandbox_endpoints = 50002;
	  repeated Security x_wso2_security = 50003;
	  string x_wso2_rate_limit = 50004;
	  string x_wso2_scopes = 50005;
	}

	//method level extensions
	extend google.protobuf.MethodOptions {
	  	string x_wso2_method_rate_limit = 50006;
	  	string x_wso2_scopes = 50007;
	}


	//to define endpoints
	message Endpoints {
		repeated Endpoint urls = 1;
		EndpointType type = 2;
	}

	message Endpoint {
		string url = 1;
	}

	enum EndpointType {
		DEFAULT = 0;
		FAILOVER = 1;
	}

	enum Security {
		NONE = 0;
		BASIC = 1;
		OAUTH2 = 2;
		JWT = 3;
	}

If there are multiple scopes, user needs to provide that as comma separated values.
