### ISSUE TITLE
Microgateway 3.2.0 project does not build when folder path contains space

### ISSUE THREAD

**Issue by amiladeshapriya** [wso2/product-microgateway#2866]
### Description:
Microgateway project in the Windows environment does not get build when the path where the Microgateway toolkit binaries are present contains spaces in the folder names.

### Steps to reproduce:
1. Configure Microgateway 3.2.0 Toolkit U2 level 19 in the Windows environment
2. Add a space into the path where the Microgateway 3.2.0 Toolkit binary presents.(eg: D:\Program Files\space in foldername\apps\ApiMicrogatewayService\22.1.5\toolkit)
3. Initiate a new API Project (eg: Sample petstore project)
4. Build the project

### Results
The project will not get build.

### Affected Product Version:
Microgateway Toolkit 3.2.0 

### Environment details (with versions):
- OS: Windows

**Comment by pubudu538** [comment]
Fixed!
