### ISSUE TITLE
RabbitMQ type property is not available in message context

### ISSUE THREAD

**Issue by DaniduWijendra** [wso2/product-microgateway#2911]
### Describe your problem(s)
We need to use an AMQP transport parameter called rabbitmq.message.type[1]  (Application-specific message type, e.g. "orders.created") and the parameter is not available in WSO2 AMQP transport parameter [2]. 

[1] https://www.rabbitmq.com/publishers.html#message-properties
[2] https://docs.wso2.com/display/EI660/RabbitMQ+AMQP+Transport#RabbitMQAMQPTransport-RabbitMQAMQPtransportparameters

### Affected Product Version
Enterprise Integrator 6.6.0

**Comment by pubudu538** [comment]
This issue should be created in Product-EI. https://github.com/wso2/product-ei/issues/5566
Could not transfer the issue. So created a new issue in product-ei
