### ISSUE TITLE
Can't deploy an istio injected Choreo connect deployment to an Istio-enabled Kubernetes cluster

### ISSUE THREAD

**Issue by lathlk** [wso2/product-microgateway#3001]
### Describe your problem(s)
The field spec.template.spec.automountServiceAccountToken is set to false in templates/gateway-runtime-deployment.yaml of Choreo connect helm chart. This field instructs Kubernetes not to mount the ca.crt volume to the deployment and hence causes the issue.

### Describe your solution
Set the said field to true by default, or make it available to edit in values.yaml.

Suggestion: It is better if we can make the service port of the gateway runtime editable in the helm chart. It only allows HTTPS by default and is not useful for the Istio injection cases, as Istio assumes the workload only handles plain HTTP traffic.

---
#### Suggested Assignees:
@renuka-fernando

**Comment by renuka-fernando** [comment]
Released Choreo Connect helm charts with the required changes
- Chart version 1.0.0.5 for Choreo Connect 1.0.0
- Chart version 1.1.0.4 for Choreo Connect 1.1.0
