### ISSUE TITLE
Init and Build commands fail when the installation path contains a space

### ISSUE THREAD

**Issue by kaushi2142** [wso2/product-microgateway#3011]
### Description:
When there is a space in the path of the micro-gateway product installation directory in Windows, the init and build commands fail with below error:
`else was unexpected at this time`
The following error message was also observed in some Windows instances for the init command:
`The system cannot find the path specified`

### Steps to reproduce:

1. Download the WSO2 API Microgateway toolkit Windows distribution (wso2am-micro-gw-toolkit-windows-3.2.0) and extract the archive to a directory that contains a space in the path (Ex: E:/Program Files)
2. Initialize a sample project [1]
3. The above-mentioned errors will be displayed in the console

[1] https://mg.docs.wso2.com/en/latest/getting-started/quick-start-guide/quick-start-guide-docker/#step-1-generate-an-executable-using-wso2-api-microgateway-toolkit

### Environment details (with versions):
- OS: Windows
- Client:
- Env (Docker/K8s):

---

**Comment by ashera96** [comment]
Closing since all PRs are merged
