### ISSUE TITLE
Create API artifacts directory in adapter docker image

### ISSUE THREAD

**Issue by NomadXD** [wso2/product-microgateway#3019]
### Describe your problem(s)
https://github.com/wso2/kubernetes-microgateway/issues/61
### Describe your solution
Add `RUN mkdir -p /home/wso2/artifacts/apis` to adapter Dockerfiles

### How will you implement it
Add `RUN mkdir -p /home/wso2/artifacts/apis` to adapter Dockerfiles

---
#### Related Issues:
https://github.com/wso2/kubernetes-microgateway/issues/61

**Comment by renuka-fernando** [comment]
Let's do the same for enforcer dropins dir
