### ISSUE TITLE
Upgrade envoy proxy version from `v1.20.2` to `v1.24.1`

### ISSUE THREAD

**Issue by NomadXD** [wso2/product-microgateway#3043]
### Problem

OpenTelemetry tracer not available in envoy proxy version `v1.20.2`.

### Solution

Upgrade envoy proxy version from `v1.20.2` to `v1.24.1` to add OpenTelemetry tracing support.

**Comment by pubudu538** [comment]
Should upgrade to latest Envoy Ubuntu docker image as alpine image is deprecated.
