### ISSUE TITLE
[Choreo-Connect][1.0.0] Apply throttling on /token endpoint

### ISSUE THREAD

**Issue by ruwanmadhusanka** [wso2/product-microgateway#3060]
### Description

Not able to apply the throttling policy on the /token endpoint in Choreo connect.

### Steps to Reproduce

-

### Version

1.0.0

**Comment by slahirucd7** [comment]
ETA information for the fix will be as follows.

Product: Choreo Connect 1.0.0
Public git issue: N/A
Best Case Estimate: 13.09.2022
Most Likely Estimate: 16.09.2022
Worst Case Estimate: 20.09.2022

**Comment by slahirucd7** [comment]
The feature introduced with the below PR:
https://github.com/wso2-support/product-microgateway/pull/280

**Comment by slahirucd7** [comment]
Closing this issue since the above mentioned PR is merged now.
