### ISSUE TITLE
[Websockets] APIs with topics not working properly

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-microgateway#3062]
### Description

If we deploy a websocket API with a couple of topics and try to invoke them using the topics, gateway doesn't response properly (either hangs or gives a 400 response)

### Steps to Reproduce

1. Create a websocket API with context: postman, version: 1.0.0, endpoint: `wss://ws.postman-echo.com/raw` as the endpoint URL and deploy in CC.
2. Try to invoke after subscribe/keygen: `wscat -c wss://localhost:9095/postman/1.0.0 -H "Authorization: Bearer $TOKEN" -n`
3. This can be invoked properly
4. Now create another websocket API with context: postmantopics, version: 1.0.0, endpoint: `wss://ws.postman-echo.com`
5. Try to invoke after subscribe/keygen: `wscat -c wss://localhost:9095/postmantopics/1.0.0/raw -H "Authorization: Bearer $TOKEN" -n`
6. This ends up with a 400 response.

If we use a ballerina service as the endpoint and try the same scenario above, the CC hangs without giving a response in the 2nd case.

**ws-server.bal**
```ballerina
import ballerina/io;
import ballerina/websocket;
service /echo on new websocket:Listener(7070) {
   resource function get .()
                     returns websocket:Service|websocket:Error {
       return new WsService();
   }
}

service class WsService {
    *websocket:Service;
    remote function onTextMessage(websocket:Caller caller,
                                 string text) returns websocket:Error? {
        io:println("\ntext message: " + text);
        return caller->writeTextMessage("You said: " + text);
    }
}
```

**Running:**
`bal run ws-server.bal`

**Endpoint:** ws://<host>:7070/echo

### Version

1.1.0

**Comment by Amila-Rukshan** [comment]
I checked the given scenario, when we doing steps 4 and 5,  got the path logs as below:
```
[2022-09-08T06:07:36.335Z] 'GET /postmantopics/1.0.0/raw / HTTP/1.1' 502 - 0 150 2170 - '-' '-' '88164b83-4090-4a66-bbe4-cf7ffde65002' 'ws.postman-echo.com' '3.225.70.24:443'
```
`/` means we are not passing `/raw` path to the actual backend.


Then I add mapping to the topic from `/raw` to `/raw` as described [here](https://apim.docs.wso2.com/en/latest/design/create-api/create-streaming-api/create-a-websocket-streaming-api/#step-2-configure-the-topics):
```
[2022-09-08T06:32:59.689Z] 'GET /postmantopics/1.0.0/raw /raw HTTP/1.1' 101 DC 51 29 4621 - '-' '-' '1383ec06-30ea-4783-be78-acd4b07aaaab' 'ws.postman-echo.com' '3.225.70.24:443'
```
and it worked.

**Comment by pubudu538** [comment]
Closing the issue as the functionality works properly.
