### ISSUE TITLE
Enable Choreo Connect with compression filter support

### ISSUE THREAD

**Issue by slahirucd7** [wso2/product-microgateway#3104]
### Problem

Currently Choreo Connect allows to send data only in RAW format.
Therefore HTTP payload size sending with requests is high due to this.
If we can send compressed data with HTTP requests it will impact the performance as well.

### Solution

Enable Choreo Connect with the Enovy compression filter support.
With the the above compression filter support we can enable Choreo Connect to send compressed data.

### Implementation

- Add compression filter support to Adapter and Configure the Router through adapter.
- Write test cases to cover the relevant scenarios.

**Comment by pubudu538** [comment]
Added with https://github.com/wso2/product-microgateway/pull/3105
