### ISSUE TITLE
Update base images relevant to the Adapter and Enforcer

### ISSUE THREAD

**Issue by slahirucd7** [wso2/product-microgateway#3114]
### Description

Since there are new base images for the,
**Adapter** -> https://hub.docker.com/_/alpine/tags
**Enforcer** -> https://hub.docker.com/r/adoptopenjdk/openjdk11/tags?page=2&name=jre-11.0.16.1_1
we can replace the existing images with latest versions.

Additional to that, new images mentioned above latest Apple Silicon processors.
Therefore it enables to run CC integration tests with less configurations.

**Comment by pubudu538** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/3188
