### ISSUE TITLE
JWKS route isn't created unless /testkey endpoint is enabled

### ISSUE THREAD

**Issue by jhivandebenoit** [wso2/product-microgateway#3147]
### Problem

Adapter checks whether the /testkey endpoint is enabled before creating the JWKS route instead of whether the JWKS generator is enabled.

### Solution

Creating the  JWKS route when JWT generator is enabled.

**Comment by pubudu538** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/3144
