### ISSUE TITLE
[Docs] Update helm resource links with the new version

### ISSUE THREAD

**Issue by suksw** [wso2/product-microgateway#3155]
### Description

The docs (https://github.com/wso2/docs-apim/pull/6420/files) in master branch currently points to https://github.com/wso2/kubernetes-microgateway/tree/1.1.x/helm/choreo-connect where the version is 1.1.x. This must be updated once a new branch is created in the https://github.com/wso2/kubernetes-microgateway repo for a new release.

**Comment by renuka-fernando** [comment]
This is completed with https://github.com/wso2/docs-apim/pull/6921
