### ISSUE TITLE
Update dependency check maven plugin version

### ISSUE THREAD

**Issue by slahirucd7** [wso2/product-microgateway#3186]
### Description

In the existing version of the `org.owasp:dependency-check-maven` below error comes when scanning the JARS,
![image](https://user-images.githubusercontent.com/40932779/211996238-a0bf7185-fe05-4606-9f41-ada2eea12d43.png)
By updating to the latest version above error will resolve.

**Comment by pubudu538** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/3177
