### ISSUE TITLE
Revise suppression file relevant to the Enforcer

### ISSUE THREAD

**Issue by slahirucd7** [wso2/product-microgateway#3195]
### Description

Enforcer's suppression file contains some entries since CC 1.1.0 version and there could be possibilities to update the
file considering the latest dependency versions. After adding latest versions, it's possible to reduce the entry count
in the file.

Related to: https://github.com/wso2/product-microgateway/issues/3190

**Comment by pubudu538** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/3209
