### ISSUE TITLE
Docker ARM image for Choreo Connect Components

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#3196]
### Description

Push docker images with the arch types: ARM and AMD

### Version

1.2.0-m1

### Related Issues

https://github.com/wso2/product-microgateway/issues/2412

**Comment by pubudu538** [comment]
Existing images work in ARM machines. Hence we no longer need this.

**Comment by pubudu538** [comment]
Recent change to the Enforcer Image - https://github.com/wso2/product-microgateway/pull/3226
