### ISSUE TITLE
Configuration file cannot take values with special character "#" 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#321]
**Description:**
micro-gw.conf values cannot be included "#". The reason behind this probably can be that it is read "#sometext" as a comment.

**Steps to reproduce:**
e.g.
In micro-gw.conf if we have a password that contains "#" special character as follows.

[keyManager]
password="pa#sword"

**Comment by praminda** [comment]
@AmaliMatharaarachchi Can you specify the product version for the issue?

**Comment by AmaliMatharaarachchi** [comment]
version 2.6.0 
But I think it is applicable to every other version which uses TOML configuration files.

**Comment by Rajith90** [comment]
This seems to be a limitation in the toml format

**Comment by Rajith90** [comment]
https://github.com/ballerina-platform/ballerina-lang/issues/9778

**Comment by praminda** [comment]
Postponing the fix until ballerina team issues a fix for this

**Comment by praminda** [comment]
This issue has been fixed in ballerina. Should be able to resolve this once the ballerina 1.0.0 migration is complete.

**Comment by praminda** [comment]
Ballerina 1.0.0 migration can be tracked in #717

**Comment by praminda** [comment]
@AmaliMatharaarachchi Shall we try this now. Should be fixed with the ballerina upgrade efforts

**Comment by praminda** [comment]
Ballerina is now upgraded to 1.1.x and No longer reproducible in master branch as of 4aa807bc
