### ISSUE TITLE
Restructuring the Microgateway Project Folder Structure and Command Execution to Support Multiple APIs

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#325]
Description:
There is a requirement to add the following features to the Microgateway in Future. 
Add multiple APIs to a project
Publish APIs from Microgateway to Store
Support fine-grained endpoint configurations based on resource level.

- Ex. GET menu - <IP_1>
- POST order - <IP_2>

Currently, when the “micro-gw setup” command is executed, it fails if the project already exists and therefore we have no mechanism to add another API to the same project. 

Considering the developer first approach, the current folder structure of the project is as follows.

Command: 

- **micro-gw setup <project_name> -oa <path_to_swagger_file> -e <endpoint>**

Folder Structure:
<img width="320" alt="Screen Shot 2019-03-12 at 1 52 13 PM" src="https://user-images.githubusercontent.com/17596317/54185085-2f5bae00-44ce-11e9-92a9-4c7f3e7cd1e0.png">

**Proposed Flow of the Process:**

_setup command_

- **micro-gw setup <project_name>**

This is allowed and it will create the following folder structure
<img width="241" alt="Screen Shot 2019-03-12 at 1 54 24 PM" src="https://user-images.githubusercontent.com/17596317/54185233-8792b000-44ce-11e9-8ea0-f75bcba3df7c.png">

- **micro-gw setup <project_name> -oa <path_to_swagger_file> -e <_endpoint>**

Folder structure will look like this,

<img width="301" alt="Screen Shot 2019-03-12 at 1 54 31 PM" src="https://user-images.githubusercontent.com/17596317/54185246-8eb9be00-44ce-11e9-97d6-dd5309950b4d.png">

As you can see there is another folder added API_files. We will read the swagger and name accordingly. The version number is identified by reading the swagger file. 

 The purpose behind saving the swagger is to publish the API to the store from microgateway. Metadata file holds the metadata related to API. Other than that the endpoint will be added to the routes.yaml with the corresponding api_name and the version number.  This endpoint is the basic endpoint for the API. ( compare the difference with add-route command)

	
More importantly, there will not be a code generation operation at the “setup” phase. In other words, there won’t be a “pizzashackAPI_1.0.0.bal” file during this phase. 

			
_Set-project command_ 
	
- **micro-gw set-project <project-name>**

Along with this new structural implementation, there will be a lot of additional commands related to the project (mentioned in below sections). The developer will have to mention the project name within each and every command. This command removes that burden from the developer.

_add-api command_

As mentioned earlier, A project can either be “setup” with just one API definition or without any API definition. To add more APIs, we need to introduce the add command.

- **micro-gw add-api  -oa <path_to_swagger_file> -e endpoint**

As in the setup command, we will be continuing with api_name provided in the swagger.

consider the following command, (in this case API name is DrinksAPI
			micro-gw add-api  -oa drinks_swagger.json -e some_endpoint
	

<img width="294" alt="Screen Shot 2019-03-12 at 1 54 55 PM" src="https://user-images.githubusercontent.com/17596317/54185267-98dbbc80-44ce-11e9-8cf2-12c0c8bd9a9f.png">

It can be observed that still there is no code generation (bal file generation) has happened. 

_Add-route command_
	

- **micro-gw add-route -a <user_provided_api_name> -v  <_version>  -m <http_method> -r <resource_name> -e <_endpoint>**

We have added a basic endpoint while setting up the API. This command is to provide separate endpoints based on resource level. <http_method> would be something like “GET”, “POST” etc. and resource_name would be something like “menu”. These details would be added to the routes.yaml as well. 

_Build command_

- **micro-gw build <project_name>**

This is the same existing command. The difference is that code generation and compilation both happen at this phase. (Previously code generation happened at the “setup”  phase.) In this case, pizzashackAPI_1.0.0.bal file and drinksAPI_1.0.0.bal both will be saved in the src directory. Target directory will have all the components which will be required to run the microgateway. 

The folder structure will look like this,
<img width="308" alt="Screen Shot 2019-03-12 at 1 55 12 PM" src="https://user-images.githubusercontent.com/17596317/54185302-aa24c900-44ce-11e9-95c2-25584f35d4d1.png">

_delete_api command_

- **micro-gw delete-api -a <API_name> -v <API_version>**

	Since we are supporting add_api command, we need to support delete_api command as well. 

_list_apis command_
	

- **micro-gw list_apis** 

	This will list down all the APIs with their available versions. (API name would be the name of that folder corresponding to the API) 

_register command_

- **micro-gw register -a <API_name> -v <API_version>** 

	This command will publish the API in Store. Since we have the swagger file saved in the directory, we can use the Publisher API.

The command names and the arguments are not finalized yet. But this is the expected way to accomplish the task. 

The structure of routes.yaml file looks like this,
<img width="617" alt="Screen Shot 2019-03-12 at 12 43 02 PM" src="https://user-images.githubusercontent.com/17596317/54184163-f4f11180-44cb-11e9-9a87-bd6d371a86d5.png">

User can define the endpoint for the API in three different levels,

- API level
- Resource level w/o HTTP-method
- Resource level with HTTP-method

Further this routes file has capability to store any mediation associated with a certain resource.

Suggested Labels:
Docs has Impact, Feature

**Comment by VirajSalaka** [comment]
These would be the revised set of commands. 
1. **micro-gw setup <project_name>**

Project Structure will be created under the provided project name.


2. **micro-gw setup <project_name> -oa <path_to_swagger> -e <endpointConfig> -b <basePath>**

In this case, the user has to provide the basePath if the OpenAPI spec is 3.0 or OpenAPI spec is 2.0 and basePath is not included without basepath. EndpointConfig is the global endpoint for the API. No ballerina code generation happens during this. We create the folder structure and copy the swagger file into the relevant directory. In the meantime, we will be updating the routes.yaml with global configuration. basePath will be saved in the routes.yaml file.
 
API_ID also will be generated using the hash value of “API_name:API_version” concatenated string. And the folder in which the swagger is saved will be named after that API_ID.
 
3. **micro-gw set project <project_name>**

Since there can be so many projects, the user can specify the project he is currently working on so that he does not have to mention project name for each and every command repeatedly.

4. **micro-gw add api -oa <path_to_swagger> -e <endpointConfig> -b <basePath>**

This method adds a new API to the project. It is the same as the above-mentioned setup command.

5. **micro-gw list apis**

This command will list the following fields.
api_id  |  api_name | api_version | basePath

6. **micro-gw update api -a <API_ID>  ( -e <endpointConfig> -b <basePath> )**

The user can either update the endpointConfig, or update the basepath or do both operations using this command.

7. **micro-gw list resources -ai <API_ID>**

This will list all the resources available for a given API_ID. The resources will be read using the swagger file. Resource_id would be the hash value of the “API_name:API_version:Resource_name: Method_name”.

When there is a resource like /order/{order_id} we will have to keep a common way to define the inner variable.
 
resource_name | method_name | resource_id

8. **micro-gw add route -ri <resource_id> -e <endpointConfig>**

This will add a new endpoint configuration for the given resource.  

9. **micro-gw desc route -ri <resource_id>**

This will output the endpoint configuration for the given resource. Following properties will be shown.
Endpoint_type, endpoint_security, endpoint_list for PROD and SAND environments.

10. **micro-gw update route -ri <resource_id> -e <endpointConfig>**

Update the route for the resource with a different endPointConfig.

11. **micro-gw delete route -ri <resource_id>**

Delete the route for given resource_id.

12. **micro-gw build**

This will generate the ballerina code, compile the ballerina code and after all, we can launch the project.

And the structure of the routes.yaml would be as follows.
![image](https://user-images.githubusercontent.com/17596317/56015037-41bb4880-5d15-11e9-8eac-0c02709a3bff.png)

**Comment by praminda** [comment]
Fix included in #325
