### ISSUE TITLE
 "Resource forbidden" error when invoking API using a valid third party JWT token

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-microgateway#329]
**Description:**
When invoking an API resource using a valid third party JWT token a "Resource forbidden" error is thrown

**Affected Product Version:**
Micro-gateway after Ballerina upgrade. 

**Steps to reproduce:**
- Generate a valid JWT from a third party
- Use the JWT token and invoke and API

**Comment by Rajith90** [comment]
Fixed by : https://github.com/wso2/product-microgateway/pull/346/

**Comment by Rajith90** [comment]
#346 Merged to master
