### ISSUE TITLE
Rate-limiter shows a request count for unlimited value

### ISSUE THREAD

**Issue by slahirucd7** [wso2/product-microgateway#3290]
### Description

We can define rate-limit as unlimited in below format.

```
{
        "id": "",
        "target": "/empId1",
        "verb": "DELETE",
        "authType": "Application \u0026 Application User",
        "throttlingLimit": {
          "requestCount": -1,
          "unit": "MINUTE"
        },
        "scopes": [],
.
.
.

```

then, after deployment, when retrieving the defined RL policies rate-limiter assigns below request count to the operation.
`Default.org_carbon.super.vhost_localhost.path_/rl-1/empId1.method_DELETE: unit=MINUTE requests_per_unit=4294967295, shadow_mode: false`

**Comment by renuka-fernando** [comment]
Let's add the rate-limiter in the Dev profile of the maven project as well. So rate-limiter will be built on `mvn clean install` command as well.

**Comment by slahirucd7** [comment]
The issue sorted with the below PR:
https://github.com/wso2/product-microgateway/pull/3306
