### ISSUE TITLE
Post Method for Token Call Is Missing

### ISSUE THREAD

**Issue by Abshan** [wso2/product-microgateway#3292]
### Problem

Hi Team,

In the earlier versions of the MGW toolkit 3.2.0, we can generate a token for the microgw by making a call like this

`curl -L -X POST 'https://api.mgw.com/apikey' -H 'Authorization: Basic xxxxxxxxx' -H 'Content-Type: application/x-www-form-urlencoded' --data- urlencode 'grant_type=client_credentials'`

However, in the later versions, we found out that the POST call is no longer available (method not allowed), and it has been changed to a GET call. With the below GET  call, we get a token with which we can consume the API.

`curl -L -X GET "https://api.mgw.com/apikey" -H "Authorization: Basic xxxxxxxxx" `

However, when there are multiple clients calling the system for a token, it is not an easy task to make the change on each client side. 

### Solution

Add the POST method to the list of supported methods when calling the token endpoint.

### Suggested Labels

MGW

**Comment by npamudika** [comment]
Fixed by https://github.com/wso2/product-microgateway/pull/3308
