### ISSUE TITLE
The following parsing error logs can be seen for the compression filter

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-microgateway#3295]
### Description

The following logs can be seen

choreo-connect-with-apim-adapter-1   | 2023-03-06 11:08:43 ERRO [compression_filter.go:55] - [envoyconf.getGzipConfigurations] [-] Error while parsing the gzip configuration value for the memory level: error occurred while processing gzip configuration value [severity=Minor error_code=2235]
choreo-connect-with-apim-adapter-1   | 2023-03-06 11:08:43 ERRO [compression_filter.go:65] - [envoyconf.getGzipConfigurations] [-] Error while parsing the gzip configuration value for the window bits: error occurred while processing gzip configuration value [severity=Minor error_code=2236]
choreo-connect-with-apim-adapter-1   | 2023-03-06 11:08:43 ERRO [compression_filter.go:75] - [envoyconf.getGzipConfigurations] [-] Error while parsing the gzip configuration value for the compression level: error occurred while processing gzip configuration value [severity=Minor error_code=2237]
choreo-connect-with-apim-adapter-1   | 2023-03-06 11:08:43 ERRO [compression_filter.go:85] - [envoyconf.getGzipConfigurations] [-] Error while parsing the gzip configuration value for the chunk size: error occurred while processing gzip configuration value [severity=Minor error_code=2238]

### Steps to Reproduce

Start CC Adapter.

### Version

1.2.0-beta

**Comment by renuka-fernando** [comment]
Completed with #3294
