### ISSUE TITLE
Update the log4j version in product microgateway to 2.17.2.

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-microgateway#3338]
### Problem

We need to update the log4j version in the product microgateway to 2.17.2.

### Solution

N/A

### Suggested Labels

wso2am-micro-gw-3.2.0

**Comment by Tharsanan1** [comment]
The public fix is not applicable as the latest version uses a higher log4j version: https://github.com/wso2/product-microgateway/blob/21e4cad40b45375b3152dffe3c896644175b03bd/pom.xml#L703
