### ISSUE TITLE
Query Parameters With Curly Brackets Are Not Working In MGW-3.2

### ISSUE THREAD

**Issue by Abshan** [wso2/product-microgateway#3374]
### Description

Hi Team,

When there are curly brackets in the query parameter, the invocation fails with the following error message,

`illegal character in query at index 72: /api/sample/test/value?sampleVal={%22name%22:%22abshan%22}`

For example, if we invoke an API hosted in MGW using the following curl command, the above-mentioned error can be observed,

`https://localhost:8243/api/sample/test/value?sampleVal={%22name%22:%22abshan%22}`

As you can see in the above query parameter, { } have not been encoded, and yet it works fine with APIM, but not with Micro-Gateway. And, as per the [WHATWG standard](https://url.spec.whatwg.org/), the { and } are safe and don't need explicit encoding.

### Steps to Reproduce

- The issue can be easily reproduced by invoking an API hosted in MGW, with a query parameter which includes curly brackets.

### Version

3.2.7

### Environment Details (with versions)

MGW-3.2.7

### Suggested Labels

APIM MGW

**Comment by npamudika** [comment]
Closing as this is fixed via https://github.com/wso2/product-microgateway/pull/3393
