### ISSUE TITLE
Global timeout setup for Wso2 MicroGateway

### ISSUE THREAD

**Issue by VinulaUthsara** [wso2/product-microgateway#3387]
### Description

We tried to implement the timeout configuration that is mentioned in the documentation [1] for APIM 3.2.0.

For that we add the following configuration in the yaml file

x-wso2-production-endpoints:
Urls: 
advanceEndpointConfig:
timeoutInMillis:200000
type: http

Then we proceed to import the API into the publisher but when we check the API definition there, this property is not appearing.
We tried the same locally and was able to obtain the same result. We also observe this is happening in APIM 3.0.0 too.

[1] https://mg.docs.wso2.com/en/latest/how-tos/endpoints/resiliency/retry-and-timeout-configs/#timeout-config

### Steps to Reproduce

1. Edit the swagger file with the following configurations:
x-wso2-production-endpoints:
Urls: <url> 
advanceEndpointConfig:
timeoutInMillis:200000
type: http
2. Import the API to APIM 3.0.0
3. Edit the swagger definition and observe the added configuration is not available.

### Version

3.0.0, 3.2.0

### Suggested Labels

3.0.0

**Comment by HeshanSudarshana** [comment]
Closing the issue since the public PR is merged.
