### ISSUE TITLE
MicroGateway ballerina filter getXmlPayload() removes the starting CRLF character from the first multipart boundary

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/product-microgateway#3403]
### Description

 The `CRLF` characters at the beginning of the body are being removed when building the payload via the ballerina filter.

### Steps to Reproduce

- Deploy a sample API in the microgateway.
- Configure the below as the endpoint of the sample API.
`http://localhost:8889
`
**Setting up the backend.**
- Create a file name **docker-compose.yaml**lfile including the below code.
```
version: "3.7"
services:
  http-echo:        
    hostname: http-echo        
    image: mendhak/http-https-echo        
    environment:        
     - HTTP_PORT=8889        
    ports:
     - "8889:8889"
```
- Execute the below command inside the directory where the docker-compose.yaml file is stored.
`docker-compose up -d
`
- Execute the below command tp tail the logs of the backend server
`docker-compose logs -f
`- Add a custom filter to the microgateway project.
- Copy the following code to the **soap_gdc_filter.bal** file and place it inside the /extensions directory:
```
import ballerina/http;
import wso2/gateway;

xmlns "http://****" as gdc14;

string CONFIG_SOAP_GDCXML_CONTEXT = "usr_soap_gdcxml_context";
string CONFIG_ENVIRONMENT = "usr_environment";
string CONFIG_ENVIRONMENT_ID = "usr_environment_id";

string REQUEST_CONTENT_TYPE = "requestContentType";
string GDC_REQUEST_MESSAGE_ID = "gdcRequestMessageId";
string GDC_REQUEST_HEADER = "gdcRequestHeader";

string ERROR_RESPONSE_CODE = "error_response_code";

// Filter for the Soap GDC XML API
// 
public type SoapGdcFilter object {

    public function filterRequest(http:Caller caller, http:Request request, http:FilterContext context) returns boolean {

        if (context.attributes.hasKey(gateway:SKIP_ALL_FILTERS) && <boolean>context.attributes[gateway:SKIP_ALL_FILTERS]) {
            return true;
        }   

        xml|error payload = request.getXmlPayload();
        
        return true;
    }

    public function filterResponse(http:Response response, http:FilterContext context) returns boolean {
        return true;
    }

}; // SoapGdcFilter
```

- Add the below configuration to the deployment-config.toml residing under the /conf directory:

```
[[filters]]
    name = "SoapGdcFilter"
    position = 1
```

- Configure SOAP UI to send a post request with MTOM enabled.

- Invoke the API using the SOAP UI and you will be able to observe that the **CRLF** ("/r/n" ) character is being missed in the first multipart boundary when sending the request to the backend server. Check the backend server's log.
`"body": "------=_Part_32_1103335936.1688648631996\r\nContent-Transfer-Encoding: 8bit\r\ncontent-type:
`- It should include the CRLF character as below,
`"body": "\r\n------=_Part_32_1103335936.1688648631996\r\nContent-Transfer-Encoding: 8bit\r\ncontent-type:
`

### Affected Component

APIM

### Version

wso2am-micro-gw-3.2.0

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/3402
