### ISSUE TITLE
Error "file is too large" occurs when building Micogateway project with large number & size of swaggers

### ISSUE THREAD

**Issue by chashikajw** [wso2/product-microgateway#3457]
### Description

Microgateway throws "file is too large" error when building a microgateway project with large number & size of swaggers

### Steps to Reproduce

1. Execute `export _JAVA_OPTIONS="-Xms256m -Xmx2048m"` to increase the memory allocated to the JVM

2. Add large size of swagger files to a micrigateway project and build it.

You will see the file is too large issue when building the project

### Version

Microgateway 3.2.0

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/product-microgateway/pull/3461 by upgrading the Ballerina version to 1.2.47 which includes the fixes from the Ballerina side.
