### ISSUE TITLE
Update Distributed Throttling Document

### ISSUE THREAD

**Issue by sanjeewa-malalgoda** [wso2/product-microgateway#360]
**Description:**
Please find attached distributed throttling related document and update document accordingly.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sanjeewa-malalgoda** [comment]
[Distributed Throttling In Micro-gateways.pdf](https://github.com/wso2/product-microgateway/files/3027813/Distributed.Throttling.In.Micro-gateways.pdf)

**Comment by Rajith90** [comment]
Public documentation can be found here : https://docs.wso2.com/display/MG270/Distributed+Throttling+in+the+API-M+Microgateway

Thanks @shaniR for updating the documentation
