### ISSUE TITLE
Support "micro-gw set project <project name>" command

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#402]
**Description:**
The requirement of this command is to avoid the burden of specifying the project name repeatedly throughout all the commands.

The challenge here is to save the project directory after the user has set it up. There are two available options.

1. Save as an environmental variable 
2. Persist the workspace directory in a separate file inside the Microgateway tools distribution.

If we choose the first option over the second, the environment variable will not be available once the machine shuts down. When it comes to the second approach,  the file would be removed if we update the toolkit distribution. Then the existing workspace directory will not be recognized anymore. 

**Suggested Labels:**
Discussion

**Related Issues:**
https://github.com/wso2/product-microgateway/issues/325

**Comment by praminda** [comment]
Merged to master #325
