### ISSUE TITLE
Change the structure of resources section in routes.yaml 

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#403]
**Description:**
As mentioned in https://github.com/wso2/product-microgateway/issues/325, currently the structure of resources section is a flat architecture (every resource is directly accessible via the resource_id). Via this approach, there would be a resource_id for each and every resource if a specific endpoint configuration is provided for that resource.

The limitation in this approach is to allow users to define the endpoint configuration based on the resource name ignoring the rest operation. For example, the user needs to specify the endpoint configuration for all available methods under the resource name "/menu". Under the current structure, it would be required to keep another separate record for "/menu" without any operation. In this approach, if we need to find the endpoint configuration for the resource "/menu GET" during the code generation process, first we will have to search for exactly matching endpoint configuration, if not "/menu" 's endpoint configuration and finally API level endpoint configuration.

The suggested approach is to maintain a nested architecture for resources. 
![image](https://user-images.githubusercontent.com/17596317/56016392-b85a4500-5d19-11e9-888a-9ec5edd2d201.png)

When we are parsing this routes.yaml file for the code generation process, we transform this into a flat structure where only the actual resources are available (there is no record for "/menu" in this occasion). 

**Suggested Labels:**
Discussion

**Related Issues:**
https://github.com/wso2/product-microgateway/issues/325

**Comment by praminda** [comment]
This is resolved with the cli restructure #325
