### ISSUE TITLE
Linux and Windows CLI tools behaves differently

### ISSUE THREAD

**Issue by praminda** [wso2/product-microgateway#428]
**Description:**
`micro-gw` and `micro-gw.bat` files have different behaviours when comparing the implementation. For example the cli outputs. `bat` version supports verbose mode but `bash` version doesn't. Need to go through these files and make those exactly the same

**Related Issues:**
#412

**Comment by praminda** [comment]
After recent developments in dev_first approach there are several changes that are not included in windows cli `micro-gw.bat` file

**Comment by praminda** [comment]
Updated the priority considering the impact

**Comment by praminda** [comment]
Critical issues were fixed in #480. Therefore we can reduce the priority for now.

**Comment by haze03** [comment]
I’m trying to find a way in but I need a little help , aside that  , the SD Maid Pro was paid for and I’m not receiving the app on my device.

**Comment by praminda** [comment]
Both executables has nearly similar behaviour now further improvements will be added in next release

**Comment by praminda** [comment]
Added few more fixes
