### ISSUE TITLE
Error when no arguments are provided for linux CLI

### ISSUE THREAD

**Issue by praminda** [wso2/product-microgateway#446]
**Description:**
Simply invoking the micro-gw binary without any arguments (`micro-gw`) throws main class not found error.
`Error: Could not find or load main class org.wso2.apimgt.gateway.cli.cmd.Main`

**OS, DB, other environment details and versions:**    
Linux

**Related Issues:**
#428

**Comment by hasuniea** [comment]
have to add shell fix
