### ISSUE TITLE
Error while executing "micro-gw help" command 

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-microgateway#473]
**Description:**

When I execute micro-gw help command as soon as I set the PATH variable, the following error could be seen (even before executing **micro-gw help** ).

```
$ micro-gw help
Error: Could not find or load main class org.wso2.apimgt.gateway.cli.cmd.Main
```
Then after **micro-gw init**, I executed micro-gw help and micro-gw setup commands and I got the following error.

```
$ micro-gw help
[micro-gw: unknown help topic ``, Run 'micro-gw help' for usage.]

$ micro-gw help setup
[micro-gw: unknown help topic `setup`, Run 'micro-gw help' for usage.]

```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0-alpha
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Mentioned in the description.

**Related Issues:**

**Comment by praminda** [comment]
@dinusha92 Can you please try latest master build. We've done several improvements after alpha release. However this issues is reproducible in master. @VirajSalaka is looking in to this.
