### ISSUE TITLE
Improve the README to show how to call an api without security and with security

### ISSUE THREAD

**Issue by nuwanbando** [wso2/product-microgateway#505]
How do I call an API without security ? what's the openapi x-* property I should use for that ?

If I need security, how can I get a token easily ? Can we improve the README to have that info. 

Right now if I just add a swagger and call an API I get `"fault":{"code":900902, "message":"Missing Credentials", "description":"Missing Credentials. Make sure your API invocation call has a header: \"Authorization: Bearer ACCESS_TOKEN\""}}`

Is adding `x-auth-type: None` the right method ?

**Comment by praminda** [comment]
We've introduced a new annotation for this, `x-mgw-disable-security`. Readme will be updated with details.

**Comment by praminda** [comment]
Readme is updated.
https://github.com/wso2/product-microgateway#7-disable-security-for-resources
