### ISSUE TITLE
Can we create a continuous build for the master

### ISSUE THREAD

**Issue by nuwanbando** [wso2/product-microgateway#506]
I cloned the repo and built the micro-gw locally. It would be great, if there is a continuous build setup for the master so I can download the latest binary

**Comment by praminda** [comment]
[This] is the jenkins build for master branch. You can download daily build distributions from there. Hope this is what you are looking for. 

[This]: https://wso2.org/jenkins/view/All%20Builds/job/products/job/product-microgateway

**Comment by nuwanbando** [comment]
I think we should show that in the github project itself. Otherwise it's a disconnected experience. Shall we put a builder link/icon in to the readme page. so anyone can click and navigate to the latest build ?
