### ISSUE TITLE
port 9096 doesn't work

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-microgateway#525]
**Description:**
MG startup log prints this.

```
[ballerina/http] started HTTPS/WSS endpoint 0.0.0.0:9096
[ballerina/http] started HTTPS/WSS endpoint 0.0.0.0:9095
[ballerina/http] started HTTP/WS endpoint 0.0.0.0:9090
```

But the port 9096 is not working. why do we need that line?

**Comment by praminda** [comment]
Port `9096` is used for exposing `/token, /authorize, /revoke` endpoints.
So this port will not be available for normal api communication.

**Comment by bhathiya** [comment]
Is `started HTTPS/WSS endpoint` something we can modify?

**Comment by praminda** [comment]
This is coming from ballerina when a listener is initialized. Since `9096` this is not a custom listener we implemented, we don't have access to `__init` at the moment. Otherwise we can print a meaningful message when the listener is initialized. 
I'll check if there's an easy way to print an info log describing what are the endpoints available through each listener.

**Comment by praminda** [comment]
Ballerina doesn't seems to have a way to implement this at the moment. I've created ballerina-platform/ballerina-lang#15320 to track this.
However we'll add a log to our custom gateway listeners mentioning that these are the endpoints that should be used for gateway communication. This should clear any confusion on which port to use.

**Comment by bhathiya** [comment]
+1. That's should solve the problem.

**Comment by praminda** [comment]
We've added below log messages for HTTP and HTTPS gateway listeners

```
[micro-gateway] HTTPS listener started on port 9095
[micro-gateway] HTTP listener started on port 9090
```

**Comment by praminda** [comment]
Final output after the review.
```
[ballerina/http] started HTTPS/WSS endpoint 0.0.0.0:9096
[ballerina/http] started HTTPS/WSS endpoint 0.0.0.0:9095
[ballerina/http] started HTTP/WS endpoint 0.0.0.0:9090
2019-05-16 21:43:12,411 INFO  [wso2/gateway] - HTTPS listener is active on port 9095 
2019-05-16 21:43:12,411 INFO  [wso2/gateway] - HTTP listener is active on port 9090
```
