### ISSUE TITLE
Error in bash script of gateway runtime

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#526]
**Description:**
When I execute the following command

`bash gateway <EXECUTABLE_LOCATION>`

It gives the following error message in the console
`/home/rajith/APIM/cli_restructure/wso2am-micro-gw-linux-3.0.0-beta3-SNAPSHOT/runtime/bin/ballerina: 32: /home/rajith/APIM/cli_restructure/wso2am-micro-gw-linux-3.0.0-beta3-SNAPSHOT/runtime/bin/ballerina: source: not found`

**Affected Product Version:**
3.0.0-beta2

**Related Issues:**

**Comment by bhathiya** [comment]
Duplicate of https://github.com/wso2/product-microgateway/issues/524
