### ISSUE TITLE
Make toolkit behaves same when open APIs are added and imported from APIM

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#545]
**Description:**
Currently the swagger of the  imported APIS resides in the gen folder, because toolkit generates the swagger. But this should be similar to adding swagger by Developer.
There should be a way to  add a swagger hosted on any public url, using either init command or  add command. So the importing API and developer adding would be have the same approach. 

for ex:
`micro-gw init https://<APIM_URL>/api/am/publisher/v0.14/apis/<api-name>/swagger`

**Comment by praminda** [comment]
We initially decided not to let developers edit imported APIs because that can create inconsistencies between APIM API and MGW API. We need to take a final decision on this.

**Comment by praminda** [comment]
This part is already fixed in master with #866

**Comment by Rajith90** [comment]
This has been fixed with the issue : https://github.com/wso2/product-microgateway/issues/866
