### ISSUE TITLE
Basic auth password doesn't accept lowercase hashes

### ISSUE THREAD

**Issue by praminda** [wso2/product-microgateway#553]
**Description:**
sha1 hashed password given for `"b7a.users"` config in `micro-gw.conf` is not validated correctly if hash is provided in lower case. Authentication happens successfully only if password is provided in all uppercase letters.
Ex:
`d033e22ae348aeb5660fc2140aec35850c4da997` doesn't work
`D033E22AE348AEB5660FC2140AEC35850C4DA997` works

**OS, DB, other environment details and versions:**    
Any

**Steps to reproduce:**

- Configure mgw to work with [basic auth]
- Generate the password hash using command `echo -n <password> | sha1sum` or using [md5hashing] tool
- Configure `micro-gw.conf` with generated password and try to invoke the API resource

[md5hashing]: https://md5hashing.net/hash/sha1
[basic auth]: https://github.com/wso2/product-microgateway#microgateway-securing-apis

**Comment by shaniR** [comment]
Added a note to the document with this information. https://docs.wso2.com/display/MG300/Basic+Authentication

**Comment by praminda** [comment]
@shaniR Great.
We can't add an implementation level fix for this because we can't ballerina's password match can't be case insensitive. Therefore we've to live with the note in the documentation, informing users the type of hash we accept.
