### ISSUE TITLE
etcd - Issue with defining multiple URLs in the Swagger file

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-microgateway#561]
**Description:**
I get the following error when running the micro-gw build petstore-project command trying option 1 and option 2 separately. However, the micro-gw build command works perfectly with Option 3. Therefore, it looks like at the moment we do not support multiple URLs to be added under x-mgw-production-endpoints:

`
Compiling source
    src:0.0.0
error: src:0.0.0::Swagger_Petstore_New__1_0_0.bal:17:5: invalid token ']'
`

==============================================
**Option 1**
x-mgw-production-endpoints:
  urls:
  - https://petstore.swagger.io/v2
  - etcd(petstore,https://www.petstore.com/ps_homepage.aspx)

==============================================
**Option 2**
x-mgw-production-endpoints:
  urls:
  - etcd(petstore1,http://ws.cdyne.com/phoneverify/phoneverify.asmx)
  - etcd(petstore,https://www.petstore.com/ps_homepage.aspx)

==============================================
**Option 3**
x-mgw-production-endpoints:
  urls:
  - etcd(petstore,https://www.petstore.com/ps_homepage.aspx)

**Suggested Labels:**

**Suggested Assignees:**
Viraj Gamage

**Affected Product Version:**
MGW-3.0.0-RC1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praminda** [comment]
@VirajSalaka is working on a fix
