### ISSUE TITLE
[Micro GW] Few hyperlinks are pointing to old APIM docs

### ISSUE THREAD

**Issue by rnavagamuwa** [wso2/product-microgateway#594]
Few hyperlinks in the Micro GW docs point to old APIM(2.5) docs.

- "**View documentation**" link on the download page
- See "**Microgateway quick start**" hyperlink of [this](https://docs.wso2.com/display/AM260/Overview+of+the+Microgateway) doc

**Comment by Mariangela** [comment]
Fixed the second link and checked all the other links and updated them. As the first link is in wso2.com [1], I will get Marketing to update this link.

[1] https://wso2.com/api-management/api-microgateway/#download-micro-api-gateway

**Comment by Mariangela** [comment]
Now, issue #1 also has been fixed in [1]. Thanks for reporting!

[1] https://wso2.com/api-management/api-microgateway/#download-micro-api-gateway
