### ISSUE TITLE
Deployment toml attributes in documentation

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-microgateway#614]
MGW version 2.6.0 documentation related to [docker deployment](https://docs.wso2.com/display/AM260/Deploying+the+API+Microgateway+in+Docker) explains each attribued in deployment.toml file. But in MGW 3.0.1 [document](https://docs.wso2.com/display/MG301/Deploying+the+API+Microgateway+in+Docker), it is not available.

**Comment by praminda** [comment]
Documentation is available now. Check [1], it is linked from the link @dinusha92've shared. Please check and reopen if there are any remaining issues.
[1]: https://docs.wso2.com/display/MG300/deployment.toml+for+Docker
