### ISSUE TITLE
Incorrect command in MGW document

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-microgateway#615]
### Description:

[Deployment documentation](https://docs.wso2.com/display/MG301/Depolyment) has two subtopics for Docker and K8s. Both of those documents contains **micro-gw setup** command, which is not available in the latest micro-gw toolkit.

### OS, DB, other environment details and versions:
- OS:
- Client:
- DB:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
Documentation page is updated now please check
