### ISSUE TITLE
APIs with disabled HTTP transport can be invoked from HTTP

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-microgateway#617]
### Description:
APIs with disabled HTTP transport can be invoked from HTTP

### Steps to reproduce:
- Create an API with HTTP transport disabled.
- Import the API to microgateway and build it.
- Start the microgateway
- We can see HTTP port getting still started.
```
2019-06-10 17:44:58,323 INFO  [wso2/gateway] - HTTP listener is active on port 9090 
```

- Invoke the API using the HTTP port and it still gets successful.

### Affected Product Version:
3.0.1-rc3

**Comment by praminda** [comment]
Currently we don't have a configuration to expose APIs in a selected transport. Also we don't support all the configurations available in WSO2 APIM. Therefore  lowering the priority for the moment.

**Comment by Rajith90** [comment]
With MGW 3.1.0 onward we can specify the transport types as below in the open API

```yaml
x-wso2-transports:
- "http"
-"https"
```
