### ISSUE TITLE
Enable Http 2.0 when runs Microgateway using standard VM

### ISSUE THREAD

**Issue by npamudika** [wso2/product-microgateway#683]
### Description
We need to mention, how to enable Http 2.0 when it runs the Microgateway using the standard VM in Doc [1]. We need to mention that we have to change the following configuration to **true** in the **MGW-RUNTIME-HOME/conf/micro-gw.conf** file.

### Affected Product Version
3.0.1

[1] https://docs.wso2.com/display/MG301/Enabling+HTTP+2.0

**Comment by Mariangela** [comment]
This information is now available in [1]. @npamudika , please let me know if you need this documentation improved any further.

[1] https://docs.wso2.com/display/MG301/Enabling+HTTP+2.0#EnablingHTTP2.0-EnablingHTTP2.0onAPIMicrogateway

**Comment by npamudika** [comment]
We need to mention how to enable http/2 support for a VM. The doc only indicates how this can be enabled in a docker setup.

**Comment by praminda** [comment]
Steps to enable http2 is the same. Step on how to test it gives the docker sample command in this doc. I think thats fine as long as steps to enable the feature is not different from VM to docker.

**Comment by praminda** [comment]
@Mariangela looks like we need to update step 05 to make the doc compatible with non-docker environments. 
In that case `micro-gw.conf` file is located in `<MGW-RUNTIME-HOME>/conf` directory

**Comment by praminda** [comment]
Updated the [documentation](https://docs.wso2.com/display/MG300/HTTP+2.0) with VM based configurations and command. Docker commands will not be listed per each configuration patter. How to start docker based setup is described in docker Quick start and other documents.
