### ISSUE TITLE
Release 3.0.1 Doesn't have toolkit distributions

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-microgateway#684]
### Description:

WSO2 API MG 3.0.1 [release page](https://github.com/wso2/product-microgateway/releases/tag/v3.0.1) dosen't have toolkit distributions.

### OS, DB, other environment details and versions:
- OS:
- Client:
- DB:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
@ajanthan We are not releasing distribution artifacts in github release as it makes harder to track downloads. Once the GA release is announced all, distribution artifacts will be available via [https://wso2.com](https://wso2.com/api-management/api-microgateway/) downloads page
