### ISSUE TITLE
micro-gw build output is not clear

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-microgateway#687]
### Describe your problem(s)
When I execute build command I see the following message on a successful build.
micro-gw build petstore
Compiling source
    src:0.0.0

Running tests
    src:0.0.0
	No tests found

Generating executable
    `./target//Users/ajanthan/setups/mg-projects/petstore/target/petstore.balx`
The message under Generating executable is not clear. What is the meaning of `./target//Users/ajanthan/setups/mg-projects/petstore/target/petstore.balx`?

### How will you implement it

---

**Comment by praminda** [comment]
Fix is merged to release branches. Hence closing the issue.
