### ISSUE TITLE
Ability to do JWT Authentication by providing JWKS endpoint

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-microgateway#688]
### Describe your problem(s)
Currently Setting up JWT authentication involves importing the public certificate manually but nowadays it is standard to supply key via JWKS endpoint.

### How will you implement it

---

**Comment by drobert-bfm** [comment]
No reply on this? nearly a year later??? 
Come on guys, .well-known and JWKS are pretty much no brainers today. Not supporting it makes you look like you're not keeping up and makes the product looks like a dead end.

**Comment by praminda** [comment]
@menakaj It seems we can resolve this issue with #1307? Is there anything pending?

**Comment by menakaj** [comment]
This is fixed with #1307
