### ISSUE TITLE
Health Check API for Individual API Gateway

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-microgateway#690]
### Describe your problem(s)

Does micro gateway expose healthz api? 

### How will you implement it

---

**Comment by Rajith90** [comment]
Hi Ajanathan,
Microgateway 3.0.1 atm does not have in built healthz api,
But we can use the startup extensions of microgateway to schedule timer tasks to periodically, send an update to a relevant parties regarding its availability.
When you initialize the microgateway project there is an file called startup_extension.bal inside the extension folder. Here we can implement the timer task. So in this approach we can implement the push method to notify the health
We will consider this in the roadmap for future releases.

**Comment by Rajith90** [comment]
Microgateway will expose a health check endpoint with "/health" context from 3.1.0.-alpha onwards. This is supported in GET, PUT, POST operations

please find the sample request below

```
curl -k -X POST "https://localhost:9095/health" -v

curl -k "https://localhost:9095/health" -v
```

And it will respond with an json payload as below

```
{"status":"healthy"}
```
