### ISSUE TITLE
How to unit test intercepters

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-microgateway#691]
### Describe your problem(s)

How can I unit test interceptors? Is there any sample?

### How will you implement it

---

**Comment by Rajith90** [comment]
Hi Ajanathan, 
We do not have sample in microgateway. 
But since we are using ballerina for interceptors, we can use the ballerina test framework (Testerina)[1], to write unit tests for the interceptors.

[1] -https://ballerina.io/learn/how-to-test-ballerina-code/
