### ISSUE TITLE
Error when importing API that has SOAP backend

### ISSUE THREAD

**Issue by vithu30** [wso2/product-microgateway#716]
### Description:
When building the imported API that has SOAP back-end, it fails with following exception.
`ERROR {org.wso2.apimgt.gateway.cli.cmd.Main} - 'x-wso2-production-endpoints' and 'x-wso2-sandbox-endpoints' properties are not included under API Level in openAPI definition`

The endpoint type for SOAP endpoint is set as "address" which is not handle in [1].

### Steps to reproduce:

- Create API using by following either [2] or [3]
- Import the API in micro-gateway
- Build the project

[1] https://github.com/wso2/product-microgateway/blob/v3.0.1/components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/RouteUtils.java#L323
[2] https://docs.wso2.com/display/AM250/Create+and+Publish+a+SOAP+API
[3] https://docs.wso2.com/display/AM250/Generate+REST+API+from+SOAP+Backend

### Affected Product Version:
3.0.1

### OS, DB, other environment details and versions:
- OS:
- Client:
- DB:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
Hi @vithu30 Thanks for identifying where the issue is. I'll add a fix to handle `address` type endpoints.
