### ISSUE TITLE
Cannot setup distributed throttling by following the Doc

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-microgateway#722]
Doc https://docs.wso2.com/display/MG301/Distributed+Throttling has steps to setup the distributed throtting for MG. But cannot set up this by following the doc. For example it has a url **throttleEndpointUrl** but there is no mentioning on how to configure this. It has https://localhost:9443/endpoints as the sample url but it has no use. Please fix this doc.

**Comment by Rajith90** [comment]
This has been explained in the documentation
