### ISSUE TITLE
Cannot add labels to deployment using deployment toml

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-microgateway#734]
### Description:
I tried to define a label for the deployment in K8s and it failed. This feature needs to test properly along with other annotations for K8s.

[kubernetes]
  [kubernetes.kubernetesDeployment]
    enable = true
    image = 'pubudu/petstore:v1.0'
    labels = '{app:k8s_project}'

Sample definition in Ballerina for label defining https://github.com/ballerinax/kubernetes/blob/85411c2e3d76425bc825391267f6b8d9be72f7b6/kubernetes-extension-test/src/test/resources/job/ballerina_job.bal#L25

### OS, DB, other environment details and versions:
- OS:
- Client:
- DB:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
Label should be provided in this format `labels = '{"app": "k8s_project"}'`
But ATM even if you provide this in the correct format it generates below annotation causing compilation issues.

```java
@kubernetes:Deployment {
    name:"petstore-deployment-abcd-sd9234-4352-96e1be9356",
    labels:{&quot;app&quot;: &quot;k8s_project&quot;},
    image:"pubudu/petstore:v1.0"
}
```

Which means mustache is escaping the config value. This can be fixed if we skip the escaping in mustache by using `{{& var_name}}` syntax.

**Comment by pubudu538** [comment]
Great! Let's get this fixed. Better to try multiple labels. I think we will have to look at other places where we can give labels and fix those accordingly.

**Comment by praminda** [comment]
Fix is merged to release branches. Hence closing the issue.
