### ISSUE TITLE
MG port changes do not change the ports defined in K8s services

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-microgateway#737]
### Description:
We can change the default ports in the microgateway using the micro-gw.conf. Although we change these ports, it does not change the ports defined in K8s services. K8s services are getting created with default ports.

### OS, DB, other environment details and versions:
- OS:
- Client:
- DB:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
Generating k8s services in something that happens at the build time of an MGW project. However `micro-gw.conf` is a runtime configuration. So I don't see a way to push these configurations to k8s services.

**Comment by praminda** [comment]
@pubudu538 Since this is internal mgw port (not the externally exposed port) we can ignore this for now. Please reopen if you think otherwise.
