### ISSUE TITLE
Template overriding issue when configured different keystores for different ports 9095/9096

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-microgateway#738]
### Description:
Update listeners.mustache template to use different keystores for ports 9095 and 9096. When starting the MGW server below error can be observed.

> error: {ballerina/http}HTTPError {message:"Conflicting configuration detected for listener configuration id 0.0.0.0:9096"}
> 	at ballerina/http:initEndpoint(<native>)
> 	   ballerina/http:init(service_endpoint.bal:85)
> 	   ballerina/http:__init(service_endpoint.bal:50)
> 	   src:0.0.0:src:0.0.0.<init>(listeners.bal:77)

### Steps to reproduce:

- Add additional keystore in 3.0.1/runtime/bre/security directory.
- Configure wso2am-micro-gw-toolkit-3.0.1/resources/templates/listeners.mustache file referring to both keystores.
- Build the project and run.

### Affected Product Version:
3.0.1

**Comment by praminda** [comment]
Thanks for reporting the issue. Further discussion on the root cause of the issue can be found in ballerina-platform/ballerina-lang#17600

**Comment by Rajith90** [comment]
We have deprecate the usage of port 9096. The /token, /authorize and etc endpoints are available via port 9095
