### ISSUE TITLE
If there is a path variable which contains basepath as substring, 404 error occurs

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#749]
### Description:
If there is a path variable which contains the "x-wso2-basePath" as a substring, 404 error occurs. The underlying reason is that every substring which contains basePath is replaced by null string. Therefore the path variable becomes modified.
https://github.com/wso2/product-microgateway/blob/a0145c9b215c55e5a1625c3241111faefe88c4a7/components/micro-gateway-cli/src/main/resources/templates/service.mustache#L89

### Steps to reproduce:
Modify an openAPI definition such that basepath contains as a substring in a path variable.
>Ex.
x-wso2-basePath : "pet"
paths:
    /pet/findByStatus

### Affected Product Version:
3.0.1

### OS, DB, other environment details and versions:
- OS: MacOS Mojave
- Client:
- DB:
- Env (Docker/K8s):

**Comment by praminda** [comment]
looks like `replace("{{basepath}}","");` does a replaceAll. We should request replaceFirst behavior from new ballerina string libs.

**Comment by praminda** [comment]
This is available in ballerina 1.0.0 with stringutils. Therefore we should fix this in the next release.

**Comment by praminda** [comment]
Fixed in master by #759 as part of the jballerina migration
