### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-microgateway#763]
### Description:
Spelling mistake of "referred" in Document. 
Line - TASKS are **refered** to the workflows in WSO2 API Manager that you can configure constraints on top of actions performed. 
 in Doc on API Cloud: https://docs.wso2.com/display/APICloud/Key+Concepts

### Steps to reproduce:
TASKS are **referred** to the workflows in WSO2 API Manager that you can configure constraints on top of actions performed. 

### Affected Product Version:
Wso2 API Cloud Documentation

### OS, DB, other environment details and versions:
- OS:
- Client:
- DB:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
Issue is not related to WSO2 API Microgateway. @arshita-kakkar Can you please report this issues through the "Provide Feedback" button on the same documentation link?
