### ISSUE TITLE
Micro gateway can not call services through a proxy

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#802]
### Description:
If the back end service can be connected via n proxy server, then microgateway does not have a way to specify the proxy server url, port, username and password values.

### Steps to reproduce:
1. Expose backend service and make it connect via a proxy server(squid proxy)
### OS and other environment details and versions:
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Rajith90** [comment]
With the fix : #product-microgateway/pull/814 we can define proxy configs as below in open API , using the x-wso2-production-endpoint vendor extension

`
x-wso2-production-endpoints:
  urls:
    - https://localhost:2380/v1
    - https://localhost:2380/v2
  proxyConfig:
    host: localhost
    port: 3128
`

And also this can be overridden for all the APis in the gateway by providing the configs globally in the micro-gw.conf file as below

`
[httpClients]
  verifyHostname=true
  [httpClients.proxy]
    enabled = false
    host = ""
    port = ""
    username = ""
    password = ""
`

This configuration will apply to the http clients used by microgateway as well. Here are few http clients which will use the proxy config

- The client used to communicate with key manager for token validation
- The client used to publish throttle events to the traffic manager of WSO2 Traffic manager
- The client used to communicate with etcd server for service discovery
- The client used to communicate with WSO2 Analytics server to upload analytics event written files
- The client used to communicate with etcd server to get updates regarding revoked jwt tokens

**Comment by Rajith90** [comment]
Since API developer should not know the knowledge about the proxy configurations, asking to configure the proxy configuration on the open API itself would makes less sense. So we have changed only to use the proxy configs from the micro-gw.conf file as below.
[httpClients]
  verifyHostname=true
  [httpClients.proxy]
    enabled = true
    host = "localhost"
    port = 3128
    username = ""
    password = ""`
`

This config will apply to all the client endpoint in the micro gateway which are connecting to the actual back ends of the services exposed via micro gateway.
And also it will apply to the following client used with in the gateway to communicate external parties like key manager, analytics server, etcd, Traffic manager and etc.

- The client used to communicate with key manager for token validation
- The client used to publish throttle events to the traffic manager of WSO2 Traffic manager
- The client used to communicate with etcd server for service discovery
- The client used to communicate with WSO2 Analytics server to upload analytics event written files
- The client used to communicate with etcd server to get updates regarding revoked jwt tokens

**Comment by praminda** [comment]
@Rajith90 Did we fix this on master

**Comment by praminda** [comment]
@Rajith90 I don't see the new configuration on default-mgw-conf.template did we add this to master?

**Comment by Rajith90** [comment]
This fix is not available in the 3.0.x as well as the master, since this needs major revamp in the client side code

**Comment by Rajith90** [comment]
This behaviour can be achieved by editing the template files in the toolkit. Hence reducing the severity of the issue

**Comment by Rajith90** [comment]
Since API developer should not know the knowledge about the proxy configurations, asking to configure the proxy configuration on the open API itself would makes less sense. So we have changed only to use the proxy configs from the micro-gw.conf file as below.
```toml
[httpClients]
  verifyHostname=true
  [httpClients.proxy]
    enabled = true
    enableInternalServices = true
    host = "localhost"
    port = 3128
    username = ""
    password = ""
```

This config will apply to all the client endpoint in the micro gateway which are connecting to the actual back ends of the services exposed via micro gateway.
And also it will apply to the following client used with in the gateway to communicate external parties like key manager, analytics server, etcd, Traffic manager and etc if the `enableInternalServices` config also set to true.

- The client used to communicate with key manager for token validation
- The client used to publish throttle events to the traffic manager of WSO2 Traffic manager
- The client used to communicate with etcd server for service discovery
- The client used to communicate with WSO2 Analytics server to upload analytics event written files
- The client used to communicate with etcd server to get updates regarding revoked jwt tokens
