### ISSUE TITLE
No matching resource found for path... while invoking a local API using Microgateway (API Manager 2.6.0)

### ISSUE THREAD

**Issue by SushantWankhede** [wso2/product-microgateway#803]
**Description:**
I'm working with Microgateway coupled with API Manager 2.6.0. I'm working on Windows environment. I've created a .net core API and was running it locally. And the invoking the API using Microgateway gives no matching resource found..

**Steps to reproduce:**
1. Published the API with production and sandbox URL's https://localhost:44337/v1/1.0.0/ as my local API is running on 44337. The context was given as v1/1.0.0 in the Publisher. For the GET method, I had added Produces = application/xml and Consumes = application/json, and added one parameter. After publishing the Production and Sandbox URL's shown as below
http://ip-address:8281/v1/1.0.0
http://ip-addres:8281s/v1/

https://ip-address:8244/v1/1.0.0
https://ip-address:8244/v1/

2. Subscribed to the API on the Store after creating a new application. 
3. I setup the project with command: micro-gw setup projectName -a apiName -v 1.0.0
4. Build the project with: micro-gw build projectName
5. After it successfully built, I ran the "gateway" from the bin directory of the executable. It ran successfully and generated the .balx file.
6. To invoke the project, I used the below command
curl -k -i -H "Authorization: Bearer 7a02d94e-9653-3fd0-b58a-79738c5ca277" https://localhost:44337/v1/1.0.0/resourceName/{id}. This returned the response successfully.
7. But, I noticed that it's not running via Microgateway using https://localhost:9095...
8. So, after reading more, I added a microgateway in Admin portal and gave the GatewayHost as https://localhost:9095.
9. Then I selected this microgateway label on my API in the Publisher and clicked on Save & Publish button. After this, in the Store, this is displayed under Microgateways section of my API: https://localhost:9095/v1/1.0.0
10. Then I ran the below command,
curl -k -i -H "Authorization: Bearer 7a02d94e-9653-3fd0-b58a-79738c5ca277" https://localhost:9095/v1/1.0.0/resourceName/{id}.
11. After running the above command, I'm getting the below error. 
HTTP/1.1 404 Not Found
content-type: text/plain
content-length: 79
server: wso2-http-transport
date: Fri, 20 Sep 2019 15:46:05 +0530

no matching resource found for path : /v1/1.0.0/resourceName/{id} , method : GET

12. Just to make sure, I setup and built the same project again, but it's giving the same issue. Could you please help?

**Affected Product Version:**
Microgatewat (API Manager 2.6.0)

**OS and other environment details and versions:**
Windows 10

**Comment by SushantWankhede** [comment]
@praminda could you please help getting directions on this? I'm not sure I'm missing any steps or there is any issue. I see that you assisted me with the issue before, https://github.com/wso2/product-microgateway/issues/793.

**Comment by SushantWankhede** [comment]
@malinthaprasan I followed your video at https://docs.wso2.com/display/AM260/API+Microgateway+Walkthrough. Could you please help me with the above issue? I would be really grateful! Thank you!

**Comment by praminda** [comment]
@SushantWankhede Tried this myself but seems to work for me. Can you please attach the `<MGW_PROJECT>/src/<apiName>_1.0.0.bal` file?

**Comment by SushantWankhede** [comment]
@praminda, I guess I was sending an OAuth token with the Microgateway as it was mentioned here https://docs.wso2.com/display/AM250/Microgateway+Quick+Start#MicrogatewayQuickStart-GenerateadistributionforasingleAPI that it works with both JWT or an OAuth2 token. Then I tried sending JWT token, hosted the application in local server and changed the Production URL in the Publisher to point to the one with an IP address. On validating this URL, it came as valid and everything worked fine. Does Microgateway work with both JWT and OAuth?

**Comment by praminda** [comment]
It does work with both OAuth and JWT. However to use OAuth tokens you need to configure a Key manager for MGW. MGW can self validate JWT tokens but for OAuth tokens you need a running Key Manager in the deployment.
check the keymanager configurations here. https://docs.wso2.com/display/MG301/FAQs#FAQs-HowshouldIconfiguretheKeyManagerwhenusinganOAuth2Token%3F

**Comment by praminda** [comment]
@SushantWankhede Were you able to make it work after following the suggested steps?

**Comment by SushantXPO** [comment]
@praminda Thanks for reaching out to me! Yes it allowed using the OAuth token by having the below setting in the micro-gw.conf file. 
[keyManager]
serverUrl="https://localhost:9444"
username="admin"
password="admin"
tokenContext="oauth2"
timestampSkew=5000
verifyHostname=true

I was getting some error, may be because my host is on the 9444 port and not on 9443 as by default the micro-gw.conf file gives 9443 port. I figured that out and it'w working now.

**Comment by praminda** [comment]
great. I'm closing the issue.
