### ISSUE TITLE
Analytics publishing error will result in request to break

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#808]
### Description:
The analytics filter publishes the request and response path data to analytics server. Error while collecting data to publish will result in an error for the client request. We need to avoid disturbing the request flow whenever analytics publishing flow is broken.

### Affected Product Version:
3.0.1

### OS and other environment details and versions:
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
@Rajith90 Can you send the fix for master branch aswell

**Comment by Rajith90** [comment]
This already fixed in the master as well.
