### ISSUE TITLE
Microgateway toolkit and runtime uses installed b7a version

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#810]
### Description:
Microgateway runtime and toolkit seems to use BALLERINA_HOME variable if it is set as an environment variable. This will cause issues for users who have already installed ballerina in their environments. The BALLERINA_HOME should be set to the packed b7a distributions of the gateway runtime and toolkit,

### Steps to reproduce:
Install ballerina version locally(1.0.0)
Try to build a project with toolkit.
This will result in build errors
### Affected Product Version:
3.0.1

### OS and other environment details and versions:
- OS:Windows
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
Fix is merged to release branches. Hence closing the issue.
