### ISSUE TITLE
[Analytics] Error when load testing API invocations

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-microgateway#821]
### Description:
Error when load-testing API invocations of an API hosted on the microgateway.

![image](https://user-images.githubusercontent.com/32578617/65848886-a884fa80-e365-11e9-9c32-04c52fdf5456.png)

### Steps to reproduce:

- Configure Microgateway with API Analytics
- Start analytics server
- Initialize new microgateway project
- Import API from API Manager into microgateway
- Build microgateway project
- Run project on microgateway.
- Perform load testing.

### Affected Product Version:

3.0.1

### OS and other environment details and versions:
- OS: Ubuntu 18.04.2 LTS
- Client:
- Env (Docker/K8s):

---

**Comment by Rajith90** [comment]
@VirajSalaka will look into this

**Comment by menakaj** [comment]
Typecasting errors are fixed in https://github.com/wso2/product-microgateway/pull/1319
