### ISSUE TITLE
MGW jwt and basic auth uses unauthenticated tier when used with security

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#832]
### Description:
Microgateway uses unauthenticated tier as the subscription level tier, when jwt(without subscription claim) and basic auth is used. We need to introduce a default subscription tier in those scenarios.

### OS and other environment details and versions:
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
[Fix](https://github.com/wso2/product-microgateway/pull/844) merged
