### ISSUE TITLE
Need a way find toolkit/runtime version

### ISSUE THREAD

**Issue by praminda** [wso2/product-microgateway#839]
### Describe your problem(s)

Currently both micro-gw and gateway executable doesn't provide a way to find the installed version using a command line argument. This should be available in both executables.
### Describe your solution

Introduce version command for both executables
`./micro-gw version`
`./gateway version`
### How will you implement it

Register new jcommander command to resolve version in toolkit.
In runtime executable we might have to do this within the executable itself.

**Comment by Rajith90** [comment]
@chashikajw is currently looking into this
