### ISSUE TITLE
Update the microgateway docker base image creation using the binary

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#842]
### Describe your problem(s)
ATM MGW docker base image is created using the b7a base image. This can cause problems when delivering updates for the product. Hence we need to create the docker base image using the binary distribution of the microgateway
### How will you implement it

Extract the binary distribution of mgw, add proper users and groups to the image , and assign relevant permissions to paths.
---

**Comment by praminda** [comment]
@VirajSalaka Hope you are working on this with new distribution changes

**Comment by praminda** [comment]
Fixed.
Related PR #1047
