### ISSUE TITLE
swagger File format is invalid for API s created in the publisher.

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-microgateway#845]
As we can't import api definitions through import command i copied the swagger and created a yaml file inside the api definitions folder in my project. But when building the project it says that swagger end point and sandbox endpoint format is invalid.

micro-gw build calculator
micro-gw: Error while parsing the endpoint object. The x-wso2-production-endpoints or x-wso2-sandbox-endpoints format is incompatible : http://www.mocky.io/v2/5d8b5bf03500008ca3d46f2a

**Comment by praminda** [comment]
Is this related to importing from apim 3.0.0? Also please attach the swagger file. If swagger provided by APIM is not compatible with mgw then it should be corrected in APIM.

**Comment by praminda** [comment]
@ShanJayaweera This issue can happen when you have a syntax error in production and sandbox endpoint definition in the openapi file. Please verify the syntax and reopen the issue if that is not the case
https://github.com/wso2/product-microgateway/blob/6d1175ae49c76090d83d6ab655d1aa09ac0e07ae/components/micro-gateway-cli/src/main/java/org/wso2/apimgt/gateway/cli/utils/OpenAPICodegenUtils.java#L363

**Comment by Rajith90** [comment]
This happens if the x-wso2-production-endpoint or x-wso2-sandbox-endpoint extension format is incorrect. Please re open if thats not the case
