### ISSUE TITLE
Micro gateway reset method is not documented

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-microgateway#846]
### Description:
When we import an API through Labels we need to add the username and password of the user. as I used the store in admin admin credentials I entered it. But if we import another API again it keeps that username in his memory and directly asks to add the password of the admin. So we need to use the command "micro-gw reset" if we want to add a different user name. But I was unable to find this scenario in the documentation of Micro gateway.
I have attached the cmd responses with this. 

![Screenshot from 2019-09-26 14-22-06](https://user-images.githubusercontent.com/51467737/65674437-2c8b6980-e06a-11e9-8002-a68704d5ae33.png)

### Affected Product Version:

MG300
### Content Positioning in Documentation Structure:

- Link:

- Heading (& Step):

- Any other reference:

---

**Comment by praminda** [comment]
This specific issue regarding the method to reset CLI tool is documented in [FAQs](https://docs.wso2.com/display/MG300/FAQs#FAQs-HowcanIresettheMicrogatewayCLItool?). However we need a proper single document describing all microgateway commands

**Comment by AmaliMatharaarachchi** [comment]
Added https://docs.wso2.com/display/MG310/Toolkit+commands
