### ISSUE TITLE
Quick Start doesn't work for a new user

### ISSUE THREAD

**Issue by joaoemilio** [wso2/product-microgateway#851]
### Description:
Follow the quickstart on a machine that doesn't have anything regarding Micro GW, like a new server or VM linux. It says to run the docker image that is not built by default.

### Steps to reproduce:
Follow the quickstart on a machine that doesn't have anything regarding Micro GW, like a new server or VM linux. It says to run the docker image that is not built by default.

### Affected Product Version:
3.0.2

### Content Positioning in Documentation Structure:
https://github.com/wso2/product-microgateway#microgateway-quick-start

**Comment by Rajith90** [comment]
Here is the guide to run using binary distribution
[1] - https://docs.wso2.com/display/MG300/Quick+Start+Guide+-+Binary

**Comment by praminda** [comment]
QSG now contains a link to [VM mode startup](https://github.com/wso2/product-microgateway#How-to-run-the-microgateway-distribution)
