### ISSUE TITLE
Options -v and --version are not working

### ISSUE THREAD

**Issue by joaoemilio** [wso2/product-microgateway#853]
### Description:
Options -v and --version are not working

### Steps to reproduce:
MacBook-Joao:microgw-3.0.2 joaoemilio$ ~/tools/wso2am-micro-gw-toolkit-3.0.2/bin/micro-gw -v
[micro-gw: Unknown command '-v', Run 'micro-gw help <command>' for usage.]
MacBook-Joao:microgw-3.0.2 joaoemilio$ ~/tools/wso2am-micro-gw-toolkit-3.0.2/bin/micro-gw --version
[micro-gw: Unknown command '--version', Run 'micro-gw help <command>' for usage.]
MacBook-Joao:microgw-3.0.2 joaoemilio$ 

### Affected Product Version:
3.0.2

### Environment details (with versions):
- OS: MacOS Mojave 10.14.6
- Client:
- Env (Docker/K8s): Binary

**Comment by praminda** [comment]
Hi @joaoemilio 
`-v` and `--version` are not supported parameters in `micro-gw` tool at the moment. We have a separate issue #839 to follow this implementation. Hopefully we'll be able to push it with the next release.

**Comment by praminda** [comment]
Please track the progress #839
