### ISSUE TITLE
Windows Installer for 3.0.2 points to a 3.0.1 folder by default

### ISSUE THREAD

**Issue by joaoemilio** [wso2/product-microgateway#856]
Windows Installer for 3.0.2 points to a 3.0.1 folder by default
![mg302-git-issue-2019-11-02 145327](https://user-images.githubusercontent.com/11098232/68074988-a658f600-fd80-11e9-9816-6193b82410c8.png)

**Comment by praminda** [comment]
Hi @joaoemilio 
Thanks for reporting the issue. Can you please fill the bug issue template for this, according to the [contribution guidelines]. This helps us to keep everything organized.

[contribution guidelines]: https://github.com/wso2/product-microgateway/blob/master/CONTRIBUTING.md#reporting-an-issue

**Comment by praminda** [comment]
Fixed in latest windows installer
