### ISSUE TITLE
Overriding Endpoints for Developer-first Approach APIs

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-microgateway#859]
### Description:
On the microgateway overriding endpoint information, the provided information doesn't seem correct under the developer first approach. Can't figure out the endpoint name by looking at the swagger file. Also this doc needs information on how to override the endpoint when running the microgateway on docker.

https://docs.wso2.com/display/MG300/Overriding+Endpoints+for+Developer-first+Approach+APIs#examplemultiple-dev

https://wso2.org/jira/browse/DOCUMENTATION-8667

**Comment by AmaliMatharaarachchi** [comment]
closing as this has been updated. https://mg.docs.wso2.com/en/latest/how-tos/endpoints/overriding-endpoint-information/overriding-endpoints-for-developer-first-approach-apis/
