### ISSUE TITLE
Issue in Docker image creation 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#863]
### Description:
Error `ballerina: unknown option: '--config'
Run 'ballerina help' for usage.` thrown when creating a docker image

### Steps to reproduce:
Build DockerFile and run

### Affected Product Version:
toolkit 3.0.2
jballerina

### Environment details (with versions):
- OS: MacOS catalina
- Client:
- Env (Docker/K8s): Docker

---
#### Suggested Labels:
bug

#### Suggested Assignees:
AmaliMatharaarachchi

**Comment by praminda** [comment]
[Fix](https://github.com/wso2/product-microgateway/pull/864) merged
