### ISSUE TITLE
Commands to deploy MGW with a command-line tool 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#866]
### Describe your problem(s)
It is better to be able to upload api definition in project initializing stage by a CLI command instead of copying files manually.
Provide CLI commands to enable docker deployment. 

### Describe your solution
Introduce option --api-definition to init command to set api definition to project directory.
Introduce option --docker to build command to setup docker configurations.

### How will you implement it

---
#### Suggested Labels:

jballerina

#### Suggested Assignees:

AmaliMatharaarachchi

**Comment by praminda** [comment]
[Fix](https://github.com/wso2/product-microgateway/pull/865) merged to master
