### ISSUE TITLE
Microgateway doesn't honor URL params for API context

### ISSUE THREAD

**Issue by chintana-zz** [wso2/product-microgateway#873]
Steps to reproduce,
1. Create an API swapping version and context using a URL params
<img width="528" alt="url-params" src="https://user-images.githubusercontent.com/27903/67460507-0072f200-f5f0-11e9-819f-3cd1187cff32.png">

2. Publish the API, then subscribe to the API

3. Test the API using store swagger UI to make sure API is valid and working
4. Use microgateway toolkit 3.0.1 to create a micro gateway distribution by importing this API
5. Run the microgateway zip and try to invoke the API
6. Complains that the context cannot be found

**Comment by Rajith90** [comment]
This has been fixed in MGW 3.1.0-beta and APIM 3.1.0-beta versions. Hence will be available with MGW 3.1.0 and APIM 3.1.0 versions
