### ISSUE TITLE
Support Path Parameters with a suffix

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#884]
Please refer to the following issue.
[https://github.com/ballerina-platform/ballerina-lang/issues/19957](https://github.com/ballerina-platform/ballerina-lang/issues/19957)

**Comment by praminda** [comment]
This should be resolved in master branch with latest ballerina upgrade. Need to test and verify

**Comment by VirajSalaka** [comment]
Closing the issue as it is fixed.
