### ISSUE TITLE
Observability Feature for Microgateway.

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-microgateway#888]
### Describe your problem(s)

WSO2 API Microgateway simplifies the process of creating, deploying and securing APIs within distributed microservice architectures. Performance issues, errors, and exceptions happen all the time when we are working with these microservice Architectures. 

### Describe your solution

Due to these various performance issues, errors, and exception we need to monitor our services. To accomplish this issue the concept of observability comes along with Microgateway. Observability is a measure of how well internal states of a system can be inferred from knowledge of its external outputs. Monitoring, logging, and distributed tracing are key methods that reveal the internal state of the system to provide the observability.

### How will you implement it

We have some default ballerina APIs to measure the performance. A gauge is one type of metric that is supported by default in Ballerina, and it represents a single numerical value that can arbitrarily go up and down. It can also report statistics such as max, min, mean, percentiles, etc. We have identified Analytic filter, Throttling filter, Authentication filter(handlers and handler wrappers) as some important filters that we need to monitor. So we have implemented gauges to those filters. 

Some HTTP requests and responses related data are collected from ballerina side APIs and CPU and memory-related data are collected from JMX reporter. We use Prometheus to scrape that data and Grafana to visualize those data. 

Also, we can trace our code blocks and measure the time incurred during the actual runtime execution. We have used this tracing property in each and every filter and for some identified time-consuming logics. These traces can be viewed from Jaeger or Zipkin. Ballerina by default support jaeger. 

This observability feature will also use Basic Auth to secure the endpoints which will be used by Prometheus to scrape data. 

---
#### Suggested Labels:

jballerina

**Comment by ShanJayaweera** [comment]
DashBoard previews

![Screenshot from 2019-10-30 10-16-36](https://user-images.githubusercontent.com/51467737/69524924-17a95480-0f8d-11ea-85fb-70fc7f11bbbc.png)

![Screenshot from 2019-10-30 10-19-19](https://user-images.githubusercontent.com/51467737/69525102-66ef8500-0f8d-11ea-90cc-e56e42762242.png)

![Screenshot from 2019-10-30 10-19-57](https://user-images.githubusercontent.com/51467737/69524926-1841eb00-0f8d-11ea-87f3-e9ad0ff0d730.png)

![Screenshot from 2019-10-30 10-21-23](https://user-images.githubusercontent.com/51467737/69524927-1841eb00-0f8d-11ea-8353-2ba77a459b0d.png)

**Comment by ShanJayaweera** [comment]
This Feature has two parts. Metrics and tracing. Here the tracing part will only work with the ballerina 1.0.4 upgrade as jaeger need a version bump to work properly.

https://github.com/ballerina-platform/ballerina-lang/issues/19582

**Comment by praminda** [comment]
Feature merged to master
