### ISSUE TITLE
Microgateway response delay when it is called from a remote network

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#891]
### Description:
When A request is sent from a remote network to the microgateway, it takes some time (~15s) to complete the read operation. Due to this, the response is delayed. The reason behind this issue has been a reverse DNS lookup performed by the ballerina service.

### Affected Product Version:
3.0.1, 3.0.2

---
#### Related Issues:
https://github.com/ballerina-platform/ballerina-lang/issues/20085

#### Suggested Labels:
Bug

**Comment by praminda** [comment]
This should be resolved in master branch with latest ballerina upgrade. Need to test and verify

**Comment by VirajSalaka** [comment]
Since the issue is fixed is ballerina 1.1.0 as per comment in https://github.com/ballerina-platform/ballerina-lang/issues/20085. Hence we can close this issue.
