### ISSUE TITLE
Missing JWT doc under security

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#895]
### Description:
Needs to add JWT under the security section. 

### Content Positioning in Documentation:
- Link: https://docs.wso2.com/display/MG300/Security

- Heading (& Step):

- Any other reference:

---

**Comment by praminda** [comment]
We are missing documentation on the expected content of the JWT. 
This is very important information if someone is using a JWT issuer other than WSO2 Key Manager. So its better if we can provide similar content as in [Mandatory attributes of a JWT token]

[Mandatory attributes of a JWT token]: https://apim.docs.wso2.com/en/latest/Learn/APISecurity/OAuth2DeepDive/AccessTokenTypes/jwt-tokens/#mandatory-attributes-of-a-jwt-token

**Comment by Rajith90** [comment]
Added the doc [1]

[1] - https://docs.wso2.com/display/MG310/Self+Contained+JWT+Authentication
