### ISSUE TITLE
Expose /token and /revoke endpoints in 9095 port

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-microgateway#896]
### Describe your problem(s)
When customers require SSL termination at the microgateway level, it becomes a must to use two domains for token endpoint and normal API endpoints. For example: apis.abc.com and auth.abc.com. It can confuse the users in some use cases where customers need to expose some of their login related endpoints via the gateway (apis.abc.com) which uses the normal API related domain. Then for the login related activities, they have talk cross-domains which is confusing from user PoV.

### Describe your solution
Expose the /token and /revoke endpoints as well in 9095 port with a mechanism to skip the default filters. Then all the endpoints can be exposed in a single domain when SSL termination at the microgateway is required.

**Comment by praminda** [comment]
Looks ok. But we'll have to keep both 9096 and 9095 token endpoints available until we release MGW 4.0.0
@Rajith90 As per our chat you had a plan for the implementation. Can you explain it?

**Comment by Rajith90** [comment]
We will be using the annotation [1], in the /token, /authorize, /revoke, /userinfo endpoints.
So when this annotation is used every filter will be skipped. So the token service call will not go through the filter chain. ANy deveoper writing new filter will have to perform this check on that custom filter if they want to skip that filter for the particular service

[1] - 
`@gateway:Filters {
    skipAll: true
}`
