### ISSUE TITLE
API Level auth providers not working properly

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#915]
### Description:
Security scheme defined in API level not working.

### Steps to reproduce:
Add similar to the following to a valid API definition and build a microgateway project using that definition.
`security:
  - mybasic: []
components:
  securitySchemes:
    mybasic:
      type: http
      scheme: basic
`
Basic auth is not enabled at API level but only default security "jwt","oauth2" can be observed.

### Affected Product Version:
jBallerina

### Environment details (with versions):
- OS: macos catalina
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
Using `config.basicAuth.isOptional` in below lines should fix the issue. Can you send a PR?

https://github.com/wso2/product-microgateway/blob/5c662cfc7011f8f894cce04f0e74563fb4d32220/components/micro-gateway-cli/src/main/resources/templates/service.mustache#L60-L66
