### ISSUE TITLE
Remove 9096 tokenListenerPort 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#916]
### Describe your problem(s)
We have a separate port to expose the /token, /revoke, /authorize, /userinfo endpoints. By default, this port is 9096. The API requests are served by the port 9095(https) 9090 (http).
Having an additional port makes the deployment complex.

### Describe your solution
We need to expose the /token and etc endpoints also using the 9095 port. 

### How will you implement it

---
#### Related Issues:
#896

**Comment by Rajith90** [comment]
I also agree we need to remove this port in next minor release 3.1 and above

**Comment by Rajith90** [comment]
Supporting the /token and other endpoints from 9095 and 9090 was done as an improvement in https://github.com/wso2/product-microgateway/issues/896

**Comment by praminda** [comment]
Dropping a interface port in minor release doesn't look like a good idea. Anyway it depends on the next release version number 😉

**Comment by Rajith90** [comment]
We will keep the 9096 port as it is for minor releases.
