### ISSUE TITLE
Authorization header and case sensitivity

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#925]
### Description:
When request with authorization type "bearer" is given instead of "Bearer", it fails. 

### Steps to reproduce:
curl -X GET "https://localhost:9095/petstore/v1/pet/1" -H "accept: application/xml" -H "Authorization: **Bearer** token" -> works

curl -X GET "https://localhost:9095/petstore/v1/pet/1" -H "accept: application/xml" -H "Authorization: **bearer** token" -> not working

### Affected Product Version:

jballerina

### Environment details (with versions):
- OS: catalina
- Client:
- Env (Docker/K8s):

---

**Comment by chashikajw** [comment]
MGW 3.1.0 docs contains the format as
curl -X GET "https://localhost:9095/v2/pet/1" -H "accept: application/xml" -H "api_key:$TOKEN" -k

**Comment by hasuniea** [comment]
This is a ballerina limitation
https://ballerina.io/v1-1/learn/api-docs/ballerina/auth/constants.html#AUTH_SCHEME_BEARER
