### ISSUE TITLE
wso2-microgateway not supporting all the functions of ballerina language

### ISSUE THREAD

**Issue by skz363** [wso2/product-microgateway#927]
### Description:
wso2-microgateway not supporting all the functions of ballerina language

### Details:
I tried to write a interceptor for converting the strings to uppercase and also tried to iterate a map to print the keys but wso2-microgateway is giving issue while building.

Code details:

public function prepareCommandMapFromResponse(map<json> responseMap,map<json> commandMap) {

    io:println("\nIterating a map :");
    map<string> words = { a: "apple", b: "banana", c: "cherry" };
    // Iterating a map will return the values in the map.
    foreach var fruit in words {
    string statement = "Lion in Town. Catch the Lion";

    string s1 = statement.toUpperCase();
    io:println("ToUpper: ", s1);
    }

    string[] responseKeys = responseMap.keys();
    foreach var key in responseKeys {
        io.println("hello".toUpperAscii()); 
        commandMap[key.toUpperAscii()] = responseMap[key];
        io:println(responseMap.keys());
    }
foreach var [k, v] in words.entries() {
   io:println("letter: ", k, ", word: ", v);
 }

When building I am getting an error saying 
error: src:0.0.0::interceptors/digital_banking_interceptor.bal:136:17: undefined function 'string.toUpperCase' , toUpperAscii().
Also i am getting error saying unexpected token [  and undefined function entries()

### Affected Product Version:

Micro-gateway3.0.2

### Environment details (with versions):
- OS: Windows
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
Hi @skz363 
MGW 3.0.2 is implemeted on top of ballerina `0.990.x` series. Therefore if you are adding any ballerina source code to MGW `3.0.x` you need to use `0.990.x` ballerina syntax.
For example `toUpperCase()` should be `toUpper()` in `0.990.x` syntax. 

You might be able to get some help from [0.991 documentation](https://v0-991.ballerina.io/learn/api-docs/ballerina/primitive-types.html#string). Also to get ballerina dev's help you can join their [slack channel](https://ballerina.io/community/slack/).

We are currently working on releasing a new MGW version supporting ballerina 1.x. You can try that out if you take build from the master branch. Please note its a WIP.

**Comment by praminda** [comment]
I'm closing the issue with the answer provided. Feel free to reopen if you need further clarification
