### ISSUE TITLE
Refactor code for getting API level and resource level security schemes from swagger definition

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#940]
### Describe your problem(s)

We need to honour the values comes from the swagger. If the security definitions are not defined, then oauth2 should be added.

### Describe your solution

It is better to remove unnecessary Basic auth's isRequired and isOptional logic.

### How will you implement it

---
#### Related Issues:
#931

**Comment by AmaliMatharaarachchi** [comment]
@Rajith90 @praminda if someone defined only apikey security for a resource in the swagger, do we add auth2 security too for that resource?

**Comment by praminda** [comment]
hmm, if we add oauth2 automatically that means we are forcing oauth2 right? Even when customer only need apiKey auth?

**Comment by AmaliMatharaarachchi** [comment]
@praminda if it has apikey security in api definition then oauth2 won’t be added by default. Oauth2 will be added by default only if any other security scheme is not defined.
