### ISSUE TITLE
Restructure Microgateway toolkit and runtime distribution.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#943]
### Describe your problem(s)
With the changes introduced in jballerina 1.1.0, it is not required to have ballerina runtime and the other dependent jar for the runtime. Overall, this will reduce the microgateway runtime distribution's size.

### Describe your solution
Remove the unwanted jar, artifacts from both runtime and toolkit distribution.

---
#### Related Issues:
https://github.com/wso2/product-microgateway/issues/921

#### Suggested Labels:
Improvement

**Comment by praminda** [comment]
With the solution provided for this issue. We'll need to update the docs with new steps for docker QSG and `ballerina.home` placeholder replacement in configs
