### ISSUE TITLE
Details on Keystore password is missing

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-microgateway#949]
### Description:

In all the certificate import/export instructions the Keystore password details are missing. For a user who is new to the WSO2/Ballerina ecosystem, those details (default Keystore password in WSO2 products and B7A)are new.
### Content Positioning in Documentation:

- Link: https://docs.wso2.com/display/MG300/Configuration+for+WSO2+API+Manager+3.0.0

- Heading (& Step):Configuring the Microgateway 3.0.x Toolkit and Configuring the Microgateway 3.0.x Runtime

- Any other reference:

---

**Comment by praminda** [comment]
+DocTeam 
Shall we add default ballerina keystore password to linked document as a note?

**Comment by Rajith90** [comment]
Added the default key store and trust store passwords to the document
