### ISSUE TITLE
Malformed URL error, when no sandbox endpoint is defined

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#963]
### Description:
If the openAPI definition contains only the "x-wso2-production-endpoints", the following error message pops when the build command is executed.
`micro-gw: Malformed URL is provided: '/'.`

Although there is no sandbox-endpoint is defined, a sandbox endpoint object is created with the value "/". That is the reason for this behavior.

### Steps to reproduce:
This is the sample openAPI file used.

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: echo
x-wso2-basePath: /echo/1.0.0
x-wso2-production-endpoints:
  urls:
  - http://10.0.1.148:8688/
paths:
  /:
    post:
      summary: echos the request
      operationId: echoRequest
      responses:
        '200':
          description: Expected response to a valid request
```

### Affected Product Version:
3.1.0-M1

### Environment details (with versions):
- OS: Mac OS Mojave

---

**Comment by praminda** [comment]
This is also reproducible when `servers` object is missing in the openapi 3 definition

**Comment by praminda** [comment]
Duplicates #1044
