### ISSUE TITLE
Support Application level security of WSO2 API Manager

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#964]
### Describe your problem(s)

Support x-wso2-application-security extension. 

API Manager support Application level security types - apikey, basic auth and oauth2. When we import an API from API Manager, the  x-wso2-api-security contains those allowed security types for the API. 

### How will you implement it

---

**Comment by praminda** [comment]
Can you explain why we need this and what exactly is required from apim and mgw to implement this?

**Comment by AmaliMatharaarachchi** [comment]
In API Manager when apikey security is enabled, 
both query and header In types are supported with name apikey.

api_key_query: 
        type: "apiKey"
        name: "apikey"
        in: "query"
api_key_header: 
        type: "apiKey"
        name: "apikey"
        in: "header"

**Comment by AmaliMatharaarachchi** [comment]
@praminda thanks. updated the issue description
