### ISSUE TITLE
Document the usage of cli-config.toml config file

### ISSUE THREAD

**Issue by dinusha-dilrukshi** [wso2/product-microgateway#97]
**Description:**
If APIM is running on a different host/port than localhost:9443, then "micro--gw setup" command fails with the error "Error occurred while communicate with DCR endpoint".

Config Properties in cli-config.toml need to document alone with their usage. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praminda** [comment]
Configurations and the CLI tooklit has been updated with many changes after this issue was opened. Hope this will help with any issues you have related to config documentation 
https://docs.wso2.com/display/MG270/Microgateway+Configurations
