### ISSUE TITLE
Document supported extensions 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#990]
### Description:

https://github.com/wso2/product-microgateway/wiki/Open-Api-Extensions 
We have to provide a documentation for supported swagger extensions 
### Content Positioning in Documentation:

- Link:

- Heading (& Step):

- Any other reference:

---

**Comment by Rajith90** [comment]
This is updated in the docs
https://docs.wso2.com/display/MG310/OpenAPI+Extensions
https://mg.docs.wso2.com/en/latest/concepts/openapi-extensions/
