### ISSUE TITLE
Backend jwt is not sent when using jwt auth tokens

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#991]
### Description:
When Using APIM 3.0.0 the backend jwt is sent in a claim called "backednJWT". We should forward this token to the backend using either x-jwt-assertion header or a configurable header.

### Steps to reproduce:
1. Enable back end jwt generation from APIOM 3.0.0
2. Get a jwt token
3. Send a microgateway an API request with that jwt.
Then check in the trace logs the jwt intended for the backend is not sent to the back end
### Affected Product Version:
3.1.0-m2
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by AmaliMatharaarachchi** [comment]
With PR https://github.com/wso2/product-microgateway/pull/1049, if Backend JWT is provided under backendJwt claim in JWT, it will be send with the jwtConfig.header header name to the backend.
