### ISSUE TITLE
Documenting how to write filter extensions for microgateway

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-microgateway#994]
### Description:
Current documentation has not been included in the way how can write a filter extension for specific requirements in microGW. It is good to have such documentation for a proper understanding of filtering HTTP requests in Ballerina.

### Content Positioning in Documentation:

- Link:

- Heading (& Step):

- Any other reference:

**Comment by praminda** [comment]
@HiranyaKavishani Please don't remove mandatory fields from issue template. I've added them back

**Comment by AmaliMatharaarachchi** [comment]
Refer document https://docs.wso2.com/display/MG310/Adding+Extension+Points#AddingExtensionPoints-Extensionfilter
